<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<?php if ($block->getInfo()->getAdditionalInformation()): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($block->getInfo()->getAdditionalInformation() as $label => $value): ?>
            <tr>
                <th scope="row"><?= $block->getLabel($label) ?></th>
                <td>
                    <?= /* @noEscape */
                    nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
<?= $block->getChildHtml() ?>
