<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/PdfTemplates
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-pdf-invoice-pro
 */
?>
<div id="" data-resizable="true" data-resizable-handle="table" class="pdf-element element_total"style="height: auto !important;">
    <table cellpadding="0" cellspacing="0" width="100%" height="100%" class="pdf-table" style="border-width: 0; border-style: solid">
        <tr class="pdf-table-item pdf-table-item-total">
            <td class="pdf-table-label translate_subtotal">SUBTOTAL</td>
            <td class="pdf-table-value">$216.60</td>
        </tr>
        <tr class="pdf-table-item pdf-table-item-total">
            <td class="pdf-table-label translate_tax">TAX (15%)</td>
            <td class="pdf-table-value">$72.20</td>
        </tr>
        <tr class="pdf-table-item pdf-table-item-grand-total">
            <td class="pdf-table-label translate_grand_total">ORDER TOTAL</td>
            <td class="pdf-table-value">$288.80</td>
        </tr>
    </table>
</div>
