<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var \MageWorx\OrderEditor\Block\Adminhtml\Sales\Order\Edit\Form\Account\Modal $block */ ?>
<?php
/**
 * Modal window container. Customers grid is located inside after initialization.
 * @see app/code/MageWorx/OrderEditor/view/adminhtml/web/js/order/edit/form/account/modal.js
 */
?>
<div id="select-a-customer-modal" style="display:none;"></div>
