<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $exist = false ?>
<?php $child = null ?>
<?php $settings = ' ' ?>
<div class="edit-static-form">
	<div class="line">
        <div class="col-des-12 builder-title">
			<h2><?php echo __('Testimonial Block') ?></h2>
		</div>
	</div>
		<form id="section-form" enctype="multipart/form-data" method="POST" action="<?php echo $this->getUrl('fbuilder/element/save') ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <?php if ($pageId = $this->getRequest()->getParam('page_id')): ?>
            <input type="hidden" name="page_id" value="<?php echo $pageId ?>">
        <?php else: ?>
            <input type="hidden" name="product_id" value="<?php echo $this->getRequest()->getParam('product_id') ?>">
            <input type="hidden" name="overriden" value="<?php echo $this->getRequest()->getParam('overriden') ?>">
        <?php endif ?>
        <input type="hidden" name="page_type" value="<?php echo $this->getRequest()->getParam('page_type') ?>">
        <input id="block_type" type="hidden" name="type" value="testimonial">
        <input id="block_block_name" type="hidden" name="block_name" value="<?php echo $params['block'] ?>">
        <?php if (isset($params['id'])): ?>
            <?php
                $child =  $this->getModel('MGS\Fbuilder\Model\Child')->load($params['id']);
                $exist = true;
                $settings = json_decode($child->getSetting(), true);
            ?>
            <input type="hidden" name="child_id" value="<?php echo $params['id'] ?>">
        <?php endif ?>
        <div class="mgs-tab data items product" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php
                echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setExist($exist)
                    ->setBuilderChild($child)
                    ->setDisableContent(1)
                    ->setBuilderHelper($helper)
                    ->setTemplate('MGS_Fbuilder::panel/create/element/widgets/general_tab.phtml')->toHtml() ;
            ?>

        <div class="data item title" aria-labeledby="tab-label-additional-title" data-role="collapsible" id="tab-label-additional">
                <a class="data switch" tabindex="-1" data-toggle="switch" href="#additional" id="tab-label-additional-title">
                    <?php echo __('Testimonial Config') ?>
                </a>
        </div>

        <div class="data item content" id="additional" data-role="content" style="display:none">
			<div class="form-group line">
                <label for="limit" class="col-des-3 control-label"><?php echo __('Number of testimonial to display') ?></label>
                <div class="col-des-8">
                    <input type="text" id="limit" class="input-text required-entry validate-number" name="setting[limit]"<?php if ($exist): ?> value="<?php echo $settings['limit'] ?>"<?php endif ?> />
                </div>
            </div>
			<div class="form-group line">
                <label for="perrow" class="col-des-3 control-label"><?php echo __('Items per row') ?></label>
                <div class="col-des-8">
                    <select id="perrow" class="input-text" name="setting[perrow]">
                        <option value="1"<?php if ($exist && ($settings['perrow']==1)): ?> selected="selected"<?php endif ?>>1</option>
                        <option value="2"<?php if ($exist && ($settings['perrow']==2)): ?> selected="selected"<?php endif ?>>2</option>
                        <option value="3"<?php if ($exist && ($settings['perrow']==3)): ?> selected="selected"<?php endif ?>>3</option>
                        <option value="4"<?php if ($exist && ($settings['perrow']==4)): ?> selected="selected"<?php endif ?>>4</option>
                    </select>
                </div>
            </div>
            <div class="form-group line">
                <label for="perrow_tablet" class="col-des-3 control-label"><?php echo __('Items per row (Tablet)') ?></label>
                <div class="col-des-8">
                    <select id="perrow_tablet" class="input-text" name="setting[perrow_tablet]">
                        <option value="1"<?php if ($exist && ($settings['perrow_tablet']==1)): ?> selected="selected"<?php endif ?>>1</option>
                        <option value="2"<?php if ($exist && ($settings['perrow_tablet']==2)): ?> selected="selected"<?php endif ?>>2</option>
                        <option value="3"<?php if ($exist && ($settings['perrow_tablet']==3)): ?> selected="selected"<?php endif ?>>3</option>
                        <option value="4"<?php if ($exist && ($settings['perrow_tablet']==4)): ?> selected="selected"<?php endif ?>>4</option>
                    </select>
                </div>
            </div>
            <div class="form-group line">
                <label for="perrow_mobile" class="col-des-3 control-label"><?php echo __('Items per row (Mobile)') ?></label>
                <div class="col-des-8">
                    <select id="perrow_mobile" class="input-text" name="setting[perrow_mobile]">
                        <option value="1"<?php if ($exist && ($settings['perrow_mobile']==1)): ?> selected="selected"<?php endif ?>>1</option>
                        <option value="2"<?php if ($exist && ($settings['perrow_mobile']==2)): ?> selected="selected"<?php endif ?>>2</option>
                        <option value="3"<?php if ($exist && ($settings['perrow_mobile']==3)): ?> selected="selected"<?php endif ?>>3</option>
                        <option value="4"<?php if ($exist && ($settings['perrow_mobile']==4)): ?> selected="selected"<?php endif ?>>4</option>
                    </select>
                </div>
            </div>
			<div class="form-group line">
                <label for="template" class="col-des-3 control-label"><?php echo __('Template') ?></label>
            	<div class="col-des-8">
					<select id="template" class="input-text" name="setting[template]">
						<option value="default_template"<?php if($exist && ($settings['template']=='default_template')): ?> selected="selected"<?php endif ?>><?php echo __('Default Template') ?></option>
						<option value="center_content"<?php if($exist && ($settings['template']=='center_content')): ?> selected="selected"<?php endif ?>><?php echo __('Center Content') ?></option>
						<option value="boxed_content"<?php if($exist && ($settings['template']=='boxed_content')): ?> selected="selected"<?php endif ?>><?php echo __('Boxed Content') ?></option>
					</select>
                </div>
            </div>
            <div class="form-group line" id="use-slider">
                <label for="use_slider" class="col-des-3 control-label"><?php echo __('Use slider') ?></label>
                <div class="col-des-8">
                    <div class="admin__actions-switch" data-role="switcher">
                        <input type="checkbox"<?php if ($exist && $settings['use_slider']): ?> checked="checked"<?php endif ?> value="1" name="setting[use_slider]" id="use_slider" class="admin__actions-switch-checkbox" onclick="useSlider()">
                        <label for="use_slider" class="admin__actions-switch-label">
                            <span data-text-off="<?php echo __('No') ?>" data-text-on="<?php echo __('Yes') ?>" class="admin__actions-switch-text"></span>
                        </label>
                    </div>
                </div>
            </div>
            <?php
                echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setExist($exist)
					->setSettings($settings)
                    ->setDisableSliderMargin(1)
                    ->setTemplate('MGS_Fbuilder::panel/create/element/widgets/slider_setting.phtml')->toHtml() ;
            ?>
            <div class="line form-group">
                <div class="col-des-8">
                    <div class="line form-group">
                            <h4 class="no-margin-top col-des-12"><?php echo __('Name') ?></h4>
                    </div>
                    <div class="line form-group fields">
                        <div class="col-des-6">
                            <label for="name_font_size" class="control-label"><?php echo __('Font size') ?></label><br/>
                            <input type="text" class="input-text" id="name_font_size" name="setting[name_font_size]"<?php if ($exist && $settings['name_font_size']): ?> value="<?php echo $settings['name_font_size'] ?>"<?php endif ?> onchange="changeProfileStyle()"/>
                        </div> 
                        <div class="col-des-6">
                            <label for="name_color" class="control-label"><?php echo __('Color') ?></label><br/>
                            <input type="text" class="input-text color-input" id="name_color" name="setting[name_color]"<?php if ($exist && $settings['name_color']): ?> value="<?php echo $settings['name_color'] ?>"<?php endif ?> onchange="changeProfileStyle()" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="line form-group">
                <div class="col-des-8">
                    <div class="line form-group">
                            <h4 class="no-margin-top col-des-12"><?php echo __('Info') ?></h4>
                    </div>
                    <div class="line form-group fields">
                        <div class="col-des-6">
                            <label for="info_font_size" class="control-label"><?php echo __('Font size') ?></label><br/>
                            <input type="text" class="input-text" id="info_font_size" name="setting[info_font_size]"<?php if ($exist && $settings['info_font_size']): ?> value="<?php echo $settings['info_font_size'] ?>"<?php endif ?>onchange="changeProfileStyle()" />
                        </div> 
                        <div class="col-des-6">
                            <label for="info_color" class="control-label"><?php echo __('Color') ?></label><br/>
                            <input type="text" class="input-text color-input" id="info_color" name="setting[info_color]"<?php if ($exist && $settings['info_color']): ?> value="<?php echo $settings['info_color'] ?>"<?php endif ?> onchange="changeProfileStyle()"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="line form-group">
                <div class="col-des-8">
                    <div class="line form-group">
                            <h4 class="no-margin-top col-des-12"><?php echo __('Content') ?></h4>
                    </div>
                    <div class="line form-group fields">
                        <div class="col-des-6">
                            <label for="content_font_size" class="control-label"><?php echo __('Font size') ?></label><br/>
                            <input type="text" class="input-text" id="content_font_size" name="setting[content_font_size]"<?php if ($exist && $settings['content_font_size']): ?> value="<?php echo $settings['content_font_size'] ?>"<?php endif ?>onchange="changeProfileStyle()" />
                        </div> 
                        <div class="col-des-6">
                            <label for="content_color" class="control-label"><?php echo __('Color') ?></label><br/>
                            <input type="text" class="input-text color-input" id="content_color" name="setting[content_color]"<?php if ($exist && $settings['content_color']): ?> value="<?php echo $settings['content_color'] ?>"<?php endif ?> onchange="changeProfileStyle()" />
                        </div>
                    </div>
                </div>
            </div>
            <style type="text/css" id="testimonial-custom-css"></style>
        </div>
		    
		<?php if ($exist): ?>
                <?php
                    echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                        ->setExist($exist)
                        ->setBuilderChild($child)
                        ->setBuilderHelper($helper)
                        ->setTemplate('MGS_Fbuilder::panel/create/element/widgets/code_tab.phtml')->toHtml() ;
                ?>
            <?php endif ?>
        </div>
		
		<div class="line">
            <div class="form-group">
                <div class="col-des-12 builder-action">
                    <div class="buttons">
                        <?php if (!$exist): ?>
                            <button type="button" class="action" onclick="history.go(-1)"><span><?php echo __('Back') ?></span></button>
                        <?php endif ?>
                        <button type="submit" class="action primary"><span><?php echo __('Submit') ?></span></button>
                    </div>
                </div>
            </div>
        </div>
	</form>
</div>
<script>
function changeProfileStyle(){
    require([
        'jquery',
    ], function(jQuery) {
        (function($){
            name_font_size = $('#name_font_size').val();
            name_color = $('#name_color').val();
            info_font_size = $('#info_font_size').val();
            info_color = $('#info_color').val();
            content_size = $('content_size').val();
            content_color = $('#content_color').val();
            customStyle = '*{}';
            if(name_font_size!=''){
                    customStyle += '.mgs-testimonial .testimonial-content .name{font-size:'+name_font_size+'px}';
                }
            if(name_color!=''){
                customStyle += '.mgs-testimonial .testimonial-content .name{color:'+name_color+'}';
            }
            if(info_font_size!=''){
                    customStyle += '.mgs-testimonial .testimonial-content .infomation{font-size:'+info_font_size+'px}';
                }
            if(info_color!=''){
                customStyle += '.mgs-testimonial .testimonial-content .infomation{color:'+info_color+'}';
            }
            if(content_size!=''){
                    customStyle += '.mgs-testimonial .testimonial-content blockquote{font-size:'+content_size+'px}';
                }
            if(content_color!=''){
                customStyle += '.mgs-testimonial .testimonial-content blockquote{color:'+content_color+'}';
            }
            $('#profile-custom-css').html(customStyle);
        })
    })
}
</script>

		
