<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$nofitmentInstallerId = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('installer/general/no_fitment_installer');
$mobileVanfittingInstallerId = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('installer/general/mobilevan_fitment_service_installer');
$installerList = $objectManager->get('Ecomteck\StoreLocator\Model\ResourceModel\Stores\Collection')
	->addFieldToFilter('status', ['eq' => '1'])
	->addFieldToFilter('stores_id', ['neq' => $nofitmentInstallerId]) /* exclude no fitment installer id*/
	->addFieldToFilter('stores_id', ['neq' => $mobileVanfittingInstallerId]); /* exclude no fitment installer id*/
$installerList->setOrder('position', 'ASC');
$gmapApiKey = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('ecomteck_storelocator/map/api_key');

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeCode = $storeManager->getStore()->getCode();
?>
<div class="storelocator">
	<div class="sub-banner">
		<div class="image-wrap no-position">
			<picture>
				<source class="lazyload" srcset="<?= $block->getViewFileUrl('images/blank.png'); ?>"
					data-srcset="<?= $block->getViewFileUrl('images/banner/storelocator-banner.webp'); ?>">
				<source class="lazyload" srcset="<?= $block->getViewFileUrl('images/blank.png'); ?>"
					data-srcset="<?= $block->getViewFileUrl('images/banner/storelocator-banner.jpg'); ?>">
				<img class="lazyload" src="<?= $block->getViewFileUrl('images/blank.png'); ?>" alt="" width="1920px"
					height="943px" data-src="<?= $block->getViewFileUrl('images/banner/storelocator-banner.jpg'); ?>">
			</picture>
		</div>
	</div>

	<div class="container custom-width-1240">

		<div class="location-search">
			<h1>
				<?php echo __('TYRE SHOP NEAR ME - SEARCH YOUR LOCATION'); ?>
			</h1>
			<div class="location-search-wrap">
				<div class="d-flex flex-wrap align-items-center justify-content-center">
					<input id="tyinstaller" name="installerarea" type="text"
						placeholder="<?php //echo __('Enter a location...'); ?>">
					<div class="serach-distance" style="display:none;">
						<select id="serach_distance" class="input_select dropdown-select">
							<option value="30" selected>30 Km</option>
						</select>
					</div>
					<button type="submit" id="calculatedistace"
						class="action-save button button-primary-100 text-uppercase button-rounded filled-slide-right"><span>
							<?php echo __('SEARCH LOCATION'); ?>
						</span></button>
				</div>
			</div>
		</div>


		<?php if (count($installerList) > 0): ?>
			<div class="installer-list hide">
				<div class="ship-to-installer">
					<div class="row allInstallersRow">
						<?php foreach ($installerList as $installer): ?>
							<div class="col-12 col-sm-12 col-md-6 col-lg-6 installerCol6"
								data-lat="<?php echo $installer['latitude'] ?>"
								data-lng="<?php echo $installer['longitude'] ?>">
								<div class="installer hover-transition" data-lat="<?php echo $installer['latitude'] ?>"
									data-lng="<?php echo $installer['longitude'] ?>">
									<div class="installer_detail">
										<div class="installer_title">
											<div class="upper_right">
												<div class="installer_name">
													<span class="">
														<?php if ($storeCode == 'en'): ?>
															<?php echo __($installer['name']); ?>
														<?php else: ?>
															<?php echo __($installer['name_rtl']);?>
															<?php //echo __($installer['name']); ?>
														<?php endif; ?>
													</span>
												</div>
												<div class="address d-flex align-items-center">
													<span class="location-icon align-self-start"><svg
															xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
															<path
																d="M272 192C272 236.2 236.2 272 192 272C147.8 272 112 236.2 112 192C112 147.8 147.8 112 192 112C236.2 112 272 147.8 272 192zM192 240C218.5 240 240 218.5 240 192C240 165.5 218.5 144 192 144C165.5 144 144 165.5 144 192C144 218.5 165.5 240 192 240zM384 192C384 279.4 267 435 215.7 499.2C203.4 514.5 180.6 514.5 168.3 499.2C116.1 435 0 279.4 0 192C0 85.96 85.96 0 192 0C298 0 384 85.96 384 192H384zM192 32C103.6 32 32 103.6 32 192C32 207.6 37.43 229 48.56 255.4C59.47 281.3 74.8 309.4 92.14 337.5C126.2 392.8 166.6 445.7 192 477.6C217.4 445.7 257.8 392.8 291.9 337.5C309.2 309.4 324.5 281.3 335.4 255.4C346.6 229 352 207.6 352 192C352 103.6 280.4 32 192 32z" />
														</svg>
													</span>
													<span>
														<?php if ($storeCode == 'en'): ?>
															<?php echo __($installer['address']); ?>
														<?php else: ?>
															<?php echo __($installer['address_rtl']); ?>
															<?php //echo __($installer['address']); ?>
														<?php endif; ?>
													</span>
												</div>
											</div>
											<div class="upper_left">
												<div class="distance" style="display: none;">
													<span class="miles"></span>
													<span class="distance-tag">
														<?php echo __('from you') ?>
													</span>
												</div>
												<div class="rating-summary" style="display: none;">
													<div class="rating-result" title="100%">
														<span style="width:100%"><span>0%</span></span>
													</div>
												</div>
											</div>
											<div class="shop_timing_block">
												<div class="installer_date_time">
													<div class="opening_hours_text1 d-flex align-items-center">
														<span class="icon align-self-start">
															<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
																<path
																	d="M240 112C240 103.2 247.2 96 256 96C264.8 96 272 103.2 272 112V247.4L360.9 306.7C368.2 311.6 370.2 321.5 365.3 328.9C360.4 336.2 350.5 338.2 343.1 333.3L247.1 269.3C242.7 266.3 239.1 261.3 239.1 256L240 112zM256 0C397.4 0 512 114.6 512 256C512 397.4 397.4 512 256 512C114.6 512 0 397.4 0 256C0 114.6 114.6 0 256 0zM32 256C32 379.7 132.3 480 256 480C379.7 480 480 379.7 480 256C480 132.3 379.7 32 256 32C132.3 32 32 132.3 32 256z" />
															</svg> </span>
														<span>
															<?php if ($storeCode == 'en'): ?>
																<?php echo __($installer['opening_hours_text1']); ?>
															<?php else: ?>
																<?php echo __($installer['opening_hours_text1_rtl']); ?>
																<?php //echo __($installer['opening_hours_text1']); ?>
															<?php endif; ?>
														</span>
													</div>
													<div class="opening_hours_text2 d-flex align-items-center">
														<span class="icon align-self-start">
															<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
																<path
																	d="M240 112C240 103.2 247.2 96 256 96C264.8 96 272 103.2 272 112V247.4L360.9 306.7C368.2 311.6 370.2 321.5 365.3 328.9C360.4 336.2 350.5 338.2 343.1 333.3L247.1 269.3C242.7 266.3 239.1 261.3 239.1 256L240 112zM256 0C397.4 0 512 114.6 512 256C512 397.4 397.4 512 256 512C114.6 512 0 397.4 0 256C0 114.6 114.6 0 256 0zM32 256C32 379.7 132.3 480 256 480C379.7 480 480 379.7 480 256C480 132.3 379.7 32 256 32C132.3 32 32 132.3 32 256z" />
															</svg> </span>
														<span>
															<?php if ($storeCode == 'en'): ?>
																<?php echo __($installer['opening_hours_text2']); ?>
															<?php else: ?>
																<?php echo __($installer['opening_hours_text2_rtl']); ?>
																<?php //echo __($installer['opening_hours_text2']); ?>
															<?php endif; ?>
														</span>
													</div>
												</div>
											</div>
										</div>
										<?php if ($installer->getIsmobilevan() != 1): ?>
											<div class="installer-action-custom">
												<div class="google-map-direction">
													<a class="installer-url d-flex justify-content-between align-items-center" href="javascript:void(0)" data-lat="<?php  echo $installer['latitude'] ?>" data-lng="<?php echo $installer['longitude'] ?>" data-bs-toggle="modal" data-bs-target="#installerShowMap" data-bs-placement="top" title="<?php echo __($installer['name']);?>" data-title="<?php echo __($installer['name']);?>">
														<span><?php echo __('See on Map') ?></span>
														<img alt="Google Map" src="<?php echo $this->getViewFileUrl('images/google-maps.png'); ?>">
													</a>
												</div>
											</div>
										<?php endif; ?>
									</div>
								</div>
							</div>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
		<?php else: ?>
			<div class='installer_msg'>
				<?php echo __('No any Installer found!!'); ?>
			</div>
		<?php endif; ?>
	</div>

	<div class="section tyres-fitting-text">
		<div class="container custom-width-1240">
			<h2>
				<?php echo __('Convenient Tyre Fitting with TyresOnline'); ?>
			</h2>
			<p>
				<?php echo __('At TyresOnline, we understand that convenience is key when it comes to fitting your vehicle with new tyres. That’s why we have partnered with the best fitment centers across the KSA to ensure that you can find a location that suits your needs. On this page, you can easily search your area to find fitment centers near you and select the one that’s most convenient. We make tyre fitting easy and hassle-free, so you can get back on the road with confidence.'); ?>
			</p>
		</div>
	</div>

	<div class="section welcome">

		<div class="container-fluid px-0">
			<div class="image-wrap picture loader aspect-custom">
				<picture>
					<source class="lazyload" srcset="<?= $block->getViewFileUrl('images/blank.png'); ?>"
						data-srcset="<?= $block->getViewFileUrl('images/banner/welcome-to-tyres-online-uae-sm.webp'); ?>"
						media="(max-width: 767px)">
					<source class="lazyload" srcset="<?= $block->getViewFileUrl('images/blank.png'); ?>"
						data-srcset="<?= $block->getViewFileUrl('images/banner/welcome-to-tyres-online-uae-sm.jpg'); ?>"
						media="(max-width: 767px)">
					<source class="lazyload" srcset="<?= $block->getViewFileUrl('images/blank.png'); ?>"
						data-srcset="<?= $block->getViewFileUrl('images/banner/welcome-to-tyres-online-uae.webp'); ?>"
						media="(min-width: 768px)">
					<source class="lazyload" srcset="<?= $block->getViewFileUrl('images/blank.png'); ?>"
						data-srcset="<?= $block->getViewFileUrl('images/banner/welcome-to-tyres-online-uae.jpg'); ?>"
						media="(min-width: 768px)">
					<img class="lazyload" src="<?= $block->getViewFileUrl('images/blank.png'); ?>"
						alt="<?php echo __('Welcome To Tyres Online KSA'); ?>" width="1920px" height="943px"
						data-src="<?= $block->getViewFileUrl('images/banner/welcome-to-tyres-online-uae.jpg'); ?>">
				</picture>
			</div>

			<div class="banner-content text-center d-flex flex-wrap align-content-between">
				<div class="top position-relative w-100">
					<div class="shape">
						<picture>
							<source class="lazyload" srcset="<?= $block->getViewFileUrl('images/blank.png'); ?>"
								data-srcset="<?= $block->getViewFileUrl('images/section/Welcome-banner-top-shape.webp'); ?>">
							<img class="lazyload" src="<?= $block->getViewFileUrl('images/blank.png'); ?>"
								alt="<?php echo __('Welcome To Tyres Online KSA'); ?>" width="1920px" height="150px"
								data-src="<?= $block->getViewFileUrl('images/section/Welcome-banner-top-shape.jpg'); ?>">
						</picture>
					</div>
    <div class="heading-style6 white text-center">
      <h2 class="text-uppercase"><?php echo __('TYRE SHOP');?>&nbsp;<span><?php echo __('NEAR ME');?></span></h2>
      <p class="cw1"><?php echo __('We are it! We\'re always online, search and find the tyres you need from the comfort of wherever you are in the KSA.') ?></p>
    </div>
				</div>

				<div class="bottom position-relative w-100">
					 <div class="heading-style6 white text-center">
      <h2 class="text-uppercase"><?php echo __('TYRES IN') ?>&nbsp;<span> <?php echo __('ALL OVER THE KSA') ?></span></h2>
      <p>
	<span><?php echo __('Tyres Riyadh') ?></span>
      	<span><?php echo __('Tyres Jeddah') ?></span>
      	<span><?php echo __('Tyres Dammam') ?></span>
      </p>
  </div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- start Modal for installer map -->
<div class="modal fade installerShowMap" id="installerShowMap" tabindex="-1" role="dialog" aria-labelledby="installerShowMapLabel">
    <div class="modal-dialog modal-dialog-centered modal-custom-width-lg bs-custom-modal" role="document">
      <div class="modal-content">
      	<div class="modal-title"><span></span></div>
      	<span class="close white"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path d="M312.1 375c9.369 9.369 9.369 24.57 0 33.94s-24.57 9.369-33.94 0L160 289.9l-119 119c-9.369 9.369-24.57 9.369-33.94 0s-9.369-24.57 0-33.94L126.1 256L7.027 136.1c-9.369-9.369-9.369-24.57 0-33.94s24.57-9.369 33.94 0L160 222.1l119-119c9.369-9.369 24.57-9.369 33.94 0s9.369 24.57 0 33.94L193.9 256L312.1 375z"></path></svg></span>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-12 modal_body_map">
              <div class="location-map" id="location-map">
                <div style="width: 600px; height: 450px;" id="map_canvas_installer_view_map"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- end Modal for installer map -->
<script type="text/javascript">
  require([
    'jquery'
    ], function ($) {
		var storeCode = '<?php echo $storeCode; ?>';

		var searchlat;
		var searchlong;
		if (document.getElementById('tyinstaller') !=null) {
			var input = document.getElementById('tyinstaller');
			var autocompleteSearch = new google.maps.places.Autocomplete(input);
			autocompleteSearch.setComponentRestrictions({'country': ['sa']});
			autocompleteSearch.addListener('place_changed', function(){
				var placeSearch = autocompleteSearch.getPlace();
				searchlat=placeSearch.geometry.location.lat();
				searchlong=placeSearch.geometry.location.lng();
				jQuery('.clear-btn').removeClass('d-none');
			});
		}

    	jQuery('#calculatedistace').click(function(){
			if(searchlat != "" && searchlong != "" && $('#tyinstaller').val() != "" ) {
				var p1 = new google.maps.LatLng(searchlat, searchlong);
				jQuery('.loading-mask').css('display','block !important');
				jQuery('body').trigger('processStart');
				jQuery('.installer').each(function(i, obj) {
					var p2 = new google.maps.LatLng(jQuery(this).attr('data-lat'), jQuery(this).attr('data-lng'));

					var finalinstallerrdistance=(google.maps.geometry.spherical.computeDistanceBetween(p1, p2) / 1000).toFixed(2);

					finalinstallerrdistance=parseFloat(finalinstallerrdistance);
					if(storeCode == 'en'){
						jQuery(this).find('.miles').html(finalinstallerrdistance+' kms');
					}else{
						jQuery(this).find('.miles').html(' كيلومترات '+finalinstallerrdistance);
					}
				    jQuery(this).find('.distance').show();
					var selectdistance=jQuery('#serach_distance').val();
					//console.log(jQuery(this).attr('data-lat')+'--'+jQuery(this).attr('data-lng')+'---'+searchlong+'--'+searchlat+'--'+finalinstallerrdistance);
					jQuery(this).removeAttr('data-position');
					jQuery(this).attr('data-position',finalinstallerrdistance);
					if(finalinstallerrdistance > selectdistance){
						
							jQuery(this).hide();
					}else{
							jQuery(this).show();
					}
				});
				jQuery('.installerCol6').each(function(i, obj) {
					var p2 = new google.maps.LatLng(jQuery(this).attr('data-lat'), jQuery(this).attr('data-lng'));
					var finalinstallerrdistance=(google.maps.geometry.spherical.computeDistanceBetween(p1, p2) / 1000).toFixed(2);
					finalinstallerrdistance=parseFloat(finalinstallerrdistance);
					jQuery(this).removeAttr('data-position');
					jQuery(this).attr('data-position',finalinstallerrdistance);
					
				});

				/*jQuery('.ship-to-installer .row .col-md-6 div.installer').sort(function (a, b) {

					var contentA =parseInt( jQuery(a).attr('data-position'));
					var contentB =parseInt( jQuery(b).attr('data-position'));
					return (contentA < contentB) ? -1 : (contentA > contentB) ? 1 : 0;
				 }).appendTo(".ship-to-installer");*/
				jQuery('.installerCol6').sort(function (a, b) {
					var contentA =parseInt( jQuery(a).attr('data-position'));
					var contentB =parseInt( jQuery(b).attr('data-position'));
					return (contentA < contentB) ? -1 : (contentA > contentB) ? 1 : 0;
				}).appendTo(".allInstallersRow");
				
				jQuery('.installer-list').removeClass('hide');
				setTimeout(function(){
					 jQuery('body').trigger('processStop'); 
					 jQuery('html,body').animate({
						scrollTop: jQuery(".location-search").offset().top},
					'slow');
					}, 3000);
			}else{
					  jQuery('.installer').each(function(i, obj) {
						  jQuery(this).show();
						  jQuery(this).find('.distance').hide();
						  jQuery(this).find('.miles').html();
					  });		  
			 }
		});
		jQuery('#clear-input').click(function(){
			jQuery('#tyinstaller').val('');
			jQuery('.clear-btn').addClass('d-none');
		});

		$('#installerShowMap').on('show.bs.modal', function(event) {
			var map;
			var myMarker;
			var myLatlng;
			var lat= $(event.relatedTarget).attr('data-lat');
			var lng= $(event.relatedTarget).attr('data-lng');
			var installerName = $(event.relatedTarget).attr('title');
			$('.installerShowMap .modal-title span').text(installerName);
			myLatlng = new google.maps.LatLng(lat, lng);		
			var myOptions = {
			zoom: 18,
			zoomControl: true,
			center: myLatlng,
			mapTypeId: google.maps.MapTypeId.ROADMAP
			};

			map = new google.maps.Map(document.getElementById("map_canvas_installer_view_map"), myOptions);

			myMarker = new google.maps.Marker({
				map: map,
				position: myLatlng,
				draggable: false
			});
			
			myMarker.setMap(map);
			$("#location-map").css("width", "100%");
			$("#map_canvas_installer_view_map").css("width", "100%");		
			google.maps.event.trigger(map, "resize");
			map.setCenter(myLatlng);
		});

		$(".installerShowMap .close").on("click", function () {
			$("#installerShowMap").trigger('click');
		});
});
</script>