<?php
/**
 * Ecomteck_StoreLocator extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Ecomteck
 * @package   Ecomteck_StoreLocator
 * @copyright 2016 Ecomteck
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Ecomteck
 */
?>

<?php /** @var \Ecomteck\StoreLocator\Block\StoreLocator $block */?>
<?php $_store = $block->getCurrentStore();?>
<?php $countryList = $block->storelocatorConfig->getCountries(); ?>
<?php $storeId = $block->storelocatorConfig->getStoreId(); ?>
<?php $distanceSteps = $block->storelocatorConfig->getDinstanceSteps();?>
<?php
$unit = $block->storelocatorConfig->getUnitOfLengthSettings();
if($unit == 'km'){
	$unitText = $block->storelocatorConfig->getTextSettings('kilometer_lang');
} else {
	$unitText = $block->storelocatorConfig->getTextSettings('mile_lang');
}
?>
<?php $filters = $block->getFilters();?>
<div class="bh-sl-container">
	<div id="bh-sl-map-container" class="bh-sl-map-container">
		<div class="sidebar left">
			<div class="bh-sl-form-container">
				<form id="bh-sl-user-location" method="post" action="#">
					
					<div class="form-input">
						<input type="text" id="bh-sl-address" placeholder="<?php echo __('Enter Address')?>" name="bh-sl-address" />
						
					</div>
					<?php if($block->storelocatorConfig->getNameSearchSettings()):?>
					<div class="form-input">
						<input type="text" id="bh-sl-search" placeholder="<?php echo __('Enter Store Name')?>" name="bh-sl-search" />
					</div>
					<?php endif;?>
					<button id="bh-sl-submit" type="submit"><?php echo __('Search for store')?></button>
					<div class="filter-options" id="narrow-by-list" style="padding-top:20px;" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
						<div data-role="collapsible" class="filter-options-item" style="width:100%;">
							<div data-role="title" class="filter-options-title"><?= /* @escapeNotVerified */ __('Filter') ?></div>
							<div data-role="content">
							<div class="bh-sl-filters-container">
											<?php if($block->storelocatorConfig->getMaxDistanceSettings() && $distanceSteps):?>
											<label><?php echo __('Radius:')?></label>
											<select id="bh-sl-maxdistance" name="bh-sl-maxdistance">
												<?php foreach($distanceSteps as $step):?>
												<option value="<?php echo $step['distance']?>"><?php echo $step['distance']. ' '. $unitText?></option>
												<?php endforeach;?>
											</select>
											<?php endif;?>
											<?php foreach($filters as $name => $filter):?>
												<?php if($filter['renderer'] == 'checkbox'):?>
												<ul id="<?php echo $name?>-filters-container" class="bh-sl-filters">
													<li><strong><?php echo $filter['label']?></strong></li>
													<?php foreach($filter['items'] as $item):?>
													<li>
														<label>
															<input type="checkbox" name="<?php echo $name?>" value="<?php echo $item['value']?>"> <?php echo $item['label']?>
														</label>
													</li>
													<?php endforeach;?>
												</ul>
												<?php endif;?>
												<?php if($filter['renderer'] == 'select'):?>
												<ul id="<?php echo $name?>-filters-container" class="bh-sl-filters">
													<li><strong><?php echo $filter['label']?></strong></li>
													<li>
														<select name="<?php echo $name?>">
															<?php foreach($filter['items'] as $item):?>
																<option value="<?php echo $item['value']?>"><?php echo $item['label']?></option>
															<?php endforeach;?>
														</select>
													</li>
												</ul>
												<?php endif;?>
												<?php if($filter['renderer'] == 'radio'):?>
												<ul id="<?php echo $name?>-filters-container" class="bh-sl-filters">
													<li><strong><?php echo $filter['label']?></strong></li>
													<?php foreach($filter['items'] as $item):?>
													<li>
														<label>
															<input type="radio" name="<?php echo $name?>" value="<?php echo $item['value']?>"> <?php echo $item['label']?>
														</label>
													</li>
													<?php endforeach;?>
												</ul>
												<?php endif;?>
											<?php endforeach;?>
										</div>
							</div>
						</div>
					</div>
				</form>
			</div>
			<h3 style="padding:10px"><?php echo __("STORES NEAR YOU")?></h3>
			<div class="bh-sl-loc-list">
				<ul class="list"></ul>
			</div>
			<div class="bh-sl-pagination-container">
				<ol class="bh-sl-pagination"></ol>
			</div>
		</div>
        <div id="bh-sl-map" class="bh-sl-map"></div> 
	</div>
</div>
<script type="text/x-magento-init">
    {
        "*": {

            "ecomteck_storelocator": <?php echo $block->getJsonConfig()?>

        }
    }
</script>
