<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/**
 * @see \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer
 */
/** @var \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer $block */
?>
<?php $_item = $block->getItem() ?>
<?php $items = array_merge([$_item], $_item->getChildrenItems()); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>
<?php $_prevOptionId = '' ?>

<?php if ($block->getOrderOptions() || $block->canDisplayGiftmessage()) : ?>
    <?php $_showlastRow = true ?>
<?php else : ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>
<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('catalogHelper');
?>
<?php foreach ($items as $_item) : ?>
    <?php $block->setPriceDataObject($_item) ?>

    <tr <?= (++$_index==$_count && !$_showlastRow)?' class="border"':'' ?>>
        <?php if (!$_item->getParentItem()) : ?>
        <td class="col-thumbnail">
            <?php //TODO:check bundle parent item thumbnail bug ?>
        </td>
        <td class="col-product">
            <div class="product-title" id="order_item_<?= $block->escapeHtmlAttr($_item->getId()) ?>_title">
                <?= $block->escapeHtml($_item->getName()) ?>
            </div>
            <div class="product-sku-block">
                <span><?= $block->escapeHtml(__('SKU')) ?>:</span>
                <?= /* @noEscape */ implode('<br />', $block->escapeHtml($catalogHelper->splitSku($_item->getSku()))) ?>
            </div>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <?php else : ?>
        <td class="col-thumbnail">
            <?= /* @noEscape */ $block->getColumnHtml($_item, 'thumbnail') ?>
        </td>
        <td class="col-product">
            <div class="option-value"><?= $block->getValueHtml($_item)?></div>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <?php endif; ?>
        <td class="col-status">
            <?php if ($block->canShowPriceInfo($_item)) : ?>
                <?= $block->escapeHtml($_item->getStatus()) ?>
            <?php endif; ?>
        </td>
        <td class="col-price-original">
            <?php if ($block->canShowPriceInfo($_item)) : ?>
                <?= /* @noEscape */ $block->displayPriceAttribute('original_price') ?>
            <?php endif; ?>
        </td>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($_item)) : ?>
                <?= /* @noEscape */ $block->getColumnHtml($_item, 'price'); ?>
            <?php endif; ?>
        </td>
        <td class="col-ordered-qty">
            <?php if ($block->canShowPriceInfo($_item)) : ?>
                <table class="qty-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Ordered')) ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyOrdered() * 1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyInvoiced()) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Invoiced')) ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyInvoiced() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyShipped() && $block->isShipmentSeparately($_item)) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Shipped')) ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyShipped() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyRefunded()) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Refunded')) ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyRefunded() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyCanceled()) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Canceled')) ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyCanceled() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php elseif ($block->isShipmentSeparately($_item)) : ?>
                <table class="qty-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Ordered')) ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyOrdered() * 1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyShipped()) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Shipped')) ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyShipped() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($_item)) : ?>
                <?= /* @noEscape */ $block->getColumnHtml($_item, 'subtotal'); ?>
            <?php endif; ?>
        </td>

        <td class="col-tax-amount">
            <?php if ($block->canShowPriceInfo($_item)) : ?>
                <?= /* @noEscape */ $block->displayPriceAttribute('tax_amount') ?>
            <?php endif; ?>
        </td>
        <td class="col-tax-percent">
            <?php if ($block->canShowPriceInfo($_item)) : ?>
                <?= /* @noEscape */ $block->displayTaxPercent($_item) ?>
            <?php endif; ?>
        </td>
        <td class="col-discont">
            <?php if ($block->canShowPriceInfo($_item)) : ?>
                <?= /* @noEscape */ $block->displayPriceAttribute('discount_amount') ?>
            <?php endif; ?>
        </td>
        <td class="col-total last">
            <?php if ($block->canShowPriceInfo($_item)) : ?>
                <?= /* @noEscape */ $block->getColumnHtml($_item, 'total'); ?>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow) : ?>
    <tr<?php if (!$block->canDisplayGiftmessage()) { echo ' class="border"'; } ?>>
        <td class="col-product">
            <?php if ($block->getOrderOptions()) : ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions() as $option) : ?>
                    <dt><?= $block->escapeHtml($option['label']) ?>:</dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']) : ?>
                        <?= $block->escapeHtml($option['value']);?>
                    <?php else : ?>
                        <?= $block->escapeHtml($block->truncateString($option['value'], 55, '', $_remainder));?>
                        <?php if ($_remainder) :?>
                            ... <span id="<?= $block->escapeHtmlAttr($_id = 'id' . uniqid())?>"><?= $block->escapeHtml($_remainder) ?></span>
                            <script>
require(['prototype'], function(){

    $('<?= $block->escapeJs($_id) ?>').hide();
    $('<?= $block->escapeJs($_id) ?>').up().observe('mouseover', function(){$('<?= $block->escapeJs($_id) ?>').show();});
    $('<?= $block->escapeJs($_id) ?>').up().observe('mouseout',  function(){$('<?= $block->escapeJs($_id) ?>').hide();});

});
</script>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php endif; ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
