<?php
$title = $block->escapeHtml($block->getMethod()->getTitle());
$lableDisplay = [
    'card_type_name',
    'req_card_number',
    'req_card_expiry_date'
];
?>
<dl class="payment-method">
    <dt class="title"><?= /* @noEscape */
        $title ?></dt>
    <?php if ($block->getInfo()->getAdditionalInformation()): ?>
        <dd class="content">
            <table class="data table">
                <caption class="table-caption"><?= /* @noEscape */
                    $title ?></caption>
                <?php foreach ($block->getInfo()->getAdditionalInformation() as $label => $value): ?>
                    <?php if (in_array($label, $lableDisplay)): ?>
                        <tr>
                            <th scope="row"><?= $block->getLabel($label) ?></th>
                            <td>
                                <?= /* @noEscape */
                                nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </table>
        </dd>
    <?php endif; ?>
</dl>
<?= $block->getChildHtml() ?>

