<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<div class="admin__page-section-title">
    <span class="title"><?= $block->escapeHtml($block->getHeaderText()); ?></span>
    <?php if ($block->getButtonsHtml()) : ?>
        <div class="actions" style="float: right"><?= /* @noEscape */ $block->getButtonsHtml() ?></div>
    <?php endif; ?>
</div>
<?= /* @noEscape */ $block->getChildHtml('', true) ?>
