<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var $block \MageWorx\OrderEditor\Block\Adminhtml\Sales\Order\Edit\Form\Items\Data */ ?>
<div class="page-create-order">
    <div class="<?php if ($block->getCustomerId()) : ?>order-details-existing-customer<?php endif; ?>">
        <section id="order-items" class="admin__page-section order-items" data-mage-init='{"loader": {}}'>
            <?= /* @noEscape */ $block->getChildHtml('items') ?>
        </section>
        <div id="order-search" style="display: none" class="admin__page-section order-search-items">
            <?= /* @noEscape */ $block->getChildHtml('search') ?>
        </div>
        <div id="ordereditor_new_totals" style="display: none" class="admin__page-section">
            <?= /* @noEscape */ $block->getChildHtml('temp_totals') ?>
        </div>
        <div class="actions" id="ordereditor-items-actions-block">
            <?= /* @noEscape */ $block->getSubmitButtonHtml() ?>
            <?= /* @noEscape */ $block->getAddProductsButtonHtml() ?>
            <?= /* @noEscape */ $block->getCancelButtonHtml() ?>
            <?= /* @noEscape */ $block->getDiscardChangesButtonHtml() ?>
        </div>
    </div>
</div>
