<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var $block \MageWorx\OrderEditor\Block\Adminhtml\Sales\Order\Edit\Form\Items\Form */ ?>
<form id="order_items_edit_form"
      data-order-config="<?= /* @noEscape */ $block->getOrderDataJson() ?>"
      data-load-base-url="<?= $block->escapeHtml($block->getLoadBlockUrl()) ?>"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      enctype="multipart/form-data">
    <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
    <div id="order-data">
        <?= /* @noEscape */ $block->getChildHtml('data') ?>
    </div>
</form>
<?= /* @noEscape */ $block->getChildHtml('configure') ?>
