<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var \MageWorx\OrderEditor\Block\Adminhtml\Sales\Order\Edit\Form\Items\Grid $block */ ?>

<?php $_items = $block->getItems() ?>

<div class="admin__table-wrapper" id="order-items_grid">
        <table class="data-table admin__table-primary order-tables">
            <thead>
                <tr class="headings">
                    <th class="col-product">
                        <span><?= $block->escapeHtml(__('Product')) ?></span>
                    </th>
                    <th class="col-item-status">
                        <span><?= $block->escapeHtml(__('Item Status')) ?></span>
                    </th>
                    <th class="col-original-price">
                        <span><?= $block->escapeHtml(__('Original Price')) ?></span>
                    </th>
                    <th class="col-price">
                        <span><?= $block->escapeHtml(__('Price')) ?></span>
                    </th>
                    <th class="col-qty">
                        <span><?= $block->escapeHtml(__('Qty')) ?></span>
                    </th>
                    <th class="col-subtotal">
                        <span><?= $block->escapeHtml(__('Subtotal')) ?></span>
                    </th>
                    <th class="col-tax">
                        <span><?= $block->escapeHtml(__('Tax')) ?></span>
                    </th>
                    <th class="col-discount">
                        <span><?= $block->escapeHtml(__('Discount')) ?></span>
                    </th>
                    <th class="col-row-total">
                        <span><?= $block->escapeHtml(__('Row Total')) ?></span>
                    </th>
                    <th class="col-action">
                        <span><?= $block->escapeHtml(__('Action')) ?></span>
                    </th>
                </tr>
            </thead>

            <?php if (empty($_items)) : ?>
                <tbody>
                    <tr class="even">
                        <td class="empty-text" colspan="100">
                            <?= $block->escapeHtml(__('No ordered items')) ?>
                        </td>
                    </tr>
                </tbody>
            <?php else : ?>
                <?= /* @noEscape */ $block->getItemsForm(); ?>
            <?php endif; ?>
        </table>
</div>

<script type="text/javascript">
    // <![CDATA[
    require([
            'MageWorx_OrderEditor/js/order/edit/form/items/form',
            'MageWorx_OrderEditor/js/order/edit/form/items/grid'
        ],
        function(mageworxOrderEditorItemsForm, mageworxOrderEditorItemsGrid) {
            var mageworxOrderEditorItemsForm = new mageworxOrderEditorItemsForm();
            mageworxOrderEditorItemsForm.init(<?= /* @noEscape */ $block->getJsonTaxConfigParams() ?>);

            var mageworxOrderManagerItemsGrid = new mageworxOrderEditorItemsGrid();
            mageworxOrderManagerItemsGrid.init(<?= /* @noEscape */ $block->getJsonGridParams() ?>);
        }
    );
    // ]]>
</script>



