<?php
/**
 * @category   Hdweb
 * @package    Hdweb_Vehicles
 * @author     vicky.hdit@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Hdweb\Vehicles\Controller\Adminhtml\Items;

class GetModels extends \Hdweb\Vehicles\Controller\Adminhtml\Items
{
    /**
     * Items list.
     *
     * @return \Magento\Backend\Model\View\Result\Page
     */
    public function execute()
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $resultJsonFactory = $objectManager->get('\Magento\Framework\Controller\Result\JsonFactory');
        $vehiclesHelper = $objectManager->get('\Hdweb\Vehicles\Helper\Data');
        $wheelApiKey = $vehiclesHelper::WHEEL_SEARCH_APIKEY;

        $make = $this->getRequest()->getParam('make');
        $VehicleModel_url = "https://api.wheel-size.com/v2/models/?user_key=".$wheelApiKey."&make=".$make. "&region=medm";
        $WheelVehicleModel = file_get_contents( $VehicleModel_url);
        $WheelVehicleModel =json_decode($WheelVehicleModel);
        
        $html = '<option value="">Select Model</option>';
        foreach($WheelVehicleModel->data as $modelOption){
            $html .= '<option value="'.$modelOption->slug.'">'.$modelOption->name.'</option>';
        }

        $response['response'] = $html;
        $resultJson = $resultJsonFactory->create();
        return $resultJson->setData($response);
    }
}