<?php
/**
 * @category   Hdweb
 * @package    Hdweb_Vehicles
 * @author     vicky.hdit@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Hdweb\Vehicles\Controller\Adminhtml\Items;

class Save extends \Hdweb\Vehicles\Controller\Adminhtml\Items
{
    public function execute()
    {
        if ($this->getRequest()->getPostValue()) {
            try {
                $model = $this->_objectManager->create('Hdweb\Vehicles\Model\Vehicles');
                $data = $this->getRequest()->getPostValue();

                $adminUser = $this->_objectManager->get('Magento\Backend\Model\Auth\Session')->getUser();
                
                if(isset($data['vehicles_id'])){
                    $data['updated_by'] = $adminUser->getUserId();
                }else{
                    $data['created_by'] = $adminUser->getUserId();
                }

                $inputFilter = new \Magento\Framework\Filter\FilterInput(
                    [],
                    [],
                    $data
                );
                $data = $inputFilter->getUnescaped();
                $id = $this->getRequest()->getParam('id');
                if ($id) {
                    $model->load($id);
                    if ($id != $model->getId()) {
                        throw new \Magento\Framework\Exception\LocalizedException(__('The wrong item is specified.'));
                    }
                }
                $model->setData($data);
                $session = $this->_objectManager->get('Magento\Backend\Model\Session');
                $session->setPageData($model->getData());
                $model->save();
                $this->messageManager->addSuccess(__('You saved the item.'));
                $session->setPageData(false);
                if ($this->getRequest()->getParam('back')) {
                    $this->_redirect('hdweb_vehicles/*/edit', ['id' => $model->getId()]);
                    return;
                }
                $this->_redirect('hdweb_vehicles/*/');
                return;
            } catch (\Magento\Framework\Exception\LocalizedException $e) {
                $this->messageManager->addError($e->getMessage());
                $id = (int)$this->getRequest()->getParam('id');
                if (!empty($id)) {
                    $this->_redirect('hdweb_vehicles/*/edit', ['id' => $id]);
                } else {
                    $this->_redirect('hdweb_vehicles/*/new');
                }
                return;
            } catch (\Exception $e) {
                $this->messageManager->addError(
                    __('Something went wrong while saving the item data. Please review the error log.')
                );
                $this->_objectManager->get('Psr\Log\LoggerInterface')->critical($e);
                $this->_objectManager->get('Magento\Backend\Model\Session')->setPageData($data);
                $this->_redirect('hdweb_vehicles/*/edit', ['id' => $this->getRequest()->getParam('id')]);
                return;
            }
        }
        $this->_redirect('hdweb_vehicles/*/');
    }
}
