<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores()) > 1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <div class="actions dropdown options switcher-options">
            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($block->getStores() as $_lang) : ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                        <?php
                        if ((int)$block->getCurrentStoreId() === 2) {
                            $flgImg = $block->getViewFileUrl('images/icon/en_US.svg');
                        } else {
                            $flgImg = $block->getViewFileUrl('images/icon/ar_SA.svg');
                        }
                        ?>
                        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                <span><?= $block->escapeHtml(__($_lang->getName())) ?></span>
                                <img class="language_flag_img" src="<?= $block->escapeUrl($flgImg) ?>" width="30" height="20" alt="<?= $block->escapeHtmlAttr(__('Language flag')) ?>">
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
