<?php
/**
 * @category   Hdweb
 * @package    Hdweb_Vehicles
 * @author     vicky.hdit@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Hdweb\Vehicles\Model\ResourceModel;

class Vehicles extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('hdweb_vehicles', 'vehicles_id');   //here "hdweb_vehicles" is table name and "vehicles_id" is the primary key of custom table
    }
}