<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Magento 2 Base Package
 */
/**
 * @var \Amasty\Base\Block\Import $block
 */
?>
<script>
    require([
            'jquery',
            'Magento_Ui/js/modal/alert',
            'prototype'
        ], function($) {
            //<![CDATA[
            var entity = $('#entity');
            entity.hide();
            entity.closest('fieldset').find('label.label.admin__field-label').css('visibility','hidden');
            $(entity).val('<?= $block->escapeHtml($block->getImportEntity()) ?>');
            varienImport.handleEntityTypeSelector();
            //]]>
        }
    );
</script>
