<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
/**
 * @var \Magento\Backend\Block\Template $block
 */
?>
<script type="text/javascript">
    setTimeout(function () {
        require([
            'jquery',
            'mage/adminhtml/wysiwyg/tiny_mce/setup'
        ], function ($, wysiwygAdapter /*,  tinymce */) {
            let $target = document.getElementById('history_comment');

            $('[data-wysiwyg-initialize=1]').each(function (index) {
                let $textarea = $(this),
                    htmlId = this.id;

                let config = {
                        tinymce: {
                            init_instance_callback: (editor) => {
                                console.log(`Editor: ${editor.id} is now initialized.`);
                            },
                            height: 500,
                            menubar: false,
                            plugins: [
                                "fullscreen autosave autolink searchreplace visualblocks",
                                "code advlist lists link image charmap print preview anchor",
                                "insertdatetime media table paste"
                            ],
                            toolbar_mode: 'wrap',
                            toolbar: 'undo redo | a11ycheck casechange blocks | bold italic backcolor | alignleft aligncenter alignright alignjustify | restoredraft | bullist numlist checklist outdent indent | removeformat | code table help',
                            autosave_interval: '30s',
                            autosave_retention: '15m',
                            autosave_ask_before_unload: false,
                            autosave_restore_when_empty: true,
                            setup: (editor) => {
                                editor.on('init keydown change', function (e) {
                                    document.getElementById(htmlId).innerText = editor.getContent();
                                });
                            }
                        }
                    }

                if (tinymce && tinymce.majorVersion == 4) {
                    config.tinymce4 = config.tinymce;
                }

                let wswg = new wysiwygAdapter(htmlId, config);
                wswg.setup();
            });
        });

    }, 1000);
</script>
