<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/** @var \MageWorx\OrderEditor\Block\Adminhtml\Sales\Order\Edit\Form\Items\Type\AbstractType $block */
$item          = $block->getOrderItem();
$itemType      = $block->getEditedItemType();
$itemId        = $block->getOrderItemHtmlId();
$parentItemId  = $block->getParentItemHtmlId();
$hasParent     = $block->hasOrderItemParent();
$canEditItem   = true;
$canDeleteItem = $block->getCanDeleteItem();
?>
<tr id="order_item_<?= $block->escapeHtml($itemId); ?>"
    class="type-<?= $block->escapeHtmlAttr($itemType) ?>
    <?php if ($hasParent) : ?> has-parent has-parent-<?= $block->escapeHtmlAttr($parentItemId) ?><?php endif; ?>
    <?php if ($item->getQtyCanceled() + $item->getQtyRefunded() >= $item->getQtyOrdered()): ?> removed_item <?php endif;?>"
    <?php if ($hasParent) : ?> data-parent-id="<?= $block->escapeHtmlAttr($parentItemId) ?>"<?php endif; ?>
    data-item-id="<?= $block->escapeHtmlAttr($itemId) ?>">

    <!-- Name, SKU, configure button, hidden params -->
    <td class="col-product">
        <span class="item_name_<?= $block->escapeHtmlAttr($itemId) ?>"
              id="order_item_<?= $block->escapeHtmlAttr($itemId) ?>_title"><?= $block->escapeHtml($item->getName()) ?></span>
        <div class="product-sku-block">
            <span><?= $block->escapeHtml(__('SKU')) ?>:</span>
            <span class="item_sku_<?= $block->escapeHtmlAttr($itemId) ?>"><?= $block->escapeHtml($item->getSku()) ?></span>
        </div>
        <div class="product-configure-block">
            <?php $button = $block->getConfigureButtonHtml() ?>
            <?php if ($button && !$block->isNewItem()) : ?>
                <?php if (!$block->isCustomOptionsStillAvailable()):?>
                    <div class="message--notice">
                        <p class="text"><?= __('Custom options has been changed since this product ordered. Be careful when making changes!');?></p>
                    </div>
                <?php endif; ?>
                <?= /* @noEscape */ $button; ?>
                <div style="display:none !important;">
                    <input type="hidden" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][product_options]"/>
                    <input type="hidden" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][sku]"/>
                </div>
            <?php endif; ?>
        </div>
        <?php $imgHelper = $block->getImageHelper($item); ?>
        <?php if ($imgHelper) : ?>
            <img src="<?= $block->escapeUrl($imgHelper->resize(90, 90)->getUrl()); ?>"
                 alt="<?= $block->escapeHtmlAttr($itemId) ?>" />
        <?php endif; ?>

        <input type="hidden"
               value="<?= $block->escapeHtmlAttr($item->getId()) ?>"
               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][item_id]"/>
        <input type="hidden"
               value="<?= $block->escapeHtmlAttr($itemType) ?>"
               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][item_type]"/>
        <input type="hidden" class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($item->getProductId()) ?>"
               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][product_id]"/>
        <input type="hidden" class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($block->getPrice('discount_tax_compensation_amount')); ?>"
               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][discount_tax_compensation_amount]"/>
        <input type="hidden" class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($block->getPrice('weee_tax_applied_row_amount')); ?>"
               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][weee_tax_applied_row_amount]"/>
    </td>

    <!-- Item Status -->
    <td class="col-status">
        <?= ($itemType == 'quote') ? $block->escapeHtml(__('New')) : $block->escapeHtml($item->getStatus()); ?>
    </td>

    <!-- Original Price -->
    <td class="col-price-original">
        <?= /* @noEscape */ $block->displayPriceAttribute('original_price') ?>
    </td>

    <!-- Price -->
    <td class="col-price">
        <label><?= $block->escapeHtml(__('Excl.Tax:')) ?>&nbsp;<b><?= /* @noEscape */ $block->getPriceHtml('price'); ?></b></label><br/>
        <span class="currency-span"><?= $block->escapeHtml($block->getOrder()->getOrderCurrency()->getCurrencySymbol());?></span>
        <input type="text" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][price]"
               title="<?= $block->escapeHtmlAttr(__("Price excl tax")) ?>"
               class="mw-order-editor-order-item required-entry validate-number"
               value="<?= $block->escapeHtmlAttr($block->getPrice('price')); ?>"/><br/>
        <input type="hidden" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][orig_price]"
               title="<?= $block->escapeHtmlAttr(__("Orig Price excl tax")) ?>"
               class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($block->getPrice('price')); ?>"/>
        <label><?= $block->escapeHtml(__('Incl.Tax:')) ?>&nbsp;<b>
                <?= /* @noEscape */ $block->getPriceHtml('price_incl_tax'); ?>
            </b>
        </label>
        <br/>
        <span class="currency-span"><?= $block->escapeHtml($block->getOrder()->getOrderCurrency()->getCurrencySymbol());?></span>
        <input type="text" name="item[<?= $block->escapeHtmlAttr($block->escapeHtmlAttr($itemId)) ?>][price_incl_tax]"
               title="<?= $block->escapeHtmlAttr(__("Price incl. tax")) ?>"
               class="mw-order-editor-order-item required-entry validate-number"
               value="<?= $block->escapeHtmlAttr($block->getPrice('price_incl_tax')); ?>"/>
        <input type="hidden" name="item[<?= $block->escapeHtmlAttr($block->escapeHtmlAttr($itemId)) ?>][orig_price_incl_tax]"
               title="<?= $block->escapeHtmlAttr(__("Orig Price incl. tax")) ?>"
               class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($block->getPrice('price_incl_tax')); ?>"/>
    </td>

    <!-- Quantity -->
    <td class="col-qty">
        <table class="qty-table">
            <tr>
                <td><?= $block->escapeHtml(__("Ordered")); ?></td>
                <td><?= $item->getQtyOrdered() * 1; ?></td>
            </tr>
            <?php if ($item->getQtyInvoiced() > 0) : ?>
                <tr>
                    <td><?= $block->escapeHtml(__("Invoiced")) ?></td>
                    <td><?= $item->getQtyInvoiced() * 1; ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($item->getQtyRefunded() > 0) : ?>
                <tr>
                    <td><?= $block->escapeHtml(__("Refunded")) ?></td>
                    <td><?= $item->getQtyRefunded() * 1; ?></td>
                    <input type="hidden" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][orig_qty_refunded]"
                           class="mw-order-editor-order-item orig_qty_refunded_input"
                           data-item-id="<?= $block->escapeHtmlAttr($itemId) ?>"
                           value="<?= $item->getQtyRefunded() * 1; ?>"/>
                </tr>
            <?php endif; ?>
            <?php if ($item->getQtyShipped() > 0) : ?>
                <tr>
                    <td><?= $block->escapeHtml(__("Shipped")) ?></td>
                    <td><?= $item->getQtyShipped() * 1; ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($item->getQtyCanceled() > 0) : ?>
                <tr>
                    <td><?= $block->escapeHtml(__("Canceled")) ?></td>
                    <td><?= $item->getQtyCanceled() * 1; ?></td>
                    <input type="hidden" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][orig_qty_cancelled]"
                           class="mw-order-editor-order-item orig_qty_cancelled_input"
                           data-item-id="<?= $block->escapeHtmlAttr($itemId) ?>"
                           value="<?= $item->getQtyCanceled() * 1; ?>"/>
                </tr>
            <?php endif; ?>
            <tr>
                <td><b><?= $block->escapeHtml(__("New")); ?></b></td>
                <td>
                    <input type="text" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][fact_qty]"
                           class="mw-order-editor-order-item required-entry validate-number qty_input
                            <?= !$canDeleteItem ? 'cancelled' : ''; ?>"
                        <?= !$canDeleteItem ? 'readonly="readonly"' : ''; ?>
                           data-item-id="<?= $block->escapeHtmlAttr($itemId) ?>"
                           value="<?= $block->getItemQty() * 1 ?>"/>
                    <input type="hidden" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][orig_fact_qty]"
                           class="mw-order-editor-order-item orig_qty_input"
                           data-item-id="<?= $block->escapeHtmlAttr($itemId) ?>"
                           value="<?= $block->getItemQty() * 1 ?>"/>
                </td>

                <?php if ($hasParent) : ?>
            <tr>
                <td colspan="2">
                    <?php $parentItemQty = $item->getParentItem()->getQtyOrdered() - $item->getParentItem()
                                                                                          ->getQtyRefunded(); ?>
                    <?php $parentItemQty = $parentItemQty == 0 ? 1 : $parentItemQty * 1; ?>
                    <input type="hidden" value="<?= $block->getItemQty() / $parentItemQty; ?>"
                           name="item[<?= $block->escapeHtmlAttr($itemId) ?>][qty_item_in_bundle]"/>
                    <input type="hidden" value="<?= $block->escapeHtmlAttr($parentItemId) ?>"
                           name="item[<?= $block->escapeHtmlAttr($itemId) ?>][parent]"/>
                </td
            </tr>
        <?php endif; ?>
            </tr>
        </table>
    </td>

    <!-- Subtotal -->
    <td class="col-subtotal">
        <?= $block->escapeHtml(__("Excl.Tax")) ?>:&nbsp;<b><?= /* @noEscape */ $block->getPriceHtml('row_total'); ?></b>
        <br/>
        <span class="currency-span"><?= $block->escapeHtml($block->getOrder()->getOrderCurrency()->getCurrencySymbol());?></span>
        <input type="text" class="mw-order-editor-order-item required-entry validate-number disabled"
               title="<?= $block->escapeHtmlAttr(__("Subtotal excl. tax")) ?>"
               readonly="readonly"
               value="<?= $block->escapeHtmlAttr($block->getPrice('row_total')); ?>"
               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][subtotal]"/>
        <br/>

        <?= $block->escapeHtml(__("Incl.Tax")) ?>:&nbsp;<b><?= /* @noEscape */ $block->getPriceHtml('row_total_incl_tax'); ?></b>
        <br/>
        <span class="currency-span"><?= $block->escapeHtml($block->getOrder()->getOrderCurrency()->getCurrencySymbol());?></span>
        <input type="text" class="mw-order-editor-order-item required-entry validate-number disabled"
               title="<?= $block->escapeHtmlAttr(__("Subtotal incl. tax")) ?>"
               readonly="readonly"
               value="<?= $block->escapeHtmlAttr($block->getPrice('row_total_incl_tax')); ?>"
               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][subtotal_incl_tax]"/>

        <input type="hidden" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][orig_subtotal]"
               title="<?= $block->escapeHtmlAttr(__("Original subtotal excl tax")) ?>"
               class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($block->getPrice('row_total')); ?>"/>
        <input type="hidden" name="item[<?= $block->escapeHtmlAttr($block->escapeHtmlAttr($itemId)) ?>][orig_subtotal_incl_tax]"
               title="<?= $block->escapeHtmlAttr(__("Original subtotal incl. tax")) ?>"
               class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($block->getPrice('row_total_incl_tax')); ?>"/>
        <input type="hidden" name="item[<?= $block->escapeHtmlAttr($block->escapeHtmlAttr($itemId)) ?>][base_amount_refunded]"
               title="<?= $block->escapeHtmlAttr(__("Base Amount refunded")) ?>"
               class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($block->getPrice('base_amount_refunded')); ?>"/>
        <input type="hidden" name="item[<?= $block->escapeHtmlAttr($block->escapeHtmlAttr($itemId)) ?>][base_amount_cancelled]"
               title="<?= $block->escapeHtmlAttr(__("Base Amount Cancelled")) ?>"
               class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($block->getAmountCancelled()); ?>"/>
        <input type="hidden" name="item[<?= $block->escapeHtmlAttr($block->escapeHtmlAttr($itemId)) ?>][base_amount_cancelled_incl_tax]"
               title="<?= $block->escapeHtmlAttr(__("Base Amount Cancelled Incl. Tax")) ?>"
               class="mw-order-editor-order-item"
               value="<?= $block->escapeHtmlAttr($block->getAmountCancelledInclTax()); ?>"/>

    </td>

    <!-- Tax Amount/Percent -->
    <td class="col-tax">
        <?= $block->escapeHtml(__("Amount")) ?>:&nbsp;<b><?= /* @noEscape */ $block->getPriceHtml('tax_amount'); ?></b>
        <br/>
        <span class="currency-span"><?= $block->escapeHtml($block->getOrder()->getOrderCurrency()->getCurrencySymbol());?></span>
        <input type="text"
               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][tax_amount]"
               readonly="readonly"
               title="<?= $block->escapeHtmlAttr(__("Tax amount")) ?>"
               class="mw-order-editor-order-item required-entry validate-number disabled"
               value="<?= $block->escapeHtmlAttr($block->getPrice('base_tax_amount')); ?>"/>
        <br/>

        <?= $block->escapeHtml(__("Percent")) ?>:&nbsp;<b><?= /* @noEscape */ $block->getPercentHtml('tax_percent'); ?></b>
        <br/>
        <span class="currency-span"><?= '%';?></span>
        <input type="text"
               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][tax_percent]"
               readonly="readonly"
               id="<?= $block->escapeHtmlAttr($block->getPercent('tax_percent')); ?>"
               title="<?= $block->escapeHtmlAttr(__("Tax percent")) ?>"
               class="mw-order-editor-order-item required-entry validate-number disabled"
               value="<?= $block->escapeHtmlAttr($block->getPercent('tax_percent')); ?>"/>

        <br/>

        <?= $block->escapeHtml(__("Tax Rate")) ?>:&nbsp;
        <div class="order-item-applied-rates-container"
             id="order-item-applied-rates-container-<?= $block->escapeHtmlAttr($itemId); ?>">
            <?php
            $activeRates = $block->getItemActiveRates();
            if (!empty($activeRates)) :
                foreach ($activeRates as $activeRate) {
                    $rateHtmlId = $block->escapeHtmlAttr('tax-applied-rates-'
                        . $itemId
                        . '-'
                        . $activeRate->getCode());
                    $rateTitle  = $block->escapeHtmlAttr(
                        $activeRate->getCode() . ' (' . $activeRate->getPercent() . '%)'
                    );
                    ?>
                    <label for="<?= /* @noEscape */ $rateHtmlId; ?>">
                        <b><?= $block->escapeHtml($activeRate->getCode()); ?></b>
                        <br/>
                        <span class="currency-span"><?= '%';?></span>
                        <input name="item[<?=
                        $block->escapeHtmlAttr($itemId);
                        ?>][tax_applied_rates][<?=
                        $block->escapeHtmlAttr($activeRate->getCode())
?>]"
                               id="<?= /* @noEscape */ $rateHtmlId; ?>"
                               title="<?= $block->escapeHtmlAttr($rateTitle); ?>"
                               class="mw-order-editor-order-item tax-applied-rate-code"
                               value="<?= $block->escapeHtmlAttr(round($activeRate->getPercent(), 4)); ?>"
                        />
                    </label>
                    <?php
                }
            else :
                echo $block->escapeHtml(__('No Tax Rate'));
            endif;
            ?>
        </div>
        <div class="order-item-available-rates-container active-rates"
             id="order-item-available-rates-container-<?= $block->escapeHtmlAttr($itemId); ?>">
            <label for="tax-rates-<?= $block->escapeHtmlAttr($itemId); ?>">
                <b><?= $block->escapeHtml(__('Select Rates:')); ?></b>
                <br/>
                <select name="item[<?= $block->escapeHtmlAttr($itemId) ?>][tax_rates][]"
                        id="tax-rates-<?= $block->escapeHtmlAttr($itemId); ?>"
                        title="<?= $block->escapeHtmlAttr(__("Tax Rates")) ?>"
                        class="mw-order-editor-order-item"
                        multiple="multiple"
                        hidden="hidden">
                    <?= /* @noEscape */ $block->renderTaxRatesOptions(); ?>
                </select>
            </label>
        </div>
    </td>

    <!-- Discount Amount/Percent-->
    <td class="col-discount">
        <label><?= $block->escapeHtml(__("Amount")) ?>:&nbsp;<b>
                <?= /* @noEscape */ $block->getPriceHtml('discount_amount'); ?>
            </b>
        </label>
        <br/>
        <span class="currency-span"><?= $block->escapeHtml($block->getOrder()->getOrderCurrency()->getCurrencySymbol());?></span>
        <input type="text" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][discount_amount]"
               class="mw-order-editor-order-item required-entry validate-number
                <?= $block->getPercent('discount_percent') ? ' disabled' : ''; ?>"
               title="<?= $block->escapeHtmlAttr(__("Discount amount")) ?>"
               value="<?= $block->escapeHtmlAttr($block->getPrice('discount_amount')); ?>"/>
        <br/>

        <label><?= $block->escapeHtml(__("Percent")) ?>:&nbsp;
            <b>
                <?= /* @noEscape */ $block->getPercentHtml('discount_percent'); ?>
            </b>
        </label>
        <br/>
        <span class="currency-span"><?= '%';?></span>
        <input type="text" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][discount_percent]"
               title="<?= $block->escapeHtmlAttr(__("Discount percent")) ?>"
               class="mw-order-editor-order-item required-entry validate-number"
               value="<?= $block->escapeHtmlAttr($block->getPercent('discount_percent')); ?>"/>
    </td>

    <!-- Row total -->
    <td class="col-row-total">
        <label><b><?= /* @noEscape */ $block->getItemTotalHtml() ?></b></label><br/>
            <span class="currency-span"><?= $block->escapeHtml($block->getOrder()->getOrderCurrency()->getCurrencySymbol());?></span>
            <input type="text" name="item[<?= $block->escapeHtmlAttr($itemId) ?>][row_total]" readonly="readonly"
                   title="<?= $block->escapeHtmlAttr(__("Total")) ?>"
                   class="mw-order-editor-order-item required-entry validate-number total_input disabled"
                   value="<?= $block->escapeHtmlAttr($block->getItemTotal()); ?>"/>
    </td>

    <!-- Actions -->
    <td class="col-actions last">

        <?php if ($itemType != 'quote') : ?>
            <?php if ($canDeleteItem) : ?>
                <select class="admin__control-select item-action-dropdown"
                        id="action_dropdown_<?= $block->escapeHtmlAttr($itemId) ?>"
                        data-item-id="<?= $block->escapeHtmlAttr($itemId) ?>"
                        <?php if ($hasParent) : ?>data-parent-id="<?= $block->escapeHtmlAttr($parentItemId) ?>"<?php endif; ?>
                        name="item[<?= $block->escapeHtmlAttr($itemId) ?>][action]">
                    <option value=""><?= $block->escapeHtml(__('Please select')) ?></option>
                    <option value="remove" <?php if (!$block->getCanRemove()) { echo "disabled=\"disabled\""; } ?>>
                        <?= $block->escapeHtml(__('Remove')) ?>
                    </option>
                </select>

                <?php if (!$block->getCanRemove()): ?>
                    <span class="mw-oe-unable-to-remove-message">
                        <?= $block->escapeHtml($block->getUnableToRemoveErrorMessage()); ?>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        <?php else : ?>
            <?php if (!$hasParent) : ?>

                <select class="admin__control-select remove_quote_item"
                        data-item-id="<?= $block->escapeHtmlAttr($itemId) ?>"
                        <?php if ($hasParent) : ?>data-parent-id="<?= $block->escapeHtmlAttr($parentItemId) ?>"<?php endif; ?>
                        name="item[<?= $block->escapeHtmlAttr($itemId) ?>][action]">
                    <option value=""><?= $block->escapeHtml(__('Please select')) ?></option>
                    <option value="remove"><?= $block->escapeHtml(__('Remove')) ?></option>
                </select>

            <?php endif; ?>
        <?php endif; ?>
        <?php if ($itemType != 'quote' && $canDeleteItem) : ?>
            <table class="back-to-stock-table">
                <tr>
                    <td><?= $block->escapeHtml(__("Back to stock")) ?></td>
                    <td>
                        <input type="checkbox"
                               class="regular-checkbox back_to_stock"
                               id="item-<?= $block->escapeHtmlAttr($itemId); ?>-back_to_stock"
                               name="item[<?= $block->escapeHtmlAttr($itemId) ?>][back_to_stock]"
                               <?php if ($block->getDefaultBackToStock()) : ?>checked="checked"<?php endif; ?>
                               title="<?= $block->escapeHtmlAttr(__("Back to stock")) ?>"
                               value="1"/>
                        <label for="item-<?= $block->escapeHtmlAttr($itemId); ?>-back_to_stock"></label>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    </td>
</tr>
