<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $blockGrid = $block->getGridHtml();?>
<div class="reports-content advancereports">
    <?php echo $block->getChildHtml('grid.filter.form') ?>  

    <div class="row report-topbar" id="reportTopbar">
        <?php echo $this->getChildHtml('report.topbar') ?>
    </div>
    <div class="row report-chart" id="reportChart">
    <?php echo $this->getChildHtml('report.chart') ?>
    </div> 
    <div class="row report-content-bottom" id="reportContentBottom">
    <?php echo $this->getChildHtml('report.content.bottom') ?>
    </div>
    <div class="row breadcrumbs" id="breadcrumbs">
        <?php echo $this->getChildHtml('report.breadcrumbs') ?>
    </div>      
</div> 


<?php echo $blockGrid; ?>
<script>
require([
    'jquery',
    'mage/backend/validation',
    "prototype"
], function(jQuery){

//<![CDATA[
    jQuery('#filter_form').mage('validation', {errorClass: 'mage-error'});
    function filterFormSubmit() {
        var filters = $$('#filter_form input', '#filter_form select');
        var elements = [];
        for(var i in filters){
            if(filters[i].value && filters[i].value.length && !filters[i].disabled) elements.push(filters[i]);
            console.log(filters[i]);
        } 
        var formData = Base64.encode(Form.serializeElements(elements));
        var filterEncode = formData.replace("=", "");
        if (jQuery('#filter_form').valid()) {
            setLocation('<?php /* @escapeNotVerified */ echo $block->getFilterUrl(); ?>loffilter/'+filterEncode+'/');
        }
    }
//]]>
    window.filterFormSubmit = filterFormSubmit;
});
</script>
