<?php
$helper = $this->helper('MGS\Brand\Helper\Data');
$params = $this->getRequest()->getParams();
?>
<div class="search">
	<div class="content-heading">
		<h3 class="title text-uppercase"><?php echo __('Search Brand') ?></h3>
	</div>
	<div class="search_brand_form">
		<form id="search_brand_form" action="" method="get">
			<div class="control form-group">
				<input id="search_brand"
					   type="text"
					   name="keyword"
					   value="<?php if (isset($params['keyword'])) {
						   echo $params['keyword'];
					   } ?>"
					   placeholder="<?php echo __('Search brand here...'); ?>"
					   class="input-text"
					   autocomplete="off"/>
				<?php if (isset($params['char']) && $params['char'] != ''): ?>
					<input id="search_brand_by_char"
						   type="hidden"
						   name="char"
						   value="<?php echo $params['char']; ?>"/>
				<?php endif; ?>
			</div>
			<div class="actions">
				<button type="submit"
						title="<?php echo $block->escapeHtml(__('Search')) ?>"
						class="action btn btn-primary btn-sm">
					<span><?php echo __('Search'); ?></span>
				</button>
				<?php if (isset($params['keyword']) || isset($params['char'])): ?>
					<button type="button"
							onclick="window.location.href='<?php echo $helper->getBrandUrl(); ?>'"
							title="<?php echo $block->escapeHtml(__('Reset Filter')) ?>"
							class="action btn btn-secondary btn-sm">
						<span><?php echo __('Reset Filter'); ?></span>
					</button>
				<?php endif; ?>
			</div>
		</form>
	</div>
</div>