<?php
$msgBrandHelper = $this->helper('MGS\Brand\Helper\Data');
?>
<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('product_page_settings/show_brand')): ?>
			<?php if ($brand = $block->getBrand()): ?>
				<?php
				if ($block->getConfig('product_page_settings/small_image_width') != '') {
					$width = $block->getConfig('product_page_settings/small_image_width');
				} else {
					$width = 240;
				}
				?>
				<?php 
				$categoryId = 3;
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$categoryObj = $objectManager->get('Magento\Catalog\Model\Category')->load($categoryId);
				$categoryUrl = $categoryObj->getUrl();
				?>
				<div class="product-brand">
					<?php $img = $brand->getSmallImageUrl(); ?>
					<?php if ($img) { ?>
						<div class="brand-image">
							<a title="<?php echo $brand->getName(); ?>" href="<?php echo $msgBrandHelper->getBrandCategoryUrl($brand); ?>">
								<img src="<?php echo $img; ?>" width="307px" height="96px" alt="<?php echo $brand->getName(); ?>" class="lazyload image"/>
							</a>
						</div>
					<?php } ?>
				</div>
			<?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
