<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_productCollection = $block->getCollection();
$viewMode = $block->getViewmode();
/** @var \Magento\Catalog\Helper\Output $_helper */
//$_helper = $block->getData('outputHelper');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$listingHelper = $this->helper('Hdweb\Tyrefinder\Helper\Productlisting');
$image_width = 300;
$image_height = 300;
$currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currency = $currencysymbol->getStore()->getCurrentCurrencyCode();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$tabbyinstallmentmaxvalue = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('productsearch/general/tabbyinstallment');
$tabbyfourday = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('productsearch/general/tabbyfourday');
$getBaseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$tabbyUrl = $getBaseUrl.'tabby-payment-options';
$StockRegistry = $objectManager->get('\Magento\CatalogInventory\Api\StockRegistryInterface');
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$outOfStockPhone = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('hdweb/general/call_us_contact');
$autoPartsAttr = 0; 
$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
if ($viewMode === 'grid') {
	$imageDisplayArea = 'category_page_grid';
	$showDescription = false;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
} else {
	$imageDisplayArea = 'category_page_list';
	$showDescription = true;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
}
?>
<?php if (!$_productCollection->count()): ?>
<div class="category-products">
   <p class="note-msg"><?php echo __('Sorry! We do not have parts for your vehicle.') ?></p>
</div>
<?php else:?>
<div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
	<ol class="products list items product-items product-list list-view regular-product-list d-none d-md-block">
	<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
	<?php foreach ($_productCollection as $_product): ?>
	<?php
	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	$brand = $_helper->productAttribute($_product, $_product->getMgsBrand(), 'mgs_brand');
	$brandDetails = $listingHelper->getBrandDetails($brand); 
	$branimage = $listingHelper->getBrandImageUrl($brandDetails); 
	$brand_title = $brandDetails->getName();
	$productImage = $_imagehelper->init($_product, $imageDisplayArea)->resize($image_width, $image_height)->getUrl();
	$_productNameStripped = $block->stripTags($_product->getName(), null, true);
	$displayName = $_product->getResource()->getAttribute("display_name")->getFrontend()->getValue($_product);
	$tyreSize = '';
	$tyreSize = $listingHelper->getTyreSize($_product, true);
	$warranty_workmanship_mat=$_product->getResource()->getAttribute("warranty_workmanship_mat")->getFrontend()->getValue($_product);
	$warranty_period = $_product->getResource()->getAttribute("warranty_period")->getFrontend()->getValue($_product);
	$year = $_product->getResource()->getAttribute("year")->getFrontend()->getValue($_product);
	$runflat = $_product->getResource()->getAttribute('runflat')->getFrontend()->getValue($_product);
	$youtubeLink = $_product->getResource()->getAttribute('youtube_link')->getFrontend()->getValue($_product);
	$origin = $_product->getResource()->getAttribute('origin')->getFrontend()->getValue($_product);
	$fuel_efficiency = $_product->getResource()->getAttribute("fuel_efficiency")->getFrontend()->getValue($_product);
	$wet_grip = $_product->getResource()->getAttribute("wet_grip")->getFrontend()->getValue($_product);
	$noise_levels = $_product->getResource()->getAttribute("noise_levels")->getFrontend()->getValue($_product);
	$pattern = $_product->getResource()->getAttribute("pattern")->getFrontend()->getValue($_product);
	$perItem=$_product->getResource()->getAttribute("per_item")->getFrontend()->getValue($_product);
	$parts_category = $_product->getResource()->getAttribute("parts_category")->getFrontend()->getValue($_product);
	$postParams = $listBlock->getAddToCartPostParams($_product);
	$set4price = $listingHelper->getSet4price($_product);
	$set1price = $listingHelper->getSet1price($_product);
	$set2price = $listingHelper->getSet2price($_product);
	$productpriceWC = $listingHelper->getSet1priceWithoutCurrency($_product);
	$product_url  = $_product->getProductUrl();
	$tabbyMethodAvailable = $_product->getResource()->getAttribute("tabby_method")->getFrontend()->getValue($_product);
	$tabby_method_class = '';
	$notaabbyinstallerclass = '';
	$set4PriceNumberOnly = str_replace(',', '', $set4price);
	if($tabbyMethodAvailable == 'No' || $set4PriceNumberOnly <= $tabbyfourday || $set4PriceNumberOnly >= $tabbyinstallmentmaxvalue){
	$notaabbyinstallerclass = 'hidetabbyinstaller';
	$tabby_method_class = 'no-tabby';
	}
	$isAnyRuleExist = $AnyRuleExist = $listingHelper->isAnyRuleExist($_product);   
	$borderColor="";    
	$bkgColor="";
	$strikePriceClass = ''; 
	$offer_price = '';   
	if(count($isAnyRuleExist) > 0 ){
	$borderColor='border:2px solid '.$isAnyRuleExist[4];
	$bkgColor='background-color: '.$isAnyRuleExist[4];

	if ($isAnyRuleExist[6] > 3 && $isAnyRuleExist[5] > 0) {
	  $strikePriceClass = 'strike-price';
	}
	}

	$stockQty = 0;
	$prod_qty =  $StockState->getStockQty($_product->getEntityId());
	$isInStock = $StockRegistry->getProductStockStatus($_product->getEntityId());
	if($prod_qty >= 8){
	$stockQty = 8;
	}else{
	$stockQty = $prod_qty;
	}

	$articleNumber = $_product->getResource()->getAttribute("article_number")->getFrontend()->getValue($_product);
	$article_number_org = $_product->getResource()->getAttribute("article_number_org")->getFrontend()->getValue($_product);
	$autoPartsAttr = 0;
	$typeClass= '';
	if($parts_category != 'Tyres'){
	  $tyreSize = $articleNumber;
	  $autoPartsAttr = 1;
	  $typeClass = 'autoparts-type';
	}
	$autoparts_1 = $_product->getResource()->getAttribute("auto_parts_warranty_1")->getFrontend()->getValue($_product);
	$autoparts_2 = $_product->getResource()->getAttribute("auto_parts_warranty_2")->getFrontend()->getValue($_product);
	$auto_parts_inc1 = $_product->getResource()->getAttribute("auto_parts_installation_1")->getFrontend()->getValue($_product);
	$auto_parts_inc2 = $_product->getResource()->getAttribute("auto_parts_installation_2")->getFrontend()->getValue($_product);
	$autoparts_contact = $_product->getResource()->getAttribute("auto_parts_contact_us")->getFrontend()->getValue($_product);
	?>
	<li class="product-box <?php echo $typeClass;?>">
		<div class="row g-0 height-cover">
		  <div class="col-md-6 col-lg-6">
			<div class="left h-100">
			  <div class="row g-0 h-100">
				<?php /*if(count($isAnyRuleExist) > 0): //if offer make col-md-5 */ ?>
				<?php if(isset($isAnyRuleExist[1]) && $isAnyRuleExist[1] != ''):?>
				  <div class="col-md-5 col-lg-5">
					<div class="d-flex row-cols-2 h-100">
					  <div class="offer-image">
						<img src="<?php echo $isAnyRuleExist[1] ?>" class="img_tyre_offer" alt="">
					  </div>
					  <div class="product-image-brand-wrap d-flex flex-wrap h-100">
						  <div class="brand w-100 text-center align-self-start">
							<img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" data-src="<?php echo $branimage ?>" alt="<?php echo $brand_title ?>" class="lazyload"
							  alt="" />
						  </div>
						  <div class="image w-100 align-self-end">
							<a href="<?php echo $product_url;?>" class="d-block link">
							  <img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" data-src="<?php echo $productImage ?>"
								class="lazyload" alt="<?php echo $_productNameStripped ?>" />
							</a>
						  </div>
						</div>
					</div>
				  </div>
				<?php else: // if no offer make col-md-4 ?>
				  <div class="col-md-4 col-lg-4">
					<div class="product-image-brand-wrap d-flex flex-wrap h-100">
					  <div class="brand w-100 text-center <?php echo ($autoPartsAttr) ? 'align-self-center' : 'align-self-start'; ?>">
						<img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" data-src="<?php echo $branimage ?>" alt="<?php echo $brand_title ?>" class="lazyload"
						  alt="" />
					  </div>
					  <?php if(!$autoPartsAttr):?>
						  <div class="image w-100 align-self-end">
							<a href="<?php echo $product_url;?>" class="d-block link">
							  <img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" data-src="<?php echo $productImage ?>"
								class="lazyload" alt="<?php echo $_productNameStripped ?>" />
							</a>
						  </div>
					  <?php endif;?>
					</div>
				  </div>
				<?php endif; ?>
				<?php /* if(count($isAnyRuleExist) > 0): //if offer make col-md-7 */ ?>
				<?php if(isset($isAnyRuleExist[1]) && $isAnyRuleExist[1] != ''):?>
				  <div class="col-md-7 col-lg-7">
				<?php else: // if no offer make col-md-8?>
				  <div class="col-md-8 col-lg-8">
				<?php endif; ?>
				
				  <div class="product-info d-flex flex-wrap h-100">
					<div class="name w-100 align-self-start">
					  <h4 class="fw-bold mb-0"><a href="<?php echo $product_url;?>" title="<?php echo $_productNameStripped ?>"><?php echo __($displayName);?></a></h4>
					  <span class="fw-bold"><?php echo $tyreSize;?></span>
						<?php if($autoPartsAttr && $article_number_org != ''):?>
		<div class="info"><span class="icon bg-red-400 icon-sprite toi-info autoparts-modal-ajax" data-name="<?php echo $_productNameStripped ?>" data-partnumber="<?php echo $articleNumber ?>"></span></div>
	  <?php endif;?>
					</div>
					<div class="additional w-100 align-self-end">
					<?php if($runflat):?> 
					  <div class="run-flat">
						<span class="icon icon-sprite"></span>
					  </div>
					<?php endif;?>
						<?php if($autoPartsAttr):?>
							<?php if($autoparts_1):?>
							  <div class="warranty-style2">
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __($autoparts_1);?>"><?php echo __($autoparts_1);?></span>
							  </div>
							<?php endif;?>
							<?php if($autoparts_2):?>
							  <div class="warranty-style2">
								<span data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __($autoparts_2);?>"><?php echo __($autoparts_2);?></span>
							  </div>
							<?php endif; ?>
						<?php else:?>
							<?php if($warranty_workmanship_mat):?>
							  <div class="offer">
								<span><?php echo __($warranty_workmanship_mat);?></span>
							  </div>
							<?php endif;?>
							<?php if($warranty_period):?>
							  <div class="warranty">
								<span><?php echo __($warranty_period);?></span>
							  </div>
							<?php endif; ?>
						<?php endif;?>
					  <!-- If contact for autoPartsAttr -->
					  <?php if($autoparts_contact):?>
					   <div class="contact-for-vehicle">
						 <span data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __($autoparts_contact);?>"><?php echo __($autoparts_contact);?></span>
					   </div>
					   <?php endif;?>
					</div>
				  </div>
				</div>
			  </div>
			</div>
		  </div>
		  <div class="col-md-6 col-lg-6">
			<div class="right h-100">
			  <div class="row g-0 h-100 tyres-productset4">
				<div class="col-md-4 col-lg-4">
				  <?php if($autoPartsAttr):?>
					<div class="autoparts-feacher-image d-flex flex-wrap h-100 align-items-center justify-content-center">
					  <img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" data-src="<?php echo $productImage ?>" class="lazyload" alt="<?php echo $_productNameStripped ?>" />
					  <div class="hover-block d-flex align-items-center justify-content-center">
						<span><?php echo __('Picture shown is for illustration purpose only.');?></span>
					  </div>
					</div>
				  <?php else:?>
					  <div class="product-features d-flex flex-wrap h-100">
						<div class="mf-year w-100 align-self-start text-center">
						  <span class="fw-bold"><?php echo $year;?></span>
						</div>
						<div class="features-icon w-100 align-self-end">
						  <ul class="list-custom d-flex justify-content-center">
						  <?php if($youtubeLink):?>
							<li class="active info-video" data-izimodal-iframeurl="<?php echo $youtubeLink;?>" data-izimodal-open="#info-video" data-bs-toggle="tooltip"
							  data-bs-placement="top" data-href="<?php echo $youtubeLink;?>" title="Video" data-title="<?php echo $brand_title.' '.$pattern;?>">
							  <span class="icon icon-sprite play"></span>
							</li>
						  <?php else:?>
							<li class="" title="Video">
							  <span class="icon icon-sprite play"></span>
							</li>
						  <?php endif;?>
						  <?php if($origin):?>
						   <?php $originTitle = 'Origin: '.$origin;?>
							 <li class="active" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo $originTitle;?>">
							  <span class="icon icon-sprite origin"></span>
							 </li>
						  <?php else:?>
							 <li class="" title="Origin">
								<span class="icon icon-sprite origin"></span>
							 </li>
						  <?php endif;?>
						  <?php if($fuel_efficiency):?>
							 <li class="active" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo $fuel_efficiency;?>">
							  <span class="icon icon-sprite fuel"></span>
							 </li>
						  <?php else:?>
							 <li class="" title="Fuel">
							  <span class="icon icon-sprite fuel"></span>
							 </li>
						  <?php endif;?>
						  <?php if($wet_grip):?>
							 <li class="active" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo $wet_grip;?>">
							  <span class="icon icon-sprite grip"></span>
							 </li>
						  <?php else:?>
							 <li class="" title="Grip">
							  <span class="icon icon-sprite grip"></span>
							 </li>
						  <?php endif;?>
						  <?php if($noise_levels):?>
							 <li class="active" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo $noise_levels;?>">
							  <span class="icon icon-sprite noice"></span>
							 </li>
						  <?php else:?>
							 <li class="" title="Noice">
							  <span class="icon icon-sprite noice"></span>
							 </li>
						  <?php endif;?>
						  </ul>
						</div>
					  </div>
				  <?php endif;?>
				  
				</div>
				<div class="col-md-2 col-lg-2 tabby-pay-later-list <?php echo $notaabbyinstallerclass; ?> <?php echo $tabby_method_class;?>" data-taggyproductid="<?php echo $_product->getId() ?>">
				  <a href="<?php echo $tabbyUrl;?>" target="_blank" class="">
					<div class="pay-installments d-flex align-items-center justify-content-center h-100">
					  <div class="image sprite tabby tabbyimage"></div>
					</div>
				   </a>
				</div>
				<div class="col-md-6 col-lg-6">
				<div class="row g-0 h-100">
				  <div class="col-md-8 col-lg-9">
					<div class="product-price d-flex flex-wrap h-100">
					  <div class="w-100 align-self-end price-box tyro_price_box">
						<?php if($autoPartsAttr):?>
							<div class="price w-100 sale set1price">
							  <sub class="aed"><?php echo __($currency) ?></sub>
							  <strong class="single-tyre-price"><?php echo $set1price; ?></strong>
							  <span><?php echo __($perItem);?></span>
							</div>
							<div class="installation-info"><?php echo __($auto_parts_inc1)." <br/> ".__($auto_parts_inc2); ?></div>
						<?php else:?>
							<div class="price w-100 sale set2price">
							  <sub class="aed"><?php echo __($currency) ?></sub>
							  <strong class="settwoprice">
								<?php if(!empty($isAnyRuleExist[7])): ?>
								  <?php echo number_format($isAnyRuleExist[7], 2); ?>
								<?php else: ?>
								  <?php echo $set2price; ?>
								<?php endif; ?>
							  </strong>
							  <span class="set2">
								<?php if(!empty($isAnyRuleExist[7])): ?>
								  <?php echo __('Set of 4');?>
								<?php else: ?>
								  <?php echo __('Set of 2');?>
								<?php endif; ?>
							  </span>
							</div>
							<div class="price w-100 set4price <?php echo $strikePriceClass; ?>">
							  <sub class="aed"><?php echo __($currency) ?></sub>
							  <strong class="setfourprice"><?php echo $set4price; ?></strong>
							  <span class="set4"><?php echo __('Set of 4');?></span>
							</div>
							<div class="price w-100 set1price">
							  <sub class="aed"><?php echo __($currency) ?></sub>
							  <strong class="single-tyre-price"><?php echo $set1price; ?></strong>
							  <span><?php echo __($perItem);?></span>
							</div>
						<?php endif;?>
					  </div>
					</div>
				  </div>
				<?php if($parts_category == 'Lubricants'): ?>
					<div class="col-md-4 col-lg-3 lubricants-product">
				<?php else: ?>
					<div class="col-md-4 col-lg-3">
				<?php endif; ?>
					<?php if($parts_category == 'Lubricants'): ?>
				  		<?php
				  		$cartHelper = $objectManager->get('Magento\Checkout\Helper\Cart');
						$addtocartUrl = $cartHelper->getAddUrl($_product);
				  		?>
				  		<form data-role="tocart-form" action="<?php echo $addtocartUrl; ?>" method="post" class="tyro_cart_box cart-qty-wrap flex-wrap h-100">
				  	<?php else: ?>
						<form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post" class="tyro_cart_box cart-qty-wrap flex-wrap h-100">
					<?php endif; ?>
					  <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
					  <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
					  <?php echo $block->getBlockHtml('formkey')?>
					  <div class="cart-qty-wrap d-flex flex-wrap h-100">
						<div class="qty-selection w-100 align-self-start">
						  <?php if ($_product->getIsSalable()):?>
						  		<?php if($parts_category == 'Lubricants'): ?>
								  	<?php //if($_product->getHasOptions()): ?>
								  		<?php $customOptions = $objectManager->get('Magento\Catalog\Model\Product\Option')->getProductOptionCollection($_product);
												$optionId = array();
												foreach ($customOptions->getData() as $o) {
													
													$optionId = $o['option_id'];
												}
										?>
										<select name="options[<?php echo $optionId;?>]" id="select_<?php echo $optionId;?>" class=" required product-custom-option admin__control-select select2-qty-search" title="" data-selector="options[<?php echo $optionId;?>]" aria-required="true">
											<?php foreach($customOptions as $optionKey => $optionVal){?>
												<?php foreach($optionVal->getValues() as $valuesKey => $valuesVal) {?>
													<option value="<?php echo $valuesVal->getId();?>" price="<?php echo $valuesVal->getPrice();?>"><?php echo $valuesVal->getTitle();?></option>
												<?php } ?>
											<?php } ?>
										</select>
								  	<?php //endif; ?>
								  <?php endif; ?>
							<?php if($parts_category != 'Lubricants'): ?>
							  <select name="qty" class="select2-qty w-100 select_qty" id="<?php echo $_product->getId()?>" data-unitprice="<?= $productpriceWC ?>" 
							   <?php echo  (count($AnyRuleExist) > 0 ) ? "data-discountqty=".$AnyRuleExist[5]   :  "";  ?> 
							   <?php echo  (count($AnyRuleExist) > 0 ) ? "data-totalqty=".$AnyRuleExist[6]:"";  ?> 
								data-istabby="<?php echo $tabbyMethodAvailable; ?>" 
								data-partscat="<?php echo $parts_category; ?>">
								<?php for ($cnt = 1; $cnt <= $stockQty; $cnt++) {?>
								<?php if(count($AnyRuleExist) > 0 && $AnyRuleExist[6] > 3){?>
								<option value=<?php echo $cnt;?> <?php if($cnt == 4): ?> selected <?php endif ?>><?php echo $cnt;?></option>
								<?php } else {?>
								<option value=<?php echo $cnt;?> <?php if($cnt == 1): ?> selected <?php endif ?>><?php echo $cnt;?></option>
							   <?php } ?>
							   <?php }?>
							  </select>
							<?php endif; ?>
							  <?php else:?>
							  <select name="qty" class="select2-qty w-100 select_qty" disabled style="opacity:0;"></select>
						  <?php endif;?>
						</div>
						<div class="add-to-cart w-100 align-self-end">
						<?php if ($_product->getIsSalable()):?>
						  <button type="submit" class="action tocart btn-cart button button-block button-primary-lightgrey filled-slide-up">
							<span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
								version="1.1" x="0px" y="0px" viewBox="1 -1 100 100"
								style="enable-background:new 1 -1 100 100;" xml:space="preserve">
								<g>
								  <path
									d="M39.4,69.5c-5.1,0-9.2,4.2-9.2,9.3c0,5.2,4.1,9.4,9.2,9.4s9.2-4.2,9.2-9.4C48.5,73.6,44.4,69.5,39.4,69.5z">
								  </path>
								  <path
									d="M76,69.5c-5.1,0-9.2,4.2-9.2,9.3c0,5.2,4.1,9.4,9.2,9.4s9.2-4.2,9.2-9.4C85.2,73.6,81.1,69.5,76,69.5z">
								  </path>
								  <path
									d="M39.2,55.1h43.2l10.9-34.8H29.9L26.6,9.8H8.7v6h13.5l11.6,36.5l-6.2,14.3h61.2v-6H36.8L39.2,55.1z">
								  </path>
								</g>
							  </svg></span>
						  </button>
						<?php else: ?>
						  <a href="tel:<?php echo $outOfStockPhone; ?>" class="button button-block button-primary-lightgrey filled-slide-up">
							<span>
							  <svg fill="#000000" xmlns="http://www.w3.org/2000/svg"
								xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" version="1.1"
								style="shape-rendering:geometricPrecision;text-rendering:geometricPrecision;image-rendering:optimizeQuality;"
								viewBox="0 0 333 333" x="0px" y="0px" fill-rule="evenodd" clip-rule="evenodd">
								<defs>
								  <style type="text/css">
									.fil0 {
									  fill: #000000;
									  fill-rule: nonzero
									}
								  </style>
								</defs>
								<g>
								  <path class="fil0"
									d="M167 0c92,0 166,75 166,167 0,92 -74,166 -166,166 -92,0 -167,-74 -167,-166 0,-92 75,-167 167,-167zm-29 136c11,-4 19,-14 9,-24l-14 -14c-11,-12 -23,4 -31,12 -8,8 -10,20 -6,31 18,44 53,78 97,97 10,4 22,1 30,-7 9,-8 24,-19 12,-31l-14 -14c-9,-10 -20,-2 -24,9l-2 6c-35,-11 -52,-27 -62,-63l5 -2z">
								  </path>
								</g>
							  </svg>
							</span>
						  </a>
						<?php endif; ?>
						  <?php if ($_product->getIsSalable()):?>
							<div class="stoke-status instoke">
							  <span><?php echo __('in stock');?></span>
							</div>
						  <?php else:?>
							<div class="stoke-status nostoke">
							  <span><?php echo __('No stock');?></span>
							</div>
						  <?php endif;?>
						</div>
					  </div>
					</form>
				  </div>
				</div>
				</div>
			  </div>
			</div>
		  </div>
		</div>
	  </li>
		<?php endforeach; ?>
	</ol>
	<!-- Start normal product list mobile view -->
	<div class="product-list list-view-mobile regular-product-list d-md-none">
	  <?php foreach ($_productCollection as $_product): ?>
		<?php
		  $brand = $_helper->productAttribute($_product, $_product->getMgsBrand(), 'mgs_brand');
		  $brandDetails = $listingHelper->getBrandDetails($brand);
		  $brand_title = $brandDetails->getName(); 
		  $brandImage = $listingHelper->getBrandImageUrl($brandDetails);
		  $displayName = $_product->getResource()->getAttribute("display_name")->getFrontend()->getValue($_product);
		  $tyreSize = '';
		  $tyreSize = $listingHelper->getTyreSize($_product, true);
		  $runflat = $_product->getResource()->getAttribute('runflat')->getFrontend()->getValue($_product);
		  $origin = $_product->getResource()->getAttribute('origin')->getFrontend()->getValue($_product);
		  $year = $_product->getResource()->getAttribute("year")->getFrontend()->getValue($_product);
		  $perItem=$_product->getResource()->getAttribute("per_item")->getFrontend()->getValue($_product);
		  $parts_category = $_product->getResource()->getAttribute("parts_category")->getFrontend()->getValue($_product);
		  $product_url  = $_product->getProductUrl();
		  $productImage = $_imagehelper->init($_product, $imageDisplayArea)->resize($image_width, $image_height)->getUrl();
		  $_productNameStripped = $block->stripTags($_product->getName(), null, true);
		  $set2price = $listingHelper->getSet2price($_product);
		  $set4price = $listingHelper->getSet4price($_product);
		  $set1price = $listingHelper->getSet1price($_product);

		  $tabbyMethodAvailable = $_product->getResource()->getAttribute("tabby_method")->getFrontend()->getValue($_product);
		  $tabby_method_class = '';
		  $notaabbyinstallerclass = '';
		  $set4PriceNumberOnly = str_replace(',', '', $set4price);
		  if($tabbyMethodAvailable == 'No' || $set4PriceNumberOnly <= $tabbyfourday || $set4PriceNumberOnly >= $tabbyinstallmentmaxvalue){
			$notaabbyinstallerclass = 'hidetabbyinstaller';
			$tabby_method_class = 'no-tabby';
		  }
		  $warranty_period = $_product->getResource()->getAttribute("warranty_period")->getFrontend()->getValue($_product);
		  $warranty_workmanship_mat=$_product->getResource()->getAttribute("warranty_workmanship_mat")->getFrontend()->getValue($_product);
		  $postParams = $listBlock->getAddToCartPostParams($_product);
		  $productpriceWC = $listingHelper->getSet1priceWithoutCurrency($_product);
		  $isAnyRuleExist = $AnyRuleExist = $listingHelper->isAnyRuleExist($_product);

		  $stockQty = 0;
		  $prod_qty =  $StockState->getStockQty($_product->getEntityId());
		  $isInStock = $StockRegistry->getProductStockStatus($_product->getEntityId());
		  if($prod_qty >= 8){
			$stockQty = 8;
		  }else{
			$stockQty = $prod_qty;
		  }
		  /*if(count($isAnyRuleExist) > 0){*/
		  if(isset($isAnyRuleExist[0]) && $isAnyRuleExist[0] != ''){	  
			$productBoxBorderColor = '#D70000';
		  } else {
			$productBoxBorderColor = '#000';
		  }

		  $borderColor="";    
		  $bkgColor="";
		  $strikePriceClass = ''; 
		  $offer_price = '';   
		  /*if(count($isAnyRuleExist) > 0 ){*/
		  if(isset($isAnyRuleExist[0]) && $isAnyRuleExist[0] != ''){
			$borderColor='border:2px solid '.$isAnyRuleExist[4];
			$bkgColor='background-color: '.$isAnyRuleExist[4];

			if ($isAnyRuleExist[6] > 3 && $isAnyRuleExist[5] > 0) {
			  $strikePriceClass = 'strike-price';
			}
		  }
		  $articleNumber = $_product->getResource()->getAttribute("article_number")->getFrontend()->getValue($_product);
		  $article_number_org = $_product->getResource()->getAttribute("article_number_org")->getFrontend()->getValue($_product);
		  $autoPartsAttr = 0;
		  $typeClass= '';
		  if($parts_category != 'Tyres'){
			  $tyreSize = $articleNumber;
			  $autoPartsAttr = 1;
			  $typeClass = 'autoparts-type';
		  }
		  $autoparts_1 = $_product->getResource()->getAttribute("auto_parts_warranty_1")->getFrontend()->getValue($_product);
		  $autoparts_2 = $_product->getResource()->getAttribute("auto_parts_warranty_2")->getFrontend()->getValue($_product);
		  $auto_parts_inc1 = $_product->getResource()->getAttribute("auto_parts_installation_1")->getFrontend()->getValue($_product);
		  $auto_parts_inc2 = $_product->getResource()->getAttribute("auto_parts_installation_2")->getFrontend()->getValue($_product);
		  $autoparts_contact = $_product->getResource()->getAttribute("auto_parts_contact_us")->getFrontend()->getValue($_product);
		?>
		
		  <div class="product-box <?php echo $typeClass;?>" style="--border-color: <?php echo $productBoxBorderColor; ?>">
			<?php if(isset($isAnyRuleExist[0]) && $isAnyRuleExist[0] != ''):?>
			  <div class="offer-image">
				<img src="<?php echo $isAnyRuleExist[0] ?>" data-src="<?php echo $isAnyRuleExist[0] ?>" class=" lazyloaded" alt="Offer">
			  </div>
			<?php endif; ?>
			<div class="inner-wrap tyres-productset4">
			  <div class="row">
				<div class="col-6">
				  <div class="left">
					<div class="product-brand">
					  <img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" data-src="<?php echo $brandImage ?>" class="lazyload" alt="<?php echo $brand_title ?>" />
					</div>
					<div class="product-info d-flex flex-wrap h-100">
					  <div class="name">
						<h4 class="fw-bold mb-0"><a href="<?php echo $product_url;?>"><?php echo __($displayName); ?></a></h4>
						<span class="fw-bold"><?php echo __($tyreSize); ?></span>
					  </div>
					  <div class="additional">
						<?php if($runflat):?>
						  <!-- If run flat selected by filter -->
						  <div class="run-flat">
							<span class="icon icon-sprite"></span>
						  </div>
						<?php endif; ?>
						<?php if($autoPartsAttr && $article_number_org != ''):?>
							<div class="autoparts-additional-info">
							  <div class="info"><span class="icon bg-red-400 icon-sprite toi-info autoparts-modal-ajax" data-name="<?php echo $_productNameStripped ?>" data-partnumber="<?php echo $articleNumber ?>"></span></div>
							  <span class="installation-info"><?php echo $auto_parts_inc1;?></span>
							  <span class="installation-info"><?php echo $auto_parts_inc2;?></span>
							</div>
						<?php else:?>
							<div class="mf-year-country">
							  <?php if($origin):?>
								<span><?php echo __($origin); ?></span>
							  <?php endif; ?>
							  <?php if($year): ?>
								<span><?php echo $year; ?></span>
							  <?php endif; ?>
							</div>
						<?php endif;?>
					  </div>
					</div>
				  </div>
				</div>
				<div class="col-6">
				  <div class="right h-100 d-flex align-items-end position-relative">
					<div class="product-image">
					  <a href="<?php echo $product_url;?>" class="d-block link">
						<img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" data-src="<?php echo $productImage ?>" class="lazyload" alt="<?php echo $_productNameStripped ?>" />
					  </a>
					</div>
					<!-- if no installments remove this div-->
					<div class="pay-installments tabby-pay-later-list <?php echo $notaabbyinstallerclass; ?> <?php echo $tabby_method_class;?>">
					  <a href="<?php echo $tabbyUrl;?>" class="link d-block">
						<div class="image sprite tabby"></div>
					  </a>
					</div>
				  </div>
				</div>
			  </div>
			  <div class="bottom">
				<?php if($autoPartsAttr):?>
					<div class="warranty-style2">
					  <span data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __($autoparts_1); ?>"><?php echo __($autoparts_1); ?></span>
					  <span data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __($autoparts_2); ?>"><?php echo __($autoparts_2); ?></span>
					</div>
			  <?php else:?>
				<?php if($warranty_period):?>
				  <div class="warranty text-end">
					<span><?php echo __($warranty_period); ?></span>
				  </div>
				<?php endif; ?>
			  <?php endif;?>
				<!-- If contact for autoPartsAttr -->
				<?php if($autoparts_contact):?>
				<div class="contact-for-vehicle">
					<span data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __($autoparts_contact);?>"><?php echo __($autoparts_contact);?></span>
				</div>
				<?php endif;?>
				<div class="row g-0">
				  <div class="col-7">
					<div class="product-price d-flex flex-wrap h-100">
					  <div class="w-100 align-self-end">
						<?php if($autoPartsAttr):?>
							<div class="price w-100 sale set1price">
							  <sub class="aed"><?php echo __($currency) ?></sub>
							  <strong class="single-tyre-price"><?php echo $set1price; ?></strong>
							  <span><?php echo __($perItem);?></span>
							</div>
						<?php else:?>
							<div class="price w-100 sale set2price">
							  <sub class="aed"><?php echo __($currency) ?></sub>
							  <strong class="settwoprice">
								<?php if(!empty($isAnyRuleExist[7])): ?>
								  <?php echo number_format($isAnyRuleExist[7], 2); ?>
								<?php else: ?>
								  <?php echo $set2price; ?>
								<?php endif; ?>
							  </strong>
							  <span class="set2">
								<?php if(!empty($isAnyRuleExist[7])): ?>
								  <?php echo __('Set of 4');?>
								<?php else: ?>
								  <?php echo __('Set of 2');?>
								<?php endif; ?>
							  </span>
							</div>
							<div class="price w-100 set4price <?php echo $strikePriceClass; ?>">
							  <sub class="aed"><?php echo __($currency) ?></sub>
							  <strong class="setfourprice"><?php echo $set4price; ?></strong>
							  <span class="set4"><?php echo __('Set of 4');?></span>
							</div>
							<div class="price w-100 set1price">
							  <sub class="aed"><?php echo __($currency) ?></sub>
							  <strong class="single-tyre-price"><?php echo $set1price; ?></strong>
							  <span><?php echo __($perItem);?></span>
							</div>
						<?php endif;?>
					  </div>
					</div>
				  </div>
				  <div class="col-5">
					<div class="cart-qty-wrap">
					<?php if($warranty_workmanship_mat): ?>
						<div class="offer text-end">
						  <span><?php echo __($warranty_workmanship_mat); ?></span>
						</div>
					<?php endif; ?>
					  <?php if ($_product->getIsSalable()):?>
						<form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post" class="">
						  <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
						  <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
						  <?php echo $block->getBlockHtml('formkey')?>
						  <div class="d-flex mt-2">
							<div class="qty-selection position-relative">
							  <select name="qty" class="select2-qty w-100 select_qty" data-unitprice="<?= $productpriceWC ?>"
								<?php echo  (count($AnyRuleExist) > 0 ) ? "data-discountqty=".$AnyRuleExist[5]   :  "";  ?> 
							   <?php echo  (count($AnyRuleExist) > 0 ) ? "data-totalqty=".$AnyRuleExist[6]:"";  ?> 
							   data-istabby="<?php echo $tabbyMethodAvailable; ?>" 
							   data-partscat="<?php echo $parts_category; ?>"
							  >
								<?php for ($cnt = 1; $cnt <= $stockQty; $cnt++) {?>
								  <?php if(count($AnyRuleExist) > 0 && $AnyRuleExist[6] > 3){?>
									<option value=<?php echo $cnt;?> <?php if($cnt == 4): ?> selected <?php endif ?>><?php echo $cnt;?></option>
								  <?php } else {?>
									<option value=<?php echo $cnt;?> <?php if($cnt == 1): ?> selected <?php endif ?>><?php echo $cnt;?></option>
								  <?php } ?>
								<?php }?>
							  </select>
							  <span class="icon icon-sprite arrow"></span>
							</div>
							<div class="add-to-cart">
							  <button class="tocart" type="submit"><?php echo __('Buy Now'); ?></button>
							</div>
						  </div>
						</form>
					  <?php else: ?>
						<!-- if product outstoke -->
						<div class="d-flex mt-2">
						  <div class="call-us text-end w-100">
							<a href="tel:<?php echo $outOfStockPhone; ?>"><span><?php echo __('Call Us'); ?></span></a>
						  </div>
						</div>
						<!-- if product outstoke end-->
					  <?php endif; ?>
					</div>
				  </div>
				</div>
			  </div>
			</div>
		  </div>
	  <?php endforeach; ?>
	</div>
	<!-- End normal product list mobile view -->
</div>
<?php endif;?>
<script type="text/javascript">
require(["jquery", "select2"], function($) {
$(document).ready(function() {
  $('.select2-qty').select2({
    dropdownCssClass: "dropdown-style2 text-center",
    minimumResultsForSearch: -1
  });
  $('.select2-qty-search').select2({
    dropdownCssClass: "dropdown-style3 text-center",
  });
});
});

require([
    'jquery',
    'bootstrap'
    ], function ($, bootstrap) {
var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
  return new bootstrap.Tooltip(tooltipTriggerEl)
});
});
</script>