<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('product_page_settings/show_related_products_by_brand')): ?>
        <?php if ($brand = $block->getBrand()): ?>
            <?php
            $_productCollection = $block->getProductCollection();
            $_helper = $this->helper('Magento\Catalog\Helper\Output');
            ?>
			<?php 
			$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
			$image = 'category_page_grid';
			$themeSettings = $themeHelper->getThemeSettings();
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			?>
            <?php if (count($_productCollection)): ?>
                <div class="brand-related-products margin-top70">
					<div class="content-heading text-left">
						<h2 class="title"><span id="block-heading" role="heading" aria-level="2"><?php echo $block->getConfig('product_page_settings/title_related_products'); ?></span></h2>
					</div>
					
                    <div class="block-content content" aria-labelledby="block-heading">
                        <div class="products wrapper grid products-grid products-related row">
                            <div id="brand-related-products" class="products list items product-items owl-carousel">
                                <?php $iterator = 1; ?>
                                <?php foreach ($_productCollection as $_product): ?>
                                    <div class="item product product-item">
										<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
										<div class="product-item-info" data-container="product-grid">
											<?php
												$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
												$size = $themeHelper->getImageSize($this->getRatio());
												$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
											?>
											<div class="product-top">
												<?php // Product Image ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
													<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
													<?php echo $themeHelper->getProductLabel($_product) ?>
												</a>
												<ul class="actions-link">
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
														<li>
															<button class="action towishlist"
															   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
															   data-title="<?php echo __('Add to Wish List') ?>"
															   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
															   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
															   data-action="add-to-wishlist"
															   role="button">
																<i class="fa fa-heart"></i>
															</button>
														</li>
													<?php endif; ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
													<?php if(!$themeSettings['catalog']['compare_button']): ?>
														<li>
															<button class="action tocompare"
															   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
															   data-title="<?php echo __('Add to Compare') ?>"
															   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
															   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
															   role="button">
																<i class="fa fa-random"></i>
															</button>
														</li>
													<?php endif ?>
													<li class="hidden-sm hidden-xs">
														<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
														<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
													</li>
												</ul>
											</div>
											<div class="product details product-item-details">
												<h5 class="product name product-item-name">
													<a class="product-item-link"
													   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
														<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
													</a>
												</h5>
												<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
												<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
												<?php echo $block->getProductDetailsHtml($_product); ?>
												<?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>

												<div class="product-item-inner">
													<div class="product actions product-item-actions">
														<div class="actions-primary">
															<?php if ($_product->isSaleable()): ?>
																<?php $postParams = $block->getAddToCartPostParams($_product); ?>
																<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
																	<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
																	<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
																	<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
																	<button class="action tocart btn-cart btn btn-primary" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																		<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																	</button>
																	
																</form>
															<?php else: ?>
																<?php if ($_product->getIsSalable()): ?>
																	<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
																<?php else: ?>
																	<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
																<?php endif; ?>
															<?php endif; ?>
														</div>
													</div>
												</div>
											</div>
										</div>
                                    </div>
                                <?php endforeach ?>
                            </div>
							<?php $perRow = $block->getConfig('product_page_settings/perrow_related_products'); ?>
							<script type="text/javascript">
								require([
									'jquery',
									'mgs/owlcarousel'
								], function ($) {
									var brandrelatedproducts = $('#brand-related-products').owlCarousel({
										items: <?php echo $perRow; ?>,
										autoplay: false,
										autoplayHoverPause: false,
										nav: true,
										dots: false,
										navText: ["<i class='fa fa-arrow-left'></i>","<i class='fa fa-arrow-right'></i>"],
										responsive:{
											0:{
												items:1
											},
											480:{
												items:2
											},
											768:{
												items:<?php echo $perRow; ?>
											}
										}
									});
								});
							</script>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
