<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_order = $block->getOrder();
?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
          <thead class="thead-dark" style="background-color:#D80000;border-bottom-color:#D80000;color:white;">
            <tr>
              <th scope="col" colspan="3" style="font-weight: 500;text-align:left;font-size: 12px;padding:3px 9px;">ITEM</th>
              <th scope="col" style="text-align:center;font-weight: 500;font-size: 12px;padding:3px 9px;">QTY</th>
            </tr>
          </thead>
         <tbody>
        <?php foreach ($_items as $_item): 
                $product = $objectManager->create('Magento\Catalog\Model\Product')->loadByAttribute('sku',$_item->getSku());
                $isaccesory=false;
        ?>
            <?php
                if ($_item->getParentItem()) {
                    continue;
                }
            ?>
                <tr>
                    <td colspan="3"><span style="padding-top:5px;font-weight:500;"><br/><b>
                        <?php if($isaccesory){ ?>
                            <span style="font-size:14px;"><?php echo  $product->getResource()->getAttribute("name")->getFrontend()->getValue($product); ; ?></span>
                        <?php }else{ ?>
                        <?php echo $_item->getName(); ?></b></span><br/>
                        <?php } ?>
                        
                    </span></td>
                    <td style="text-align:center;font-size:14px;"><b><?=  $_item->getQtyOrdered() * 1 ?></b></td>
                 </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>