<?php
/**
 * Rename promotions CMS page URL from UAE slug to KSA slug + 301 redirects.
 * Run: cd /var/www/magento && sudo -u www-data php infra/scripts/apply-promotions-url-ksa.php
 */
use Magento\Framework\App\Bootstrap;

require __DIR__ . '/../../app/bootstrap.php';
$bootstrap = Bootstrap::create(BP, $_SERVER);
$om = $bootstrap->getObjectManager();
try {
    $om->get(\Magento\Framework\App\State::class)->setAreaCode('adminhtml');
} catch (\Exception $e) {
}

$conn = $om->get(\Magento\Framework\App\ResourceConnection::class)->getConnection();

$oldSlug = 'promotions-and-offers-on-tyres-uae';
$newSlug = 'promotions-and-offers-on-tyres-ksa';
$storeIds = [0, 1, 2];

$pageId = (int)$conn->fetchOne(
    'SELECT page_id FROM cms_page WHERE identifier = ? ORDER BY page_id DESC LIMIT 1',
    [$oldSlug]
);
if (!$pageId) {
    $pageId = (int)$conn->fetchOne(
        'SELECT page_id FROM cms_page WHERE identifier = ? ORDER BY page_id DESC LIMIT 1',
        [$newSlug]
    );
    if ($pageId) {
        echo "CMS page already uses identifier {$newSlug} (page_id={$pageId})\n";
    } else {
        throw new RuntimeException("Promotions CMS page not found for {$oldSlug} or {$newSlug}");
    }
} else {
    $conn->update('cms_page', ['identifier' => $newSlug], ['page_id = ?' => $pageId]);
    echo "Updated cms_page page_id={$pageId} identifier: {$oldSlug} -> {$newSlug}\n";
}

$metaUpdates = [
    'meta_title' => [
        'Tyre Offers & Promotions in Dubai, UAE | TyresOnline.ae' => 'Tyre Offers & Promotions in Saudi Arabia | TyresOnline.sa',
        'Tyre Offers & Promotions in UAE | TyresOnline.ae' => 'Tyre Offers & Promotions in Saudi Arabia | TyresOnline.sa',
        'عروض وترويجات الكفرات في دبي، الإمارات | TyresOnline.ae' => 'عروض وترويجات الكفرات في السعودية | TyresOnline.sa',
    ],
    'meta_description' => [
        'Dubai' => 'Riyadh',
        'UAE' => 'Saudi Arabia',
        'TyresOnline.ae' => 'TyresOnline.sa',
        'الإمارات' => 'السعودية',
        'دبي' => 'الرياض',
    ],
];

foreach ($metaUpdates as $col => $replacements) {
    $cols = $conn->describeTable('cms_page');
    if (!isset($cols[$col])) {
        continue;
    }
    $val = (string)$conn->fetchOne("SELECT {$col} FROM cms_page WHERE page_id = ?", [$pageId]);
    if ($val === '') {
        continue;
    }
    $new = $val;
    foreach ($replacements as $from => $to) {
        $new = str_replace($from, $to, $new);
    }
    if ($new !== $val) {
        $conn->update('cms_page', [$col => $new], ['page_id = ?' => $pageId]);
        echo "Updated cms_page {$col} page_id={$pageId}\n";
    }
}

$deleted = $conn->delete(
    'url_rewrite',
    [
        'entity_type = ?' => 'cms-page',
        'entity_id = ?' => $pageId,
    ]
);
echo "Removed {$deleted} existing cms-page url_rewrite row(s) for page_id={$pageId}\n";

foreach ($storeIds as $storeId) {
    $exists = (int)$conn->fetchOne(
        'SELECT COUNT(*) FROM url_rewrite WHERE entity_type = ? AND entity_id = ? AND store_id = ? AND request_path = ? AND redirect_type = 0',
        ['cms-page', $pageId, $storeId, $newSlug]
    );
    if (!$exists) {
        $conn->insert('url_rewrite', [
            'entity_type' => 'cms-page',
            'entity_id' => $pageId,
            'request_path' => $newSlug,
            'target_path' => 'cms/page/view/page_id/' . $pageId,
            'redirect_type' => 0,
            'store_id' => $storeId,
            'description' => null,
            'is_autogenerated' => 1,
            'metadata' => null,
        ]);
        echo "Inserted url_rewrite for store {$storeId}: {$newSlug}\n";
    }

    foreach ([$oldSlug, $oldSlug . '/'] as $oldPath) {
        $redirectExists = (int)$conn->fetchOne(
            'SELECT COUNT(*) FROM url_rewrite WHERE store_id = ? AND request_path = ?',
            [$storeId, rtrim($oldPath, '/')]
        );
        if ($redirectExists) {
            $conn->update(
                'url_rewrite',
                [
                    'target_path' => $newSlug,
                    'redirect_type' => 301,
                    'entity_type' => 'custom',
                    'entity_id' => 0,
                    'is_autogenerated' => 0,
                ],
                ['store_id = ?' => $storeId, 'request_path = ?' => rtrim($oldPath, '/')]
            );
            echo "Updated 301 redirect store {$storeId}: {$oldPath} -> {$newSlug}\n";
        } else {
            $conn->insert('url_rewrite', [
                'entity_type' => 'custom',
                'entity_id' => 0,
                'request_path' => rtrim($oldPath, '/'),
                'target_path' => $newSlug,
                'redirect_type' => 301,
                'store_id' => $storeId,
                'description' => 'KSA promotions URL migration',
                'is_autogenerated' => 0,
                'metadata' => null,
            ]);
            echo "Inserted 301 redirect store {$storeId}: {$oldPath} -> {$newSlug}\n";
        }
    }
}

$contentTables = [
    ['cms_page', 'page_id', $pageId, ['content', 'title']],
    ['cms_block', 'block_id', null, ['content']],
];

$slugReplacements = [
    'promotions-and-offers-on-tyres-uae' => 'promotions-and-offers-on-tyres-ksa',
    '/promotions-and-offers-on-tyres-uae' => '/promotions-and-offers-on-tyres-ksa',
];

foreach ($contentTables as [$table, $idCol, $idVal, $columns]) {
    $cols = $conn->describeTable($table);
    if ($idVal !== null) {
        $rows = [$conn->fetchRow("SELECT * FROM {$table} WHERE {$idCol} = ?", [$idVal])];
    } else {
        $rows = $conn->fetchAll(
            "SELECT * FROM {$table} WHERE " . implode(' OR ', array_map(
                fn ($c) => "{$c} LIKE ?",
                array_intersect($columns, array_keys($cols))
            )),
            array_fill(0, count($columns), '%promotions-and-offers-on-tyres-uae%')
        );
    }
    foreach ($rows as $row) {
        if (!$row) {
            continue;
        }
        foreach ($columns as $column) {
            if (!isset($cols[$column], $row[$column]) || $row[$column] === null) {
                continue;
            }
            $new = str_replace(array_keys($slugReplacements), array_values($slugReplacements), (string)$row[$column]);
            if ($new !== $row[$column]) {
                $conn->update($table, [$column => $new], [$idCol . ' = ?' => $row[$idCol]]);
                echo "Updated {$table}.{$column} {$idCol}={$row[$idCol]}\n";
            }
        }
    }
}

echo "Done. New URL slug: {$newSlug}\n";
