#!/bin/bash
set -e
DB=tyresonline_sa
HOST=tyresonline-sa-prod.cbybbkyzwyxj.eu-north-1.rds.amazonaws.com
USER=magento
PASS=uxaYMIQRwEU0AFl1Ck69LJnH
MYSQL=(mysql -h "$HOST" -u "$USER" -p"$PASS" "$DB")

URL_KEY_ATTR=$("${MYSQL[@]}" -N -e "SELECT attribute_id FROM eav_attribute WHERE attribute_code='url_key' AND entity_type_id=3 LIMIT 1")

echo "=== Fix parent category url_key: tyres -> all-tyres ==="
"${MYSQL[@]}" -e "
UPDATE catalog_category_entity_varchar
SET value = 'all-tyres'
WHERE entity_id = 1944 AND attribute_id = $URL_KEY_ATTR AND store_id = 0;
"

echo "=== Remove stale custom rewrites pointing to deleted categories ==="
"${MYSQL[@]}" -e "
DELETE FROM url_rewrite
WHERE entity_type = 'custom'
AND target_path LIKE 'catalog/category/view/id/%'
AND CAST(SUBSTRING_INDEX(target_path, '/', -1) AS UNSIGNED) NOT IN (
  SELECT entity_id FROM catalog_category_entity
);
"

echo "=== Remove old tyres/* autogenerated rewrites (will be regenerated) ==="
"${MYSQL[@]}" -e "
DELETE FROM url_rewrite
WHERE request_path LIKE 'tyres/%' OR request_path = 'tyres.html';
"

echo "=== Regenerate category URL rewrites (store 1 + 2) ==="
sudo -u www-data php /var/www/magento/bin/magento ok:urlrewrites:regenerate --entity-type=category --store-id=1 -n
sudo -u www-data php /var/www/magento/bin/magento ok:urlrewrites:regenerate --entity-type=category --store-id=2 -n

echo "=== Regenerate product URL rewrites (store 1 + 2) ==="
sudo -u www-data php /var/www/magento/bin/magento ok:urlrewrites:regenerate --entity-type=product --store-id=1 -n
sudo -u www-data php /var/www/magento/bin/magento ok:urlrewrites:regenerate --entity-type=product --store-id=2 -n

echo "=== Verify ==="
"${MYSQL[@]}" -e "
SELECT url_rewrite_id, entity_type, entity_id, request_path, target_path, store_id
FROM url_rewrite
WHERE request_path IN ('all-tyres.html', 'all-tyres/car-tyres.html')
ORDER BY store_id, request_path;
"

sudo -u www-data php /var/www/magento/bin/magento cache:flush 2>&1 | tail -2
echo Done.
