<?php
/**
 * Fix EN promotions page 404: point store 1 url_rewrite to English CMS page (11).
 * Run: cd /var/www/magento && sudo -u www-data php infra/scripts/fix-promotions-en-url-ksa.php
 */
use Magento\Framework\App\Bootstrap;

require __DIR__ . '/../../app/bootstrap.php';
$bootstrap = Bootstrap::create(BP, $_SERVER);
$om = $bootstrap->getObjectManager();
try {
    $om->get(\Magento\Framework\App\State::class)->setAreaCode('adminhtml');
} catch (\Exception $e) {
}

$conn = $om->get(\Magento\Framework\App\ResourceConnection::class)->getConnection();
$slug = 'promotions-and-offers-on-tyres-ksa';
$enPageId = 11;
$arPageId = 37;

$enPage = $conn->fetchRow('SELECT page_id, identifier, title, is_active FROM cms_page WHERE page_id = ?', [$enPageId]);
if (!$enPage) {
    throw new RuntimeException("English promotions CMS page {$enPageId} not found");
}

foreach ([1 => $enPageId, 2 => $arPageId] as $storeId => $pageId) {
    $exists = (int)$conn->fetchOne(
        'SELECT COUNT(*) FROM cms_page_store WHERE page_id = ? AND store_id = ?',
        [$pageId, $storeId]
    );
    if (!$exists) {
        $conn->insert('cms_page_store', ['page_id' => $pageId, 'store_id' => $storeId]);
        echo "Linked cms_page_store page_id={$pageId} store_id={$storeId}\n";
    }

    $updated = $conn->update(
        'url_rewrite',
        [
            'target_path' => 'cms/page/view/page_id/' . $pageId,
            'entity_id' => $pageId,
            'entity_type' => 'cms-page',
        ],
        [
            'store_id = ?' => $storeId,
            'request_path = ?' => $slug,
            'redirect_type = ?' => 0,
        ]
    );
    if (!$updated) {
        $conn->insert('url_rewrite', [
            'entity_type' => 'cms-page',
            'entity_id' => $pageId,
            'request_path' => $slug,
            'target_path' => 'cms/page/view/page_id/' . $pageId,
            'redirect_type' => 0,
            'store_id' => $storeId,
            'description' => null,
            'is_autogenerated' => 1,
            'metadata' => null,
        ]);
        echo "Inserted url_rewrite store {$storeId} -> page_id={$pageId}\n";
    } else {
        echo "Updated url_rewrite store {$storeId} -> page_id={$pageId}\n";
    }
}

echo "Done. EN should use page {$enPageId}, AR uses page {$arPageId}, slug {$slug}\n";
