<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
     <table border="0" cellpadding="0" cellspacing="0" width="100%">
          <thead class="thead-dark" style="background-color:#D80000;border-bottom-color:#D80000;color:white;">
            <tr>
              <th scope="col" colspan="3" style="font-weight: 500;font-size: 12px;padding:3px 9px;"><?php echo __('السلعة'); ?></th>
              <th scope="col" style="text-align:center;font-weight: 500;font-size: 12px;padding:3px 9px;"><?php echo __('السعر'); ?></th>
              <th scope="col" style="text-align:center;font-weight: 500;font-size: 12px;padding:3px 9px;"><?php echo __('الكمية'); ?></th>
              <th scope="col" style="text-align:center;font-weight: 500;font-size: 12px;padding:3px 9px;"><?php echo __('إجمالي قيمة السلع'); ?></th>
            </tr>
          </thead>
        <?php foreach ($_items as $_item): 
        ?>
            <?php
                if ($_item->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
   
<?php endif; ?>
