<?php
/**
 * Amp animations config initialization
 */
?>

<amp-animation id="slide-top-animation" layout="nodisplay">
    <script type="application/json">
        {
            "selector": ".slide-top-animation",
            "duration": ".8s",
            "keyframes": "slideTop"
        }
    </script>
</amp-animation>

<amp-animation id="slide-bottom-animation" layout="nodisplay">
    <script type="application/json">
        {
            "selector": ".slide-bottom-animation",
            "duration": ".8s",
            "keyframes": "slideBottom"
        }
    </script>
</amp-animation>
