<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->loadByAttribute('sku',$block->getSku($_item));
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
$_imageHelper = $objectManager->create('Magento\Catalog\Helper\Image');
$product_cats = $product->getCategoryIds();
$customCatId = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('productsearch/general/category_custom_id');

$isaccesory=false;

if(in_array($customCatId, $product_cats)){
  $isaccesory=true;
}

?>
<tr>
   <td colspan="3"><span style="padding-top:5px;font-weight:500;"><br/>
        <?php if($isaccesory){ ?>

         <span style="font-size:14px;"><?php echo  $product->getResource()->getAttribute("name")->getFrontend()->getValue($product); ; ?></span>
       
        <?php }else{ ?>

         <?php //echo $block->escapeHtml($product->getAttributeText('brand').' - '.$_item->getName())  
           echo  $product->getResource()->getAttribute("name")->getFrontend()->getValue($product); ; 
         ?></span><br/>                         
         <?php echo "SKU: ". $_item->getSku() ?> 
       
        <?php } ?>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                <dd>
                    <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td  style="text-align:center;font-size:14px;"><?= /* @escapeNotVerified */  $priceHelper->currency($_item->getPrice(), true, false); ?></td>
    <td  style="text-align:center;font-size:14px;"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td  style="text-align:center;font-size:14px;">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item); ?>
    </td> 
</tr>


