<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Sales\Block\Adminhtml\Order\View\History $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div id="order_history_block" class="edit-order-comments">
    <?php if ($block->canAddComment()): ?>
        <div class="order-history-block" id="history_form">

            <div class="admin__field">
                <label for="history_status" class="admin__field-label"><?= $block->escapeHtml(__('Status')) ?></label>
                <div class="admin__field-control">
                    <select name="history[status]" id="history_status" class="admin__control-select">
                        <?php foreach ($block->getStatuses() as $_code => $_label): ?>
                            <option value="<?= $block->escapeHtmlAttr($_code) ?>"
                                <?php if ($_code == $block->getOrder()->getStatus()): ?> selected="selected"
                                <?php endif; ?>>
                                <?= $block->escapeHtml($_label) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="admin__field">
                <label for="history_comment" class="admin__field-label">
                    <?= $block->escapeHtml(__('Comment')) ?>
                </label>
                <div class="admin__field-control">
                    <textarea name="history[comment]"
                              rows="3"
                              cols="5"
                              id="history_comment"
                              data-wysiwyg-initialize="1"
                              class="admin__control-textarea"></textarea>
                </div>
            </div>

            <div class="admin__field">
                <div class="order-history-comments-options">
                    <div class="admin__field admin__field-option">
                        <?php if ($block->canSendCommentEmail()): ?>
                            <input name="history[is_customer_notified]"
                                   type="checkbox"
                                   id="history_notify"
                                   class="admin__control-checkbox"
                                   value="1" />
                            <label class="admin__field-label" for="history_notify">
                                <?= $block->escapeHtml(__('Notify Customer by Email')) ?>
                            </label>
                        <?php endif; ?>
                    </div>

                    <div class="admin__field admin__field-option">
                        <input name="history[is_visible_on_front]"
                               type="checkbox"
                               id="history_visible"
                               class="admin__control-checkbox"
                               value="1" />
                        <label class="admin__field-label" for="history_visible">
                            <?= $block->escapeHtml(__('Visible on Storefront')) ?>
                        </label>
                    </div>
                </div>

                <div class="order-history-comments-actions">
                    <?= $block->getChildHtml('submit_button') ?>
                </div>
            </div>
        </div>
    <?php endif;?>

    <ul class="note-list" id="mw-oe-notes">
        <?php
        /**
         * @var \Magento\Sales\Model\Order\Status\History $_item
         */
        ?>
        <?php foreach ($block->getOrder()->getStatusHistoryCollection(true) as $_item): ?>
            <li class="note-list-item">
                <div class="edit-comment-wrapper">
                    <div class="actions block-edit-link"><a href="#">Edit</a></div>
                    <div class="mw-oe-note-edit-content" style="display: none;">
                        <textarea name="comments[<?= $block->escapeHtmlAttr($_item->getId())?>][text]"
                                  class="mw-oe-note-edit-new-text"
                                  data-wysiwyg-initialize="1"
                                  data-comment-id="<?= $block->escapeHtmlAttr($_item->getId())?>"
                                  data-order-id="<?= $block->escapeHtmlAttr($block->getOrder()->getId())?>"
                                  id="mw-oe-edit-comment-<?= $block->escapeHtmlAttr($_item->getId())?>">
                            <?php if ($_item->getComment()): ?>
                                <?= $block->escapeHtml($_item->getComment(), ["a", "b", "strong", "h1", "h2", "h3", "h4", "h5", "br", "em", "hr", "i", "li", "ol", "p", "s", "span", "table", "tbody", "tr", "td", "u", "ul"]) ?>
                            <?php endif; ?>
                        </textarea>
                        <div class="order-history-comments-actions">
                            <button id="<?= 'submit-edit-comment-' . $block->escapeHtmlAttr($_item->getId())?>"
                                    data-comment-id="<?= $block->escapeHtmlAttr($_item->getId())?>"
                                    class="mw-oe-notes-edit-submit action-default scalable action-save action-secondary">
                                <?= $block->escapeHtml(__('Submit'))?>
                            </button>
                        </div>
                    </div>
                </div>
                <span class="note-list-date">
                    <?= /* @noEscape */ $block->formatDate($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                </span>
                <span class="note-list-time">
                    <?= /* @noEscape */ $block->formatTime($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                </span>
                <span class="note-list-status"><?= $block->escapeHtml($_item->getStatusLabel()) ?></span>
                <span class="note-list-customer">
                    <?= $block->escapeHtml(__('Customer')) ?>
                    <?php if ($block->isCustomerNotificationNotApplicable($_item)): ?>
                        <span class="note-list-customer-notapplicable">
                        <?= $block->escapeHtml(__('Notification Not Applicable')) ?>
                    </span>
                    <?php elseif ($_item->getIsCustomerNotified()): ?>
                        <span class="note-list-customer-notified"><?= $block->escapeHtml(__('Notified')) ?></span>
                    <?php else: ?>
                        <span class="note-list-customer-not-notified"><?= $block->escapeHtml(__('Not Notified')) ?></span>
                    <?php endif; ?>
                </span>
                <?php if ($_item->getComment()): ?>
                    <div class="note-list-comment">
                        <?= $block->escapeHtml($_item->getComment(), ["a", "b", "strong", "h1", "h2", "h3", "h4", "h5", "br", "em", "hr", "i", "li", "ol", "p", "s", "span", "table", "tbody", "tr", "td", "u", "ul"]) ?>
                    </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php $scriptString = <<<script
        require(['prototype'], function(){
            if($('order_status'))$('order_status').update('{$block->escapeJs($block->getOrder()->getStatusLabel())}');
        });
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function ($) {
            function saveComment(DOMElement) {
                let data = {
                    'form_key': FORM_KEY,
                    'order_id': DOMElement.dataset['orderId'],
                    'comment_id': DOMElement.dataset['commentId'],
                    'comment_text': DOMElement.value
                };
                $.ajax({
                    url: "<?= $block->getUrl('ordereditor/edit/updateComment')?>",
                    data: data,
                    type: 'post',
                    dataType: 'json',
                    success: function (response) {
                        tinyMCE.activeEditor.isNotDirty = true;
                    },
                    error: function (error) {
                        console.log(['ERROR!', error]);
                    }
                });
            }

            $('#mw-oe-notes .note-list-item').each(function (index, elems) {
                let $note = $(this),
                    $editWrapper = $note.find('.edit-comment-wrapper'),
                    $editContent = $editWrapper.find('.mw-oe-note-edit-content'),
                    $editButton = $editWrapper.find('.block-edit-link'),
                    $submitButton = $editContent.find('.mw-oe-notes-edit-submit'),
                    $textarea = $editContent.find('.mw-oe-note-edit-new-text'),
                    $oldComment = $note.find('.note-list-comment');

                $textarea.on('change', function (event) {
                    $oldComment.html($(event.target).val());
                });

                $editButton.on('click', function (event) {
                    event.preventDefault();
                    $editContent.toggle();
                    $editButton.toggle();
                });

                $submitButton.on('click', function (event) {
                    event.preventDefault();
                    let commentId = event.target.dataset['commentId'],
                        commentTextarea = document.getElementById('mw-oe-edit-comment-' + commentId);

                    if (commentTextarea !== null) {
                        saveComment(commentTextarea);
                    }
                    $editButton.toggle();
                    $editContent.toggle();
                });
            });
        });
    </script>
</div>
