<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$wheelProtectorProductsIds = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('hdweb/general/wheel_protector_product_ids');
$wheelProtectorProductsIds = explode(',', trim($wheelProtectorProductsIds));
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$listingHelper = $this->helper('Hdweb\Tyrefinder\Helper\Productlisting');
$image_width = 300;
$image_height = 300;
$tabbyinstallmentmaxvalue = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('productsearch/general/tabbyinstallment');
$tabbyfourday = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('productsearch/general/tabbyfourday');
$StockRegistry = $objectManager->get('\Magento\CatalogInventory\Api\StockRegistryInterface');
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$getBaseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$tabbyUrl = $getBaseUrl.'tabby-payment-options';
$currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currency = $currencysymbol->getStore()->getCurrentCurrencyCode();
$color_code ="wheel_protector_color";
$swatchHelper = $objectManager->get('Magento\Swatches\Helper\Data');
$outOfStockPhone = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('hdweb/general/call_us_contact');
$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
?>
<div class="section section-padding wheel-protector">
  <div class="container custom-width">
    

    <div class="products wrapper list products-list">

      <ol class="products product-list regular-product-list">
        <?php foreach ($wheelProtectorProductsIds as $productId): ?>
          <?php
          $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
          $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
          $brand = $_helper->productAttribute($_product, $_product->getMgsBrand(), 'mgs_brand');
          $brandDetails = $listingHelper->getBrandDetails($brand); 
          $branimage = $listingHelper->getBrandImageUrl($brandDetails); 
          $brand_title = $brandDetails->getName();
          $productImage = $_imagehelper->init($_product, 'category_page_list')->resize($image_width, $image_height)->getUrl();
          $_productNameStripped = $block->stripTags($_product->getName(), null, true);
          $displayName = $_product->getResource()->getAttribute("display_name")->getFrontend()->getValue($_product);
          $warranty_workmanship_mat=$_product->getResource()->getAttribute("warranty_workmanship_mat")->getFrontend()->getValue($_product);
          $warranty_period = $_product->getResource()->getAttribute("warranty_period")->getFrontend()->getValue($_product);
          $year = $_product->getResource()->getAttribute("year")->getFrontend()->getValue($_product);
          $runflat = $_product->getResource()->getAttribute('runflat')->getFrontend()->getValue($_product);
          $material_number = $_product->getResource()->getAttribute("material_number")->getFrontend()->getValue($_product);
          $set1price = $listingHelper->getSet1price($_product);
          $productpriceWC = $listingHelper->getSet1priceWithoutCurrency($_product);
          $product_url  = $_product->getProductUrl();
          $tabbyMethodAvailable = $_product->getResource()->getAttribute("tabby_method")->getFrontend()->getValue($_product);
          $perItem=$_product->getResource()->getAttribute("per_item")->getFrontend()->getValue($_product);
          $isAnyRuleExist = $AnyRuleExist = $listingHelper->isAnyRuleExist($_product);   
          $borderColor="";    
          $bkgColor="";
          $strikePriceClass = ''; 
          $offer_price = '';   
          if(count($isAnyRuleExist) > 0 ){
            $borderColor='border:2px solid '.$isAnyRuleExist[4];
            $bkgColor='background-color: '.$isAnyRuleExist[4];

            if ($isAnyRuleExist[6] > 3 && $isAnyRuleExist[5] > 0) {
              $strikePriceClass = 'strike-price';
            }
          }

          $stockQty = 0;
          $prod_qty =  $listingHelper->getSalebleQty($_product->getEntityId());
          $isInStock = $StockRegistry->getProductStockStatus($_product->getEntityId());
          if($prod_qty >= 8){
            $stockQty = 8;
          }else{
            $stockQty = $prod_qty;
          }
          $postParams = $listBlock->getAddToCartPostParams($_product);
          ?>
          <li class="list-view d-none d-md-block">
            <div class="product-box height-cover">

              <ul class="list-custom d-flex flex-wrap h-100 tyres-productset4">
                <li class="block-1">
                  <div class="product-image-brand-wrap d-flex flex-wrap align-items-center h-100">
                      <div class="image w-100">
                        <img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" width="400px" height="114px" data-src="<?php echo $branimage ?>" alt="<?php echo $brand_title ?>" class="lazyload" alt="" />
                      </div>
                  </div>
                </li>

                <li class="block-2">
                <div class="product-info d-flex flex-wrap align-items-center h-100">
                  <div class="name w-100">
                    <h4 class="mb-0"><a href="<?php echo $product_url;?>" title="<?php echo $_productNameStripped ?>"><?php echo __($displayName);?></a></h4>
                    <span><?php echo __($material_number);?></span>
                  </div>
                </div>
                </li>

                <li class="block-3">
                    <div class="product-info-additional d-flex flex-wrap align-items-center h-100">
                      <div class="w-100">
                    <?php if($runflat):?> 
                      <div class="run-flat">
                        <span class="icon icon-sprite"></span>
                      </div>
                    <?php endif;?>
                    <?php if($warranty_period):?>
                      <div class="warranty">
                        <span><?php echo __($warranty_period);?></span>
                      </div>
                    <?php endif; ?>
                    <?php if($warranty_workmanship_mat):?>
                      <div class="offer">
                        <span><?php echo __($warranty_workmanship_mat);?></span>
                      </div>
                    <?php endif;?>
                  </div>
                  </div>
                </li>
                <li class="block-4">
                  <div class="color-change-image d-flex flex-wrap align-items-center justify-content-center h-100">
                        <a href="<?php echo $product_url;?>" class="d-block link">
                          <img id="protector-img-<?php echo $_product->getId();?>" src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" width="300px" height="300px" data-src="<?php echo $productImage ?>"
                            class="lazyload" alt="<?php echo $_productNameStripped ?>" id="<?php echo 'img-'.$_product->getId();?>" />
                        </a>
                    </div>
                </li>
                <li class="block-5">
                  <div class="color-selection h-100 d-flex align-items-center justify-content-center">
                        
                        <div class="section-loader size-sm"> 
                        <div class="inner d-flex align-items-center justify-content-center text-center">
                        <div class="spinner mx-auto"></div>
                        </div>
                        </div>

                      <div class="w-100 position-relative">
                      <?php 
                       $childrenProducts = [];
                       if ($_product->getTypeId() === 'configurable') {
                           $childrenProducts = $_product->getTypeInstance()->getUsedProducts($_product);
                       }
                       ?>
                      <?php $i = 1;?>
                      <?php $defaultSelected = array();?>
                      <span class="color-dropdown-label"><?php echo __('Color');?></span>
                      <?php /* <select class="color-option">
                        <?php foreach ($childrenProducts as $child){?>
                        <?php 
                        $optionIds = $child->getData($color_code);
            $colorTitle = $child->getResource()->getAttribute($color_code)->getFrontend()->getValue($child);
                        $swatchData = $swatchHelper->getSwatchesByOptionsId([$optionIds]);
                        $colorCode = $swatchData[$optionIds]['value'];
                        if($i == 1){
                          $defaultSelected[] = $child->getId();
                        }
                        ?>
                          <option value="<?php echo $child->getId();?>" data-mainproduct-id="<?php echo $_product->getId();?>" data-color-code="<?php echo $colorCode;?>" data-image="<?php echo $mediaUrl.'attribute/swatch'.$colorCode;?>" <?php if($i == 1) { echo "selected"; } ?>></option>
                        <?php $i++; } ?>
                      </select> */ ?>
           <div class="position-relative z-index">
            <ul class="main-color-option-list color-option-list" id="main-color-dropdown-ul-<?php echo $_product->getId();?>">
              <li class="init"></li>
            </ul>
            <span class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18.508 8.512">
              <g id="Group_360" data-name="Group 360" transform="translate(-35.805 -11.07)">
              <path id="Path_156" data-name="Path 156" d="M75.754,232.2H57.246l9.254,8.512Z" transform="translate(-21.441 -221.132)" fill="#646464"/></g>
              </svg>
            </span>
           </div>
          <div class="position-relative">
            <ul class="select-color-option-list" id="color-dropdown-ul-<?php echo $_product->getId();?>" style="display:none;">
             <?php /* <li class="init">
             </li> */?>
             <?php foreach ($childrenProducts as $child){?>
              <?php 
              $optionIds = $child->getData($color_code);
              $colorTitle = $child->getResource()->getAttribute($color_code)->getFrontend()->getValue($child);
              $swatchData = $swatchHelper->getSwatchesByOptionsId([$optionIds]);
              $colorCode = $swatchData[$optionIds]['value'];
              if($i == 1){
                $defaultSelected[] = $child->getId();
              }
              ?>
              <?php /* <li class="<?php if($i == 1) { echo "init"; };?>"> */ ?>
              <li class="<?php if($i == 1) { echo "first"; };?>" style="display:none;">
                <img title="<?php echo $colorTitle;?>" value="<?php echo $child->getId();?>" data-mainproduct-id="<?php echo $_product->getId();?>" data-color-code="<?php echo $colorCode;?>" src="<?php echo $mediaUrl.'attribute/swatch'.$colorCode;?>" <?php if($i == 1) { echo "selected"; } ?> />
                <span class="color-option-title"><?php echo $colorTitle;?></span>
              </li>
             <?php $i++; } ?>
            </ul>
          </div>
                   </div>
                    </div>
                </li>

                <li class="block-6">
                <div class="product-price d-flex flex-wrap align-items-center justify-content-center h-100">
                  <div class="w-100 price-box tyro_price_box">
                    <div class="price set1price">
                      <sub class="aed"><?php echo __($currency) ?></sub>
                      <strong class="single-tyre-price"><?php echo $set1price; ?></strong>
                    </div>
                  </div>
                </div>
                </li>

                <li class="block-7">
                <form data-role="tocart-form" action="<?php echo $block->getUrl('oilservice/index/addservicetocart'); ?>" method="post" class="tyro_cart_box h-100">
                          <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                          <input type="hidden" name="uenc" value="">
                          <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                          <div class="cart-qty-wrap d-flex align-items-center justify-content-center h-100">
                            <div class="qty-selection">
                              <?php if ($_product->getIsSalable()):?>
                              <select name="qty" class="select2-qty w-100 select_qty" data-unitprice="<?= $productpriceWC ?>" 
                               <?php echo  (count($AnyRuleExist) > 0 ) ? "data-discountqty=".$AnyRuleExist[5]   :  "";  ?> 
                               <?php echo  (count($AnyRuleExist) > 0 ) ? "data-totalqty=".$AnyRuleExist[6]:"";  ?> 
                                data-istabby="<?php echo $tabbyMethodAvailable; ?>">
                                <option value="1" selected="">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                              </select>
                              <span class="icon icon-sprite arrow"></span>
                              <?php else:?>
                              <?php endif;?>
                            </div>
                            <div class="add-to-cart">
                            <?php if ($_product->getIsSalable()):?>
                            <button type="submit" class="action tocart btn-cart button custom-size button-primary-100 button-rounded filled-slide-up">
                              <span><?php echo __('BUY');?></span>
                            </button>
                            <?php else: ?>
                            <a href="tel:<?php echo $outOfStockPhone; ?>" class="button custom-size button-primary-100 button-rounded filled-slide-up">
                                <span>Call</span>
                            </a>
                            <?php endif; ?>
                            </div>
                          </div>
                          <input type="hidden" id="select-product-id-<?php echo $_product->getId();?>" name="serviceproduct[]" value="<?php echo $defaultSelected[0];?>">
                        </form>
                      </li>

              </ul>

            </div>
          </li>

           <li class="list-view-mobile d-md-none" style="--border-color: #000">
            <div class="product-box">   
            <div class="inner-wrap">
             <div class="row">

             <div class="col-6">
              <div class="left position-relative h-100">
              <div class="product-image d-flex justify-content-center align-items-center">
                <a href="<?php echo $product_url;?>" class="d-block link">
                  <img id="protector-img-<?php echo $_product->getId();?>" src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" width="300px" height="300px" data-src="<?php echo $productImage ?>" class="lazyload" alt="" />
                </a>
              </div>
              </div>
               </div>

               <div class="col-6">
                 <div class="right">
                <div class="product-brand">
                  <img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" width="400px" height="114px" data-src="<?php echo $branimage ?>" alt="<?php echo $brand_title ?>" class="lazyload"
                    />
                </div>

                <div class="product-info">
                  <div class="name">
                    <h4 class="mb-0"><a href="<?php echo $product_url;?>" title="<?php echo $_productNameStripped ?>"><?php echo __($displayName);?></a></h4>
                    <span><?php echo __($material_number);?></span>
                  </div>


                  <div class="product-price">
                    <div class="price w-100 sale set1price">
                      <sub class="aed"><?php echo __($currency) ?></sub> 
                      <strong class="single-tyre-price"><?php echo $set1price; ?></strong>
                    </div>
                  </div>

                  <div class="cart-qty-wrap">
                  <?php if ($_product->getIsSalable()):?>
                      <form data-role="tocart-form" action="<?php echo $block->getUrl('oilservice/index/addservicetocart'); ?>" method="post" class="tyro_cart_box">
                        <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                        <input type="hidden" name="uenc" value="">
                        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                        <div class="d-flex justify-content-end">
                        <div class="qty-selection position-relative">
                          <select name="qty" class="select2-qty w-100 select_qty" id="<?php echo $_product->getId()?>" data-unitprice="<?= $productpriceWC ?>"
                           <?php echo  (count($AnyRuleExist) > 0 ) ? "data-discountqty=".$AnyRuleExist[5]   :  "";  ?> 
                           <?php echo  (count($AnyRuleExist) > 0 ) ? "data-totalqty=".$AnyRuleExist[6]:"";  ?> 
                          data-istabby="<?php echo $tabbyMethodAvailable; ?>">
                          <option value="1" selected="">1</option>
                          <option value="2">2</option>
                          <option value="3">3</option>
                          <option value="4">4</option>
                          <option value="5">5</option>
                          <option value="6">6</option>
                          <option value="7">7</option>
                          <option value="8">8</option>
                          </select>
                          <span class="icon icon-sprite arrow"></span>
                        </div>
                       <div class="add-to-cart">
                        <button type="submit" class="action tocart"><?php echo __('BUY');?></button>
                       </div>
                     </div>
                       <input type="hidden" id="select-product-id-<?php echo $_product->getId();?>" name="serviceproduct[]" value="<?php echo $defaultSelected[0];?>">
                      </form>
                  <?php else: ?>
                    <!-- if product outstoke -->
                      <div class="call-us text-end">
                                    <a href="tel:<?php echo $outOfStockPhone; ?>" class="d-inline-flex justify-content-center align-items-center"><span><?php echo __('Call Us'); ?></span></a>
                                </div>
                    <!-- if product outstoke end-->
                  <?php endif; ?>
                 </div>


                </div>


               </div>
              </div>




             </div>
             <div class="bottom">
              <div class="row g-0 align-items-center justify-content-between">
              <div class="col-auto">

                <div class="color-selection d-flex align-items-center">
                  <div>
                      <span class="color-dropdown-label"><?php echo __('Color');?></span>
                      </div>

                       <div>
                      <div class="position-relative">
            <ul class="main-color-option-list color-option-list" id="main-color-dropdown-ul-<?php echo $_product->getId();?>">
              <li class="init"></li>
            </ul>
                        <span class="icon">
                          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18.508 8.512">
                            <g id="Group_360" data-name="Group 360" transform="translate(-35.805 -11.07)">
                            <path id="Path_156" data-name="Path 156" d="M75.754,232.2H57.246l9.254,8.512Z" transform="translate(-21.441 -221.132)" fill="#646464"></path></g>
                          </svg>
                        </span>
                      </div>
                      <div class="position-relative">
            <ul class="select-color-option-list" id="color-dropdown-ul-<?php echo $_product->getId();?>" style="display:none;">
             <?php foreach ($childrenProducts as $child){?>
              <?php 
              $optionIds = $child->getData($color_code);
              $colorTitle = $child->getResource()->getAttribute($color_code)->getFrontend()->getValue($child);
              $swatchData = $swatchHelper->getSwatchesByOptionsId([$optionIds]);
              $colorCode = $swatchData[$optionIds]['value'];
              if($i == 1){
                $defaultSelected[] = $child->getId();
              }
              ?>
              <li class="<?php if($i == 1) { echo "first"; };?>" style="display:none;">
                <img title="<?php echo $colorTitle;?>" value="<?php echo $child->getId();?>" data-mainproduct-id="<?php echo $_product->getId();?>" data-color-code="<?php echo $colorCode;?>" src="<?php echo $mediaUrl.'attribute/swatch'.$colorCode;?>" <?php if($i == 1) { echo "selected"; } ?> />
                <span class="color-option-title"><?php echo $colorTitle;?></span>
              </li>
             <?php $i++; } ?>
            </ul>
                      </div>
                    </div>
                  </div>

              </div>
              <div class="col-auto">

                <div class="warranty">
                <span><?php echo __($warranty_period);?></span>
              </div>

              <div class="offer">
                    <span><?php echo __($warranty_workmanship_mat);?></span>
                  </div>

              </div>
              </div>
            </div>
          </div>
        </div>
          </li>

        <?php endforeach; ?>
      </ol>
		
    </div>

    

  </div>
</div>
<div class="section alloygator-process">
  <div class="container custom-width">
    <div class="process">
      <ul class="list-custom d-flex flex-wrap justify-content-center">
        <li>
          <div class="box">
            <div class="image sprite mx-auto choose-color"></div>
            <h6 class="fw-bold text-uppercase"><?php echo __('Choose Your Color');?></h6>
          </div>
        </li>
        <li class="step-next-icon d-flex align-items-end justify-content-center">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 70.849 31.151"> <g id="Group_406" data-name="Group 406" transform="translate(-674.412 -2514.339)"> <g id="Group_402" data-name="Group 402" transform="translate(663.342 2581.294) rotate(-90)"> <path id="Path_156" data-name="Path 156" d="M88.4,232.2H57.246l15.575,14.326Z" transform="translate(-21.441 -221.132)" /> </g> <g id="Group_404" data-name="Group 404" transform="translate(691.604 2581.294) rotate(-90)"> <path id="Path_156-2" data-name="Path 156" d="M88.4,232.2H57.246l15.575,14.326Z" transform="translate(-21.441 -221.132)" /> </g> <g id="Group_405" data-name="Group 405" transform="translate(719.865 2581.294) rotate(-90)"> <path id="Path_156-3" data-name="Path 156" d="M88.4,232.2H57.246l15.575,14.326Z" transform="translate(-21.441 -221.132)" /> </g> </g> </svg>
        </li>
        <li>
          <div class="box">
            <div class="image sprite mx-auto fitment-location"></div>
            <h6 class="fw-bold text-uppercase"><?php echo __('Select Fitment Location');?></h6>
          </div>
          <!-- <div class="or-icon text-center">
            <span class="icon sprite mx-auto"></span>
          </div>
          <div class="box">
            <div class="image sprite mx-auto mobile-fitment"></div>
            <h6 class="fw-bold text-uppercase"><?php echo __('Select Mobile');?> <br/> <?php echo __('Fitment Service');?></h6>
          </div> -->
        </li>
        <li class="step-next-icon d-flex align-items-end justify-content-center">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 70.849 31.151"> <g id="Group_406" data-name="Group 406" transform="translate(-674.412 -2514.339)"> <g id="Group_402" data-name="Group 402" transform="translate(663.342 2581.294) rotate(-90)"> <path id="Path_156" data-name="Path 156" d="M88.4,232.2H57.246l15.575,14.326Z" transform="translate(-21.441 -221.132)" /> </g> <g id="Group_404" data-name="Group 404" transform="translate(691.604 2581.294) rotate(-90)"> <path id="Path_156-2" data-name="Path 156" d="M88.4,232.2H57.246l15.575,14.326Z" transform="translate(-21.441 -221.132)" /> </g> <g id="Group_405" data-name="Group 405" transform="translate(719.865 2581.294) rotate(-90)"> <path id="Path_156-3" data-name="Path 156" d="M88.4,232.2H57.246l15.575,14.326Z" transform="translate(-21.441 -221.132)" /> </g> </g> </svg>
        </li>
        <li>
          <div class="box">
            <div class="image sprite mx-auto new-style"></div>
            <h6 class="fw-bold text-uppercase"><?php echo __('New Style');?></h6>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="section color-info">
  <div class="container custom-width">
    <div class="heading-style1 mb-4 text-center">
      <h2><?php echo __('AS EASY AS 1-2-3');?> <br/><span><?php echo __('THE MOST CONVENIENT WAY');?></span></h2>
      <p><?php echo __('TO BUY AND FIT WHEEL PROTECTORS');?></p>
    </div>
    <div class="text-wrap text-center">
      <p><?php echo __('AlloyGators are for wheels ranging from 12″ to 24″ diameter. Each set contains 4 AlloyGator wheel protectors,'); ?><br/><?php echo __(' 6 joining clips, stainless steel securing clips and glue. AlloyGators are also available in 14 colours.'); ?></p>
    </div>
    <div class="color-list">
      <ul class="list-custom d-flex flex-wrap align-items-center justify-content-center">
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Black');?>">
            <span class="color" style="background-color: #000"></span>
            <span class="text"><?php echo __('Black');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Graphite');?>">
            <span class="color" style="background-color: #4F5759"></span>
            <span class="text"><?php echo __('Graphite');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Silver');?>">
            <span class="color" style="background-color: #A9ADB3"></span>
            <span class="text"><?php echo __('Silver');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('White');?>">
            <span class="color" style="background-color: #fff"></span>
            <span class="text"><?php echo __('White');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Bronze');?>">
            <span class="color" style="background-color: #945712"></span>
            <span class="text"><?php echo __('Bronze');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Gold');?>">
            <span class="color" style="background-color: #817037"></span>
            <span class="text"><?php echo __('Gold');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Blue');?>">
            <span class="color" style="background-color: #191094"></span>
            <span class="text"><?php echo __('Blue');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Purple');?>">
            <span class="color" style="background-color: #581E5E"></span>
            <span class="text"><?php echo __('Purple');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Sky Blue');?>">
            <span class="color" style="background-color: #246A98"></span>
            <span class="text"><?php echo __('Sky Blue');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Green');?>">
            <span class="color" style="background-color: #74A802"></span>
            <span class="text"><?php echo __('Green');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Yellow');?>">
            <span class="color" style="background-color: #F2AF02"></span>
            <span class="text"><?php echo __('Yellow');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Pink');?>">
            <span class="color" style="background-color: #DE3173"></span>
            <span class="text"><?php echo __('Pink');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Orange');?>">
            <span class="color" style="background-color: #E7580C"></span>
            <span class="text"><?php echo __('Orange');?></span>
          </div>
        </li>
        <li>
          <div class="color-box" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo __('Red');?>">
            <span class="color" style="background-color: #B40504"></span>
            <span class="text"><?php echo __('Red');?></span>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="section wheel-protectors-info-video">
  <div class="container-fluid px-0">
    <div class="image-wrap picture aspect-16x9 loader text-center">
      <picture>
        <source srcset="<?php echo $mediaUrl.'images/bg/best-alloy-wheel-protectors-in-uae.jpg'; ?>">
        <img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" width="1920px" height="1080px" data-src="<?php echo $mediaUrl.'images/bg/best-alloy-wheel-protectors-in-uae.jpg';?>" class="lazyload" alt="<?php echo __('Best alloy wheel protectors in UAE');?>" />
      </picture>
    </div>
    <a href="javascript:void(0)" class="video-play-icon" data-izimodal-open="#protect-wheels-intro"><svg aria-hidden="true" focusable="false" data-prefix="fad" data-icon="play-circle" class="svg-inline--fa fa-play-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><g class="fa-group"><path  class="fa-secondary" fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm115.7 272l-176 101c-15.8 8.8-35.7-2.5-35.7-21V152c0-18.4 19.8-29.8 35.7-21l176 107c16.4 9.2 16.4 32.9 0 42z" opacity="0.8"></path><path fill="#fff" class="fa-primary" d="M371.7 280l-176 101c-15.8 8.8-35.7-2.5-35.7-21V152c0-18.4 19.8-29.8 35.7-21l176 107c16.4 9.2 16.4 32.9 0 42z"></path></g></svg></a>
  </div>
</div>
<div id="protect-wheels-intro" class="izimodal-videomodal" data-izimodal-transitionin="fadeInDown" data-izimodal-title="Protect Your Wheels Discreetly" data-izimodal-iframeURL="https://www.youtube.com/embed/V2Z3ebiK8go?rel=0&amp;autoplay=1"></div>
<div class="section alloygator-rim">
  <div class="container custom-width">
    <div class="row align-items-center">
      <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-3">
        <div class="image-block text-center">
          <picture>
            <source srcset="<?php echo $mediaUrl.'images/section/best-alloygator-wheel-protection-online.png'; ?>">
            <img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" width="371px" height="371px" data-src="<?php echo $mediaUrl.'images/section/best-alloygator-wheel-protection-online.png'; ?>" class="lazyload" alt="<?php echo __('Best alloygator wheel protection online');?>" />
          </picture>
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-8 col-lg-8 col-xl-7">
        <div class="text-wrap">
          <h2 class="fw-900 text-uppercase"><?php echo __('AlloyGator is the only truly engineered wheel protection solution on the market');?></h2>
          <p><?php echo __('AlloyGator rim protectors fit between the wheel and tyre and are held in place with diamond gripping technology. The AlloyGators use specially designed locking teeth, diamond grips and robust stainless-steel clips to ensure a secure, long-lasting fit to your vehicle. AlloyGators have a rounded edge and matt finish to compliment the appearance of your wheels.');?></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section wheel-protectors-info-video">
  <div class="container-fluid px-0">
    <div class="image-wrap picture aspect-16x9 loader text-center">
      <picture>
        <source srcset="<?php echo $mediaUrl.'images/bg/choose-your-wheel-protector-color.jpg'; ?>">
        <img src="<?php echo $mediaUrl.'images/section/blank.png'; ?>" width="1920px" height="1080px" data-src="<?php echo $mediaUrl.'images/bg/choose-your-wheel-protector-color.jpg'; ?>" class="lazyload" alt="<?php echo __('Choose your wheel protector color');?>" />
      </picture>
    </div>
    <a href="javascript:void(0)" class="video-play-icon" data-izimodal-open="#choose-color"><svg aria-hidden="true" focusable="false" data-prefix="fad" data-icon="play-circle" class="svg-inline--fa fa-play-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><g class="fa-group"><path  class="fa-secondary" fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm115.7 272l-176 101c-15.8 8.8-35.7-2.5-35.7-21V152c0-18.4 19.8-29.8 35.7-21l176 107c16.4 9.2 16.4 32.9 0 42z" opacity="0.8"></path><path fill="#fff" class="fa-primary" d="M371.7 280l-176 101c-15.8 8.8-35.7-2.5-35.7-21V152c0-18.4 19.8-29.8 35.7-21l176 107c16.4 9.2 16.4 32.9 0 42z"></path></g></svg></a>
  </div>
</div>
<div id="choose-color" class="izimodal-videomodal" data-izimodal-transitionin="fadeInDown" data-izimodal-title="Protect Your Wheels Discreetly" data-izimodal-iframeURL="https://www.youtube.com/embed/Jf1eJWVRVX4?rel=0&amp;autoplay=1"></div>
<script type="text/javascript">
  require([
    'jquery',
    'izimodal'
    ], function ($, izimodal) {
	$(document).ready(function() {
		$(".izimodal-videomodal").iziModal({
			history: false,
			iframe : true,
			iframeHeight: 500,
			width: 1000,
			fullscreen: true,
			headerColor: '#000000',
			loop: true
		  });
	 });
});
</script>
<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
  /* jQuery('.color-option').on('change',function() {
    jQuery('.wheel-protector').attr('id', '');
    jQuery(this).closest('.wheel-protector').attr('id', 'active-color-option');
    var selectedChildId = jQuery(this).val();
    var mainProductId = jQuery(this).find(':selected').attr('data-mainproduct-id');
    var ajaxCallUrl= '<?php echo $block->getUrl('oilservice/index/getproductthumbnail'); ?>';
    jQuery.ajax({
        type: 'POST',
        url: ajaxCallUrl,
        data: {product_id: selectedChildId},
        success: function (resultData) {
          if(resultData.status == 'SUCCESS'){
            jQuery('#active-color-option #img-'+mainProductId).attr('src', resultData.img_link);
            jQuery('#active-color-option #select-product-id-'+mainProductId).val(selectedChildId);
          }
        }
    });
  }); */
  $(document).ready(function() {
	   var wheelProtectorProductsIds = <?php echo json_encode($wheelProtectorProductsIds); ?>;
		$.each(wheelProtectorProductsIds, function(key, productIds) {
			/* var $newli = $('#color-dropdown-ul-'+productIds+' li.init').html(); */ 
			var $mainnewli = $('#color-dropdown-ul-'+productIds+' li.first').html();
			/* $( "<li>"+$newli+"</li>" ).insertAfter('#color-dropdown-ul-'+productIds+' li.init'); */ 
			jQuery('#main-color-dropdown-ul-'+productIds+' li.init').html($mainnewli);
			jQuery('.color-selection .section-loader').hide();
		});

		$(document).on("click", "ul.main-color-option-list .init", function() {
			jQuery('.product-box').attr('id', '');
			jQuery(this).closest('.product-box').attr('id', 'active-color-option');
			/* $(this).parent().find('li:not(.init)').toggle(); */ 
			$('#active-color-option .select-color-option-list').toggle();
			$('#active-color-option .select-color-option-list').find('li').toggle();
		});
		
		var allOptions = $("ul.select-color-option-list").children('li:not(.init)');
		
		$("ul.select-color-option-list").on("click", "li:not(.init)", function() {
			allOptions.removeClass('selected');
			$(this).addClass('selected');
			/* $(this).parent().children('.init').html($(this).html()); */ 
			console.log($(this).html());
			$('#active-color-option .main-color-option-list').find('li.init').html($(this).html());
			$(this).parent().toggle();
			$(this).parent().find('li:not(.init)').toggle();
			var value = $(this).find('img').attr('value');
			updateProductImage(value);
		});
	});
	function updateProductImage(selectedChildId){
		/* var mainProductId = $('.color-option-list li.selected img').attr('data-mainproduct-id'); */ 
		var mainProductId = $('.select-color-option-list li.selected img').attr('data-mainproduct-id');
		var ajaxCallUrl= '<?php echo $block->getUrl('oilservice/index/getproductthumbnail'); ?>';
		jQuery.ajax({
			type: 'POST',
			url: ajaxCallUrl,
			data: {product_id: selectedChildId},
			success: function (resultData) {
			  if(resultData.status == 'SUCCESS'){
				jQuery('#active-color-option #protector-img-'+mainProductId).attr('src', resultData.img_link);
				jQuery('#active-color-option #protector-img-'+mainProductId).attr('data-src', resultData.img_link);
				jQuery('#active-color-option #select-product-id-'+mainProductId).val(selectedChildId);
			  }
			}
		});
	}
}); 
</script>
