<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var \MageWorx\OrderEditor\Block\Adminhtml\Sales\Order\Edit\Wrapper $block */?>
<?php if ($block->isEditAllowed()): ?>
<script type="text/javascript">
    // <![CDATA[
    require([
            "MageWorx_OrderEditor/js/order/edit/form/items",
            "MageWorx_OrderEditor/js/order/edit/form/address/billing",
            "MageWorx_OrderEditor/js/order/edit/form/address/shipping",
            "MageWorx_OrderEditor/js/order/edit/form/shipping",
            "MageWorx_OrderEditor/js/order/edit/form/payment",
            "MageWorx_OrderEditor/js/order/edit/form/account",
            "MageWorx_OrderEditor/js/order/edit/form/info",
            "prototype"
        ],
        function(
            mageworxOrderEditorItems,
            mageworxOrderEditorAddressShipping,
            mageworxOrderEditorAddressBilling,
            mageworxOrderEditorShipping,
            mageworxOrderEditorPayment,
            mageworxOrderEditorAccount,
            mageworxOrderEditorInfo
        ) {
            new mageworxOrderEditorItems().init(<?= /* @noEscape */ $block->getJsonParamsItems(); ?>);
            new mageworxOrderEditorAddressBilling().init(<?= /* @noEscape */ $block->getJsonParamsAddress(); ?>);
            new mageworxOrderEditorAddressShipping().init(<?= /* @noEscape */ $block->getJsonParamsAddress(); ?>);
            new mageworxOrderEditorShipping().init(<?= /* @noEscape */ $block->getJsonParamsShipping(); ?>);
            new mageworxOrderEditorPayment().init(<?= /* @noEscape */ $block->getJsonParamsPayment(); ?>);
            new mageworxOrderEditorAccount().init(<?= /* @noEscape */ $block->getJsonParamsAccount(); ?>);
            new mageworxOrderEditorInfo().init(<?= /* @noEscape */ $block->getJsonParamsInfo(); ?>);
        }
    );
    // ]]>
</script>
<?php endif; ?>
