<?php
/**
 * Outputs checkoutConfig for cart totals (Knockout) when the shipping block is not rendered.
 *
 * @var $block \Magento\Checkout\Block\Cart\Shipping
 */
?>
<?php $serializedCheckoutConfig = /* @noEscape */ $block->getSerializedCheckoutConfig(); ?>
<script>
    window.checkoutConfig = <?= /* @noEscape */ $serializedCheckoutConfig ?>;
    window.customerData = window.checkoutConfig.customerData;
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
</script>
