<?php 
/*Continue Shopping Url*/
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
//$categoryUrl = $baseUrl.'all-tyres/car-tyres.html';
$categoryUrl = $this->getBaseUrl().'all-tyres/car-tyres.html';
?>
<div class="main actions">
	<a class="button button button-sm button-dark button-rounded filled-slide-right"
	   href="<?php echo $categoryUrl; ?>"
	   title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
		<span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
	</a>
</div>
<?php /* End of continue shopping cart code*/ ?>	
