<?php
/**
 * Shopping cart totals template
 *
 * @var $block \Magento\Checkout\Block\Cart\Totals
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$configBlock = $block->getLayout()->createBlock(
    \Magento\Checkout\Block\Cart\Shipping::class,
    'checkout.cart.inline_config',
    ['template' => 'Magento_Checkout::cart/checkout-config.phtml']
);
echo $configBlock->toHtml();
?>
<div id="cart-totals" class="cart-totals" data-bind="scope:'block-totals'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
            {
                "#cart-totals": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
    </script>
</div>
