<?php
/**
 * Shopping cart totals template
 *
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */
$configProvider = $block->getLayout()->createBlock(
    \Magento\Checkout\Block\Cart\Shipping::class,
    'cart.totals.checkout.config'
);
$serializedCheckoutConfig = /* @noEscape */ $configProvider->getSerializedCheckoutConfig();
?>
<script>
    window.checkoutConfig = <?= /* @noEscape */ $serializedCheckoutConfig ?>;
    window.customerData = window.checkoutConfig.customerData;
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
</script>
<div id="cart-totals" class="cart-totals" data-bind="scope:'block-totals'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
            {
                "#cart-totals": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
    </script>
</div>
