<?php
/**
 * Shopping cart totals template
 *
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */
$configProvider = $block->getLayout()->createBlock(
    \Magento\Checkout\Block\Cart\Shipping::class,
    'cart.totals.checkout.config'
);
$serializedCheckoutConfig = /* @noEscape */ $configProvider->getSerializedCheckoutConfig();
?>
<script>
    window.checkoutConfig = <?= /* @noEscape */ $serializedCheckoutConfig ?>;
    window.customerData = window.checkoutConfig.customerData;
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
</script>
<div id="cart-totals" class="cart-totals">
    <div class="table-wrapper">
        <table class="data table totals">
            <?= /* @noEscape */ $block->renderTotals(-1, 1) ?>
        </table>
    </div>
</div>
