<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cartModel = $_objectManager->get('Magento\Checkout\Model\Cart');
$quote = $cartModel->getQuote();
$class = '';
$display = 'display:none';
$installer_name     = "";
$installer_name_rtl     = "";
$installer_address  = "";
$installer_address_rtl  = "";
$installer_datetime = '';
$hasInstaller = 'Select';
$pickup_installer_service = 0;
$installer_lat     = "";
$installer_lng  = "";
//$quote->setPickupStore(null);
//$quote->save();
$pickup_store = $quote->getPickupStore();

if(isset($pickup_store) && !empty($pickup_store) && $pickup_store) {
$collectionFactory= $_objectManager->get('Ecomteck\StoreLocator\Model\ResourceModel\Stores\CollectionFactory');
$collection = $collectionFactory->create();
$collection->addActiveFilter();
$collection->addFieldToFilter("stores_id", (int) $pickup_store);
if ($collection) {
    $class='active';
    $display = 'display:block;';
    $hasInstaller = 'Change';
    $store_info = $collection->getFirstItem();
    $store_data = $store_info->getData();
    $installer_name     = $store_data['name'] ?? '';
    $installer_name_rtl     = $store_data['name_rtl'] ?? ($store_data['name'] ?? '');
    $installer_address  = $store_data['address'] ?? '';
    $installer_address_rtl  = $store_data['address_rtl'] ?? ($store_data['address'] ?? '');
    $pickup_installer_service  = $store_data['pickup_service'] ?? 0;
    $installer_lat   = $store_data['latitude'] ?? '';
    $installer_lng  = $store_data['longitude'] ?? '';
    $installer_datetime = date("l, F d, Y", strtotime($quote->getPickupDate())).' '.$quote->getPickupTime();
}
}
$hasMobileVanTyreService = 0;
if(isset($_COOKIE['mobilevanservice_data'])){
	$hasMobileVanTyreService = 1;
	
	/* remove this code after upload app/code/Hdweb/Coreoverride/Controller/Cart/Index.php file */
	$quote->setPickupLocation('');
	$quote->setDeliveryDate('');
	$quote->setDeliveryComment('');
	$quote->setPickupDate('');
	$quote->setPickupTime('');
	$quote->setPickupStore('');
	$quote->setMobilevanserviceLocation('');
	
	$cookieValue = stripslashes($_COOKIE['mobilevanservice_data']);
	$serviceData = json_decode($cookieValue, true);
	$mobilevanserviceAddress = $serviceData['mobilevanservice_address'];
	$mobilevanserviceLocation_lat = $serviceData['mobilevanservice_location_lat'];
	$mobilevanserviceLocation_lng = $serviceData['mobilevanservice_location_lng'];
	$mobilevanserviceDate = $serviceData['mobilevanservice_date'];
	$mobilevanserviceTime = $serviceData['mobilevanservice_time'];
	$mobilevanserviceNotes = $serviceData['mobilevanservice_notes'];
	$mobileVanInstallerId = $_objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('installer/general/mobilevan_fitment_service_installer');
	$this->_checkoutSession = $_objectManager->get('Magento\Checkout\Model\Session');
	if($mobileVanInstallerId){
		$mobileVanServiceData = array();
		$mobileVanServiceData['address'] = $mobilevanserviceAddress;
		$mobileVanServiceData['lat'] = $mobilevanserviceLocation_lat;
		$mobileVanServiceData['long'] = $mobilevanserviceLocation_lng;
		$mobileVanServiceData['date'] = $mobilevanserviceDate;
		$mobileVanServiceData['time'] = $mobilevanserviceTime;
		$mobileVanServiceData['notes'] = $mobilevanserviceNotes;
		
		$quote->setPickupDate($mobilevanserviceDate);
		$quote->setPickupTime($mobilevanserviceTime);
		$quote->setPickupStore($mobileVanInstallerId);
		$quote->setDeliveryDate($mobilevanserviceDate);
		$quote->setDeliveryComment($mobilevanserviceTime);
		$this->_checkoutSession->setPickupdate($mobilevanserviceDate);
		$this->_checkoutSession->setPickuptime($mobilevanserviceTime);
		$this->_checkoutSession->setPickupstoreid($mobileVanInstallerId);
		$quote->setMobilevanserviceLocation(serialize($mobileVanServiceData));
	}
	$quote->save();
	
	/* remove above code after upload app/code/Hdweb/Coreoverride/Controller/Cart/Index.php file */
}
$storeManager = $_objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeCode = $storeManager->getStore()->getCode();
?>

<div id="cart-fitting-location" class="section_bg fitting-location-box" <?php if ($hasMobileVanTyreService){ echo 'style="display:none;"'; };?>>
    <div class="checkout_title" data-toggle="modal" data-bs-toggle="modal" data-bs-target="#mycartinstallerModal">
        <div class="icon">
        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 53.3 39.3" style="enable-background:new 0 0 53.3 39.3;" xml:space="preserve">
            <defs><rect id="SVGID_1_" y="0" width="53.3" height="39.3"/></defs>
            <clipPath id="SVGID_2_"><use xlink:href="#SVGID_1_"style="overflow:visible;"/></clipPath>
            <path class="car_icon" d="M45.5,19.9c0,0-1.2-4.4-1.5-5.6c-0.4-1.8-1.5-2.7-2.8-3.3l-2.4-7.4c-0.7-1.9-3-3.5-5.1-3.5H19.5
                c-2.1,0-4.4,1.6-5.1,3.5L12,10.9c-1.3,0.6-2.4,1.5-2.8,3.3c-0.3,1.3-1.5,5.6-1.5,5.6c-0.4,1.9,0.9,3.5,2.9,3.5h1.5v3.9
                c0,0.7,0.6,1.4,1.4,1.4h2.9c0.7,0,1.4-0.6,1.4-1.4v-3.9h17.8v3.9c0,0.7,0.6,1.4,1.4,1.4h2.9c0.7,0,1.4-0.6,1.4-1.4v-3.9h1.5
                C44.6,23.4,45.9,21.8,45.5,19.9 M15.4,19.6c-1.3,0-2.3-1-2.3-2.3c0-1.3,1-2.3,2.3-2.3c1.3,0,2.3,1,2.3,2.3
                C17.7,18.6,16.6,19.6,15.4,19.6 M30.7,19.7h-8.1c-0.6,0-1.1-0.5-1.1-1.1s0.5-1.1,1.1-1.1h8.1c0.6,0,1.1,0.5,1.1,1.1
                S31.3,19.7,30.7,19.7 M15.3,10.2c0,0,1.2-4.4,1.8-5.7c0.6-1.3,1.6-1.7,2.5-1.7h14.2c0.9,0,2.1,0.7,2.5,1.7c0.4,1,1.8,5.7,1.8,5.7
                H15.3z M37.9,19.6c-1.3,0-2.3-1-2.3-2.3c0-1.3,1-2.3,2.3-2.3c1.3,0,2.3,1,2.3,2.3C40.2,18.6,39.2,19.6,37.9,19.6"/>
            <path class="car_icon" d="M48.8,36.1c0,0.2-0.1,0.3-0.3,0.3c-0.1,0-0.3-0.1-0.3-0.3v-26c0-0.2,0.1-0.3,0.3-0.3c0.2,0,0.3,0.1,0.3,0.3
                V36.1z M5,36.1c0,0.2-0.1,0.3-0.3,0.3c-0.2,0-0.3-0.1-0.3-0.3v-26c0-0.2,0.1-0.3,0.3-0.3C4.9,9.9,5,10,5,10.1V36.1z M53.3,39.2
                l-2.1-3c0,0,0-0.1,0-0.1L49.8,8.4c0-0.7-0.6-1.3-1.4-1.2c-0.7,0-1.2,0.6-1.2,1.2l-0.7,13.3h-8.7c-0.5,0-0.8,0.4-0.8,0.8
                c0,0.5,0.4,0.8,0.8,0.8h8.6l-0.6,12.7H31.3H22H7.4L6.8,23.4h8.6c0.5,0,0.8-0.4,0.8-0.8c0-0.5-0.4-0.8-0.8-0.8H6.7L6.1,8.4
                c0-0.7-0.6-1.2-1.2-1.2c-0.7,0-1.3,0.5-1.4,1.2L2.1,36.1c0,0,0,0,0,0.1l-2.1,3h24.5h4.2H53.3z"/>
        </svg>
        </div>
        <span><?php echo __('Select Fitting Location');?></span>
    </div>
    <form id="cart-installer-form" class="form box-head">
    <div class="form_filds_custom">
        <a class="link" id="cart-installer-location" href="javascript:void(0)" data-toggle="modal" data-bs-toggle="modal" data-bs-target="#mycartinstallerModal">
            <?php echo __($hasInstaller) ?>
        </a>
		<?php /* <a href="javascript:void(0)" class="link" id="cart-installer-location" data-izimodal-open="#mycartinstallerModal">
			<?php echo __($hasInstaller) ?>
		</a> */ ?>
        <span class="icon">
            <svg version="1.1" viewBox="0 0 752 752" xmlns="http://www.w3.org/2000/svg">
             <path d="m432.83 196.52c-74.352 0-134.97 60.617-134.97 134.97 0 22.73 5.6836 44.043 15.629 62.984l-122.66 100.4c-12.785 10.418-14.68 28.887-4.2617 41.676 10.418 12.785 28.887 14.68 41.676 4.2617l123.61-100.87c22.73 17.051 50.672 26.992 80.98 26.992 74.352 0 134.97-60.617 134.97-134.97 0-74.355-60.617-135.45-134.97-135.45zm0 246.26c-61.566 0-111.29-49.727-111.29-111.29s49.727-111.29 111.29-111.29c61.566 0 111.29 49.727 111.29 111.29-0.003906 61.566-50.203 111.29-111.29 111.29z"/>
            </svg>
        </span>
    </div>
    </form> 
    <div class="box-body">
    <ul class="fittingLocationList" style="<?php echo $display;?>">
        <li>
            <div class="list_1">
                <h5 id="selected-installer-name">
                    <?php if($storeCode == 'en'): ?>
                        <?php echo $installer_name;?>
                    <?php else: ?>
                        <?php echo $installer_name_rtl;?>
                    <?php endif; ?>
                </h5>
                <span id="selected-installer-addr">
                    <?php if($storeCode == 'en'): ?>
                        <?php echo $installer_address;?>
                    <?php else: ?>
                        <?php echo $installer_address_rtl;?>
                    <?php endif; ?>
                </span>
            </div>
            <div class="list_2">
                <a href="javascript:void(0)" class="installer-url" id="selectedInstaller" data-toggle="modal" data-target="#selectedInstallerPopupModal" data-lat="<?php echo $installer_lat;?>" data-lng="<?php echo $installer_lng;?>" data-bs-toggle="modal" data-bs-target="#selectedInstallerPopupModal">
                    <span><?php echo __('See on Map');?></span>
                    <img src="<?php echo $this->getViewFileUrl('images/google-maps.png'); ?>">
                </a>
            </div>
            <div class="list_3">
                <span id="selected-installer-date-time"><?php echo $installer_datetime;?></span>
            </div>
            <div class="closeList" id="cancel-selected-installer"><a href="javascript:void(0)"><svg aria-hidden="true" focusable="false" data-prefix="fal" data-icon="times" class="svg-inline--fa fa-times fa-w-10" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M193.94 256L296.5 153.44l21.15-21.15c3.12-3.12 3.12-8.19 0-11.31l-22.63-22.63c-3.12-3.12-8.19-3.12-11.31 0L160 222.06 36.29 98.34c-3.12-3.12-8.19-3.12-11.31 0L2.34 120.97c-3.12 3.12-3.12 8.19 0 11.31L126.06 256 2.34 379.71c-3.12 3.12-3.12 8.19 0 11.31l22.63 22.63c3.12 3.12 8.19 3.12 11.31 0L160 289.94 262.56 392.5l21.15 21.15c3.12 3.12 8.19 3.12 11.31 0l22.63-22.63c3.12-3.12 3.12-8.19 0-11.31L193.94 256z"></path></svg></a></div>
        </li>
    </ul>
    </div>
</div>
<div class="modal fade" id="mycartinstallerModal" tabindex="-1" aria-labelledby="mycartinstallerModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-custom-width bs-custom-modal">
    <div class="modal-content">
        <span class="close" data-bs-dismiss="modal"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path d="M312.1 375c9.369 9.369 9.369 24.57 0 33.94s-24.57 9.369-33.94 0L160 289.9l-119 119c-9.369 9.369-24.57 9.369-33.94 0s-9.369-24.57 0-33.94L126.1 256L7.027 136.1c-9.369-9.369-9.369-24.57 0-33.94s24.57-9.369 33.94 0L160 222.1l119-119c9.369-9.369 24.57-9.369 33.94 0s9.369 24.57 0 33.94L193.9 256L312.1 375z"/></svg></span>
      <div class="modal-body">
		<?php echo $this->getLayout()->createBlock("Ecomteck\StoreLocator\Block\StoreLocator")->setTemplate("Ecomteck_StoreLocator::storelocator/right.phtml")->setData('defer_init', true)->toHtml() ?>
      </div>
    </div>
  </div>
</div>

<!-- start Modal for selected installer map -->
  <div class="modal fade" id="selectedInstallerPopupModal" tabindex="-1" role="dialog" aria-labelledby="selectedInstallerPopupModalLabel">
    <div class="modal-dialog modal-dialog-centered modal-custom-width-lg bs-custom-modal" role="document">
      <div class="modal-content">
        <div class="modal-title"><span>See on Map</span></div>
        <span class="close white" data-bs-dismiss="modal"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path d="M312.1 375c9.369 9.369 9.369 24.57 0 33.94s-24.57 9.369-33.94 0L160 289.9l-119 119c-9.369 9.369-24.57 9.369-33.94 0s-9.369-24.57 0-33.94L126.1 256L7.027 136.1c-9.369-9.369-9.369-24.57 0-33.94s24.57-9.369 33.94 0L160 222.1l119-119c9.369-9.369 24.57-9.369 33.94 0s9.369 24.57 0 33.94L193.9 256L312.1 375z"/></svg></span>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-12 modal_body_map">
              <div class="location-map" id="location-map">
                <div style="width: 600px; height: 450px;" id="map_canvas_selected_instlr"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- end Modal for selected installer map -->
<input type="hidden" id="pickup_installer_lat" value="<?php echo $installer_lat;?>"/>
<input type="hidden" id="pickup_installer_lng" value="<?php echo $installer_lng;?>"/>
<input type="hidden" id="pickup_installer_service" value=""/>
<input type="hidden" id="pickup_destination_lat" value=""/>
<input type="hidden" id="pickup_destination_lng" value=""/>
<input type="hidden" id="different_destination_lat" value=""/>
<input type="hidden" id="different_destination_lng" value=""/>
<input type="hidden" id="is_different_destination" value=""/>
<script type="text/javascript">
  require([
    'jquery',
    'mage/storage',
    'Magento_Checkout/js/action/get-totals',
    'Magento_Checkout/js/model/quote',
    'Magento_Checkout/js/action/get-payment-information',
    'Magento_Checkout/js/model/totals',
    'Magento_Checkout/js/model/cart/totals-processor/default'
     ], function ($,storage,getTotalsAction,quote,getPaymentInformationAction, totals, totalsDefaultProvider) {
    'use strict';

    var selectedPickupStore="<?php echo $pickup_store ?>";
    var pickup_installer_service="<?php echo $pickup_installer_service ?>";
    var installer_lat="<?php echo $installer_lat ?>";
    var installer_lng="<?php echo $installer_lng ?>";
    var changeTxt = '<?php echo __('Change'); ?>';
    var noDateOrTimeSelectedTxt = '<?php echo __('Please select date and time'); ?>';
	var hasMobileVanTyreService = "<?php echo $hasMobileVanTyreService ?>";
    var storeCode = '<?php echo $storeCode; ?>';
      /* var options = {
                type: 'popup',
                modalClass: 'mycartinstallerModal_modal',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: 'mymodal1',
                    click: function () {
                        this.closeModal();
                    }
                }]
            }; */

            /* var mycartinstallerModal = modal(options, $('#mycartinstallerModal'));
            $("#cart-installer-location").on('click',function(){
				alert('Test');
                $("#mycartinstallerModal").modal("openModal");
				$(".storePickupdatepicker").val('');
				$(".storePickuptimepicker").val('');
            }); */

        jQuery(document).ready(function() {
           var carturl = "<?php echo $this->getUrl().'checkout/cart'?>";
           var checkouturl = "<?php echo $this->getUrl().'checkout'?>";
		  /* jQuery(".checkout button.checkout").attr('data-bs-toggle', 'modal');
		   jQuery(".checkout button.checkout").attr('data-bs-target', '#mycartinstallerModal');
               $('.checkout').click(function(e){
                    var installerLat = $('#pickup_installer_lat').val();
                    var installerLng = $('#pickup_installer_lng').val();
                    if(installerLat != '' && installerLat != ''){ // check is no fitting selected
					    jQuery(".checkout button.checkout").attr('data-bs-toggle', '');
						jQuery(".checkout button.checkout").attr('data-bs-target', '');
                        return true;
                    } else{
                        if(installerLat == '' && installerLng == ''){
                          // alert('Please select fitting installer and proceed to checkout.');
                          //$("#mycartinstallerModal").modal("openModal");
						 // $('#mycartinstallerModal').modal('show');
							jQuery(".checkout button.checkout").attr('data-bs-toggle', 'modal');
							jQuery(".checkout button.checkout").attr('data-bs-target', '#mycartinstallerModal');
                            e.preventDefault();
                            e.stopImmediatePropagation();
                            return false;
                        }
                    }
                    
                }); */
				
				var installerLat = $('#pickup_installer_lat').val();
                var installerLng = $('#pickup_installer_lng').val();
				
				if(installerLat != '' && installerLat != ''){
					jQuery('.action.checkout').show();
					jQuery('.restrict-checkout').hide();
				}else if(hasMobileVanTyreService == 1){
					jQuery('.action.checkout').show();
					jQuery('.restrict-checkout').hide();
				}else{
					jQuery('.action.checkout').hide();
					jQuery('.restrict-checkout').show();
				}

              jQuery(document).on('click', '.submitstore', function(){
                    var pickup_date=jQuery(this).parent().parent().find('.storePickupdatepicker').val();
                    //var pickup_time=jQuery(this).parent().parent().find('.storePickuptimepicker').val();
                    var pickup_time=jQuery(this).parent().parent().find('.storePickuptimepicker option:selected').val();
                    var pickup_store=jQuery(this).parent().parent().find('.pickup_store_id').val();
					console.log(pickup_date);
					console.log(pickup_time);
                    if(pickup_date != "" && (pickup_time != "" && typeof pickup_time !== "undefined")){
                           var customurl = "<?php echo $this->getUrl().'installer/ajax/savecartinstaller'?>";
                            var data = {'pickup_store': pickup_store,'pickup_date': pickup_date, 'pickup_time': pickup_time};

                            $('body').trigger('processStart');
                             return storage.post(
                                'installer/ajax/savecartinstaller',
                                JSON.stringify(data),
                                true
                            ).done(
                                function (response) {
                                    //console.log(response);
                                    if(response.message == 'success') {  
                                        if(storeCode == 'en'){
                                           jQuery('#selected-installer-name').text(response.name);
                                           jQuery('#selected-installer-addr').text(response.address);
                                        } else {
                                           jQuery('#selected-installer-name').text(response.name_rtl);
                                           jQuery('#selected-installer-addr').text(response.address_rtl);
                                        }
                                       jQuery('#pickup_installer_lat').val(response.installer_lat);
                                       jQuery('#pickup_installer_lng').val(response.installer_lng);
                                       jQuery('#pickup_installer_service').val(response.pickup_service);
                                        var installerDate = new Date(response.installer_date);
                                        var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }
                                        var installerDatetime = installerDate.toLocaleDateString('en-US', options) +' '+response.installer_time; 
                                        jQuery('#selected-installer-date-time').text(installerDatetime);
                                        jQuery('#cart-installer-location').text(changeTxt);   
                                        jQuery('.fittingLocationList').show();
                                        jQuery("#selectedInstaller").attr("data-lat",response.installer_lat);    
                                        jQuery("#selectedInstaller").attr("data-lng",response.installer_lng);    
                                        selectedPickupStore=pickup_store;
                                    }
                                    if (response.pickup_service == 0) {
                                        $('#custom-vehicle-div .pickupDropOption .no').trigger('click');
                                    }
                                     totalsDefaultProvider.estimateTotals(quote.shippingAddress()); 
                                     $('#mycartinstallerModal .close').trigger('click');
									 jQuery('.action.checkout').show();
									 jQuery('.restrict-checkout').hide();
                                }
                            ).fail(function () {
                                alert('<?php echo __('Unable to save fitting location. Please try again.'); ?>');
                            }).always(function () {
                                $('body').trigger('processStop');
                            });
                    }else{
                        alert(noDateOrTimeSelectedTxt);
                    }
              });

              $(document).on('click', '#cancel-selected-installer', function(){
                var installerId =   0;
                $('body').trigger('processStart');
                var data = {'installer_id': installerId};
                        return storage.post(
                                'installer/ajax/savecartinstaller',
                                JSON.stringify(data),
                                true
                            ).done(
                                function (response) {
                                    if(response.message == 'success') {  
                                       jQuery('#selected-installer-name').text('');
                                       jQuery('#selected-installer-addr').text('');  
                                       jQuery('#selected-installer-date-time').text('');   
                                       jQuery('.fittingLocationList').hide();   
                                       selectedPickupStore=""; 
                                    }     
                                     location.reload();
                                }
                            ).fail(function () {
                                alert('<?php echo __('Unable to remove fitting location. Please try again.'); ?>');
                            }).always(function () {
                                $('body').trigger('processStop');
                            });
               });
        });
        // Code goes here

        $(document).ready(function() {
          var map = null;
          var myMarker;
          var myLatlng;

          function initializeGMap(lat, lng) {
            myLatlng = new google.maps.LatLng(lat, lng);

            var myOptions = {
              zoom: 18,
              zoomControl: true,
              center: myLatlng,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            map = new google.maps.Map(document.getElementById("map_canvas_selected_instlr"), myOptions);

            myMarker = new google.maps.Marker({
              position: myLatlng
            });
            myMarker.setMap(map);
          }

          // Re-init map before show modal
          $('#selectedInstallerPopupModal').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget);
            initializeGMap(button.data('lat'), button.data('lng'));
            $("#location-map").css("width", "100%");
            $("#map_canvas_selected_instlr").css("width", "100%");
          });

          // Trigger map resize event after modal shown
          $('#selectedInstallerPopupModal').on('shown.bs.modal', function() {
            google.maps.event.trigger(map, "resize");
            map.setCenter(myLatlng);
          });
        });   
   });   
</script>    