<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$Quote = $objectManager->get('Magento\Checkout\Model\Cart');
$isEnablefitmentinstaller = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('installer/general/no_fitment_installer');
$InstallerId = 0; //$Quote->getQuote()->getInstallerId();
/* $tabbyMethodAvailable = $objectManager->create('Hdweb\Installerservice\Helper\Data')->tabbyMethodAvailable(); //check tabby method
if($tabbyMethodAvailable == 0){
	setcookie('tabbymethod_available', 0, time() + (86400 * 15), "/");
}else{
	setcookie('tabbymethod_available', 1, time() + (86400 * 15), "/");
} */
$hasMobileVanTyreService = 0;
if(isset($_COOKIE['mobilevanservice_data'])){
	$hasMobileVanTyreService = 1;
}
?>
<?php if($isEnablefitmentinstaller != ''):?>
<div class="garage">
	<?php if(!$hasMobileVanTyreService):?>
	<div class="garage_switch">
		<div class="container_switch small">
		  <label for="fully-fitted" id="fully-fitted_label" class="switch-label-small before active"><?php echo __('With Fitting');?></label>
		  <div class="switch">
			<input type="radio" class="switch-input" name="fitment_installer" value="1" id="fully-fitted"  
			<?php //echo ($InstallerId != $isEnablefitmentinstaller) ? "checked=''" : "" ?> checked>
			<label for="fully-fitted" class="switch-label switch-label-off"></label>
			<input type="radio" class="switch-input" name="fitment_installer" value="0" id="mail-order"
			<?php //echo ($InstallerId == $isEnablefitmentinstaller) ? "checked=''" : "" ?> >
			<label for="mail-order" class="switch-label switch-label-on"></label>
			<span class="switch-selection"></span>
		  </div>
		  <label for="mail-order" id="mail-order_label" class="switch-label-small after"><?php echo __('No Fitting');?></label>
		</div>
	</div>

	<div class="garage-info" id="ship_to_installer">
		<div class="not_selected">
			<p><?php echo __('With tyre Installation - Deliver to Installer Partner');?></p>
		</div>
	</div>

	<div class="garage-info" id="ship_to_address" style="display:none">
		<div class="not_selected">
			<p><?php echo __('Without tyre Installation - Deliver to my Address');?></p>
		</div>
	</div>
	<input type="hidden" id="fitment_installerId" value="<?php echo $isEnablefitmentinstaller;?>" />
	<?php else:?>
	<?php 
	$cookieValue = stripslashes($_COOKIE['mobilevanservice_data']);
	$serviceData = json_decode($cookieValue, true);
	$mobilevanserviceLocation_lat = $serviceData['mobilevanservice_location_lat'];
	$mobilevanserviceLocation_lng = $serviceData['mobilevanservice_location_lng'];
	$mobilevanserviceDate = $serviceData['mobilevanservice_date'];
	$mobilevanserviceTime = $serviceData['mobilevanservice_time'];
	$installer_datetime = date("l, F d, Y", strtotime($mobilevanserviceDate)).' - '.$mobilevanserviceTime;
	$latLong = $mobilevanserviceLocation_lat.','.$mobilevanserviceLocation_lng;
	?> 
	<div class="garage-info ifmobilevan-service">
		<span class="container_switch"><?php echo $installer_datetime.', ';?> <a href="http://maps.google.com/?q=<?php echo $latLong;?>" target="_blank"><?php echo __('Location Coordinates');?></a></span>
	</div>
	<?php endif;?>
</div>
<?php endif;?>

<?php /* End Fitment Installer Toggle */ ?>
<script type="text/javascript">
require([
	'jquery', 
	'mage/storage',
	'Magento_Checkout/js/model/quote',
	'Magento_Checkout/js/action/get-totals',
	'Magento_Checkout/js/model/cart/totals-processor/default'
	], function($,storage,quote,getTotalsAction,totalsDefaultProvider){
	jQuery('.container_switch.small input[type=radio]').change(function() {
		jQuery('.container_switch.small .switch-label-small').removeClass('active');
		if(this.value == "0"){
			jQuery('.container_switch.small .switch-label-small.after').addClass('active');
			jQuery("#ship_to_address").show();
			jQuery("#ship_to_installer").hide();
			jQuery('#cart-fitting-location').hide();  
			jQuery('#custom-vehicle-div').hide();  
		}else{
			jQuery('.container_switch.small .switch-label-small.before').addClass('active');
			jQuery("#ship_to_address").hide();
			jQuery("#ship_to_installer").show();
			jQuery('#cart-fitting-location').show();  
			jQuery('#custom-vehicle-div').show();  
		}
		
		var installerId = jQuery('#fitment_installerId').val();
		var data = {'fitment_installer': this.value,'installer_id': installerId};
		var cartInstLocText = '<?php echo __('Select'); ?>';
		return storage.post(
				'installer/ajax/setfitment',
				JSON.stringify(data),
				true
			).done(
				function (response) {
					console.log(response);
					if(response.no_fitting == 1){
						jQuery('#pickup_installer_lat').val(response.installer_lat);
						jQuery('#pickup_installer_lng').val(response.installer_lng);
						jQuery('#pickup_installer_service').val(response.pickup_service);
						jQuery(".checkout button.checkout").attr('data-bs-toggle', '');
						jQuery(".checkout button.checkout").attr('data-bs-target', '');
					}else{
						jQuery('#pickup_installer_lat').val('');
						jQuery('#pickup_installer_lng').val('');
						jQuery('#pickup_installer_service').val('');
						jQuery('#cart-installer-location').text(cartInstLocText);
						jQuery('.fittingLocationList').hide();
						jQuery(".checkout button.checkout").attr('data-bs-toggle', 'modal');
						jQuery(".checkout button.checkout").attr('data-bs-target', '#mycartinstallerModal');
					}
					if($(".garage #ship_to_address").is(":visible")){ // check is no fitting selected
						$('#custom-vehicle-div .pickupDropOption .no').trigger('click'); //remove pickup/drop charges
					} 
					totalsDefaultProvider.estimateTotals(quote.shippingAddress());
				}
			);
	});
	/*below is to solve, if we come back to cart page from checkout wrong radio selected issue*/
	jQuery('input:radio[name="fitment_installer"]').filter('[value="1"]').attr('checked', true);
});	
</script>
<style>
.garage {
    display: none;
}
.checkout-cart-index .cart.table-wrapper {
    border-radius: 25px;
}
</style>