<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $block->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>
    <tr class="<?php /* @escapeNotVerified */ echo $_code?>" style=" text-align: right;background: #fff;" >
        <td colspan="4" scope="row" style="background: #fff !important;" >
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $block->escapeHtml($_total->getLabel());?></strong>
            <?php else:?>
            <?php echo $block->escapeHtml($_total->getLabel());?>
            <?php endif?>
        </td>
        <td colspan="4" scope="row" data-td="<?php echo $block->escapeHtml($_total->getLabel());?>" style="text-align: right;background: #fff !important;">
            <?php if ($_total->getStrong()):?>
            <strong><?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?></strong>
            <?php else:?>
            <?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach?>
