<?php
//$helper = $this->helper('MGS\Brand\Helper\Data');
//$collection = $block->getBrandCollection();
$baseUrl = $this->getBaseUrl();
?>
<div class="section brands">
  <div class="container custom-width">
    <div class="heading-style6 mb-55 text-center">
      <h2 class="text-uppercase"><?php echo __('Authorized Tyre brands'); ?></h2>
      <p><?php echo __('We have brands for every taste and need. From globally established, award winning and innovative brands to newcomers in the market looking to make their mark.'); ?></p>
    </div>
    <div class="brand-list">
      <div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-4 row-cols-xl-5 justify-content-center">
        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/matrax-tyres.html'; ?>" class="d-block" aria-label="matrax"><span class="image brand-sprite matrax"></span></a>
        </div>
                <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/pirelli.html'; ?>" class="d-block" aria-label="pirelli"><span class="image brand-sprite pirelli"></span></a>
        </div>
                <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/bridgestone.html'; ?>" class="d-block" aria-label="bridgestone"><span class="image brand-sprite bridgestone"></span></a>
        </div>
                <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/michelin.html'; ?>" class="d-block" aria-label="michelin"><span class="image brand-sprite michelin"></span></a>
        </div>
        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/continental.html'; ?>" class="d-block" aria-label="continental"><span class="image brand-sprite continental"></span></a>
        </div>

        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/goodyear.html'; ?>" class="d-block" aria-label="goodyear"><span class="image brand-sprite goodyear"></span></a>
        </div>
         <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/yokohama.html'; ?>" class="d-block" aria-label="yokoma"><span class="image brand-sprite yokoma"></span></a>
        </div>
         <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/dunlop.html'; ?>" class="d-block" aria-label="dunlop"><span class="image brand-sprite dunlop"></span></a>
        </div>

        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/bfgoodrich.html'; ?>" class="d-block" aria-label="bfgoodrich"><span class="image brand-sprite bfgoodrich"></span></a>
        </div>

        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/mastercraft.html'; ?>" class="d-block" aria-label="mastercraft"><span class="image brand-sprite mastercraft"></span></a>
        </div>

           <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/hankook.html'; ?>" class="d-block" aria-label="hankok"><span class="image brand-sprite hankok"></span></a>
        </div>

        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/nexen.html'; ?>" class="d-block" aria-label="nexen"><span class="image brand-sprite nexen"></span></a>
        </div>

        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/kumho.html'; ?>" class="d-block" aria-label="kumho"><span class="image brand-sprite kumho"></span></a>
        </div>

         <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/falken.html'; ?>" class="d-block" aria-label="falken"><span class="image brand-sprite falken"></span></a>
        </div>

        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres/brand/coopertires.html'; ?>" class="d-block" aria-label="coopertires"><span class="image brand-sprite coopertires"></span></a>
        </div>
       

      </div>
    </div>
    <div class="show-all text-center">
      <a href="<?php echo $baseUrl.'all-tyre-brands'; ?>" class="button button-primary-100 text-uppercase button-rounded filled-slide-right"><span><?php echo __('SEE ALL BRANDS'); ?></span></a>
    </div>
  </div>
</div>