<?php
//$helper = $this->helper('MGS\Brand\Helper\Data');
//$collection = $block->getBrandCollection();
$baseUrl = $this->getBaseUrl();
?>
<div class="section brands">
  <div class="container custom-width">
    <div class="heading-style6 mb-55 text-center">
      <h2 class="text-uppercase"><?php echo __('Tyre Brands'); ?> <span><?php echo __('We Trust'); ?></span></h2>
      <p><?php echo __('We have brands for every taste and need. From globally established, award winning and innovative brands to newcomers to the market looking to make their mark.'); ?></p>
    </div>
    <div class="brand-list">
      <div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-4 row-cols-xl-5 justify-content-center">
        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres.html?mgs_brand=Bridgestone'; ?>" class="d-block"><span class="image brand-sprite bridgestone"></span></a>
        </div>
        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres.html?mgs_brand=Headway'; ?>" class="d-block"><span class="image brand-sprite falken"></span></a>
        </div>
        <div class="box">
          <a href="<?php echo $baseUrl.'all-tyres.html?mgs_brand=Maxxis'; ?>" class="d-block"><span class="image brand-sprite coopertires"></span></a>
        </div>
      </div>
    </div>
    <div class="show-all text-center">
      <a href="<?php echo $baseUrl.'all-tyre-brands'; ?>" class="button button-primary-100 text-uppercase button-rounded filled-slide-right"><span><?php echo __('SEE ALL BRANDS'); ?></span></a>
    </div>
  </div>
</div>