<?php
 $helper      = $this->helper("Lof\AdvancedReports\Helper\Data"); 
?>
<?php
/**
 * @see Ves_Advancedreports_Block_Adminhtml_Stats
 */
?>
<?php  
	$collection = $this->getReportCollection();
?>
<div class="animated flipInY  col-xs-4" id="reportCountries">
  <div class="x_panel top-payments">
    <div class="x_title">
      <h2><?php echo __("Top Countries"); ?></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-down"></i></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <?php  echo $helper->getSettingsSkin(array("target"=>"#reportCountries")); ?>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content" style="display: none">
      <div class="top-countries">
        <table class="countries_list">
          <tbody>
          	<?php if(0 < $collection->getSize()){ ?>
          	<?php foreach ($collection as $item){ ?>
          	<tr>
              <td><?php echo $this->localeLists->getCountryTranslation($item->getCountryId()); ?></td>
              <td class="fs15 fw700 text-right"><small><?php echo $this->formatCurrency($item->getTotalRevenueAmount());?></small></td>
            	</tr>
          	<?php } ?>
          	<?php } else { ?>
          	<tr>
              <td><?php echo __("No Records.");?></td>
            	</tr>		
          	<?php } ?>
          </tbody>
        </table>
         <p><a href="<?php echo $this->getCountriesReportLink(); ?>" title="<?php echo __("View Details"); ?>" target="_blank"><?php echo __("View Details"); ?> <i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></p>
      </div>
    </div>
  </div>
</div>