<?php if ($block->isCustomerAllowed() && $block->isValid()):
    $files = $block->getAttachedFiles(); ?>
    <div class="block block-order-details-view">
        <div class="block-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Order Attachments') ?></span>
        </div>
        <div class="block-content">
            <img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php echo __('Loading...'); ?>"
                 class="fileupload-loader"/>
            <form method="POST" enctype='multipart/form-data'
                  action="<?php echo $block->getUrl('orderupload/upload/save'); ?>"
                  data-hasrequired="<?php echo __('* Required Fields') ?>"
                  data-mage-init='{"validation":{}}'>
                <input type="hidden" name="order_id"
                       value="<?php echo $block->getOrderId(); ?>"/>
                <input type="hidden" name="customer_id"
                       value="<?php echo $block->getCustomerId(); ?>"/>
                <input type="hidden" name="form_key"
                       value="<?php echo $block->getFormKey(); ?>"/>
                <table class="data-table admin__table-primary edit-order-table order-orderupload-table">
                    <thead>
                    <tr class="headings">
                        <th class="cell-file"><?php echo __('File Name'); ?></th>
                        <th class="cell-comment"><?php echo __('Comment'); ?></th>
                        <th class="cell-updated"><?php echo __('Created On'); ?></th>
                        <?php if ($block->canDelete()): ?>
                            <th width="100" class="cell-remove last"><?php echo __('Remove'); ?></th>
                        <?php endif; ?>
                    </tr>
                    </thead>
                    <tbody id="meetanshi-orderupload-added">
                    <?php if (sizeof($files) > 0): ?>
                        <?php foreach ($files as $file): ?>
                            <?php if ($file['visible_customer_account']): ?>
                                <tr>
                                    <td>
                                    <span><a target="_blank"
                                             href="<?php echo $block->pubMediaPath() . $file['file_path']; ?>"><?php echo $file['file_name']; ?></a></span>
                                        <input type="hidden"
                                               name="orderupload[<?php echo $file['id']; ?>][file_exist]"
                                               value="<?php echo $file['id']; ?>"/>
                                        <input type="hidden"
                                               name="orderupload[<?php echo $file['id']; ?>][file_name]"
                                               value="<?php echo $file['file_name']; ?>"/>
                                        <input type="hidden"
                                               name="orderupload[<?php echo $file['id']; ?>][file_path]"
                                               value="<?php echo $file['file_path']; ?>"/>
                                    </td>
                                    <td><textarea rows="6" cols="25"
                                                  name="orderupload[<?php echo $file['id']; ?>][comment]"
                                                  title="<?php echo __('Comment') ?>"><?php echo $file['comment']; ?></textarea>
                                    </td>
                                    <td><?php echo $file['created_at']; ?></td>
                                    <?php if ($block->canDelete()): ?>
                                        <td>
                                            <div class="admin__actions-switch"
                                                 data-role="switcher">
                                                <input type="checkbox"
                                                       class="admin__actions-switch-checkbox"
                                                       id="removeItem<?php echo $file['id']; ?>"
                                                       name="orderupload[<?php echo $file['id']; ?>][remove]"
                                                       value="1">
                                                <label class="admin__actions-switch-label"
                                                       for="removeItem<?php echo $file['id']; ?>">
                                                <span class="admin__actions-switch-text"
                                                      data-text-on="Yes"
                                                      data-text-off="No"></span>
                                                </label>
                                            </div>
                                        </td>
                                    <?php endif; ?>
                                </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <script id="meetanshi-orderupload-added-template"
                            type="text/x-magento-template">

                        <tr>
                            <td>
                                <span><%- fileName %> (<%- fileSize %>)</span>
                                <input type="hidden"
                                       name="orderupload[<%- index %>][new_file]"
                                       value="1"/>
                                <input type="hidden"
                                       name="orderupload[<%- index %>][file_name]"
                                       value="<%- fileName %>"/>
                                <input type="hidden"
                                       name="orderupload[<%- index %>][file_path]"
                                       value="<%- file %>"/>
                            </td>
                            <td><textarea rows="6" cols="30"
                                          name="orderupload[<%- index %>][comment]"
                                          title="<?php echo __('Comment') ?>"></textarea></td>
                            <td><%- currentDate %></td>
                            <?php if ($block->canDelete()): ?>
                                <td>
                                    <div class="admin__actions-switch"
                                         data-role="switcher">
                                        <input type="checkbox"
                                               class="admin__actions-switch-checkbox"
                                               id="removeItem<%- index %>" name="orderupload[<%- index %>][remove]"
                                               value="1">
                                        <label class="admin__actions-switch-label"
                                               for="removeItem<%- index %>">
                                        <span class="admin__actions-switch-text"
                                              data-text-on="Yes"
                                              data-text-off="No"></span>
                                        </label>
                                    </div>
                                </td>
                            <?php endif; ?>
                        </tr>
                    </script>
                    </tbody>

                    <tfoot>
                    <tr>
                        <td colspan="4">
                            <div id="drop_file_zone" ondragover="return false" onclick="document.getElementById('meetanshi-orderupload').click()">
                                <div id="drag_upload_file">
                        <span class="meetanshi-file-upload" style="display: block;">
                            <span id="meetanshi-orderupload-add-link" class="meetanshi-file-upload__link"
                                  data-switch-title="<?php echo __('Drop files here') ?>"><?php echo __('Drop files here') ?></span>
                        <input type="file" id="meetanshi-orderupload" name="file[]" data-url="<?php echo $block->getFileUploadUrl(); ?>" multiple/>
                        </span>
                         <span style="font-size: 15px;"><?php echo __('Allowed file types : '.$block->getFileExtension());?></span>
                                </div>
                            </div>
                            <style>
                                #drop_file_zone {
                                    margin-top: 7px;
                                    margin-bottom: 10px;
                                    background-color: #EEE;
                                    border: #999 3px dashed;
                                    height: 100px;
                                    padding: 8px;
                                    font-size: 18px;
                                }
                                #meetanshi-orderupload{
                                    display: none;
                                }
                                #drag_upload_file {
                                    text-align: center;
                                    margin:20px auto;
                                }
                                #drag_upload_file span {
                                    text-align: center;
                                }
                            </style>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <div class="actions-toolbar">
                                <div class="primary" style="float: right;">
                                    <button type="submit"
                                            title="<?php echo __('Submit') ?>"
                                            class="action submit primary"
                                            style="margin-right: 0">
                                        <span><?php echo __('Submit') ?></span>
                                    </button>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>

                <div id="meetanshi-orderupload-allowedsize"
                     style="display: none;"><?php echo $block->allowedDocSizes(); ?></div>
                <div id="meetanshi-orderupload-maxFileSize"
                     style="display: none;"><?php echo $block->fileSize(); ?></div>
                <div id="meetanshi-orderupload-error" style="display: none;"></div>
                <script type="text/x-magento-init">
                {
                    "#meetanshi-orderupload": {
                        "meetanshiFileUpload": {
                            "addLink": "#meetanshi-orderupload-add-link",
                            "itemTemplate": "#meetanshi-orderupload-added-template",
                            "itemsContainer": "#meetanshi-orderupload-added",
                            "removeLinks": ".action-item-remove",
                            "errorContainer": "#meetanshi-orderupload-error",
                            "allowedSize": "#meetanshi-orderupload-allowedsize",
                            "maxFileSize": "#meetanshi-orderupload-maxFileSize"
                        }
                    }
                }

                </script>
            </form>
        </div>
    </div>
<?php endif; ?>
