<?php
/**
 * Copyright © 2017 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var MageWorx\OrdersGrid\Block\Adminhtml\System\Config\Buttons\Sync $block */
?>
<div id="mageworx-ordersgrid-sync-wrapper">
    <?php echo $block->getButtonHtml() ?>
    <div class="indicator" id="sync_span">
        <img class="sync_processing" hidden="hidden" alt="Processing"
             src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
        <img class="sync_success" hidden="hidden" alt="Success"
             src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
        <img class="sync_error" hidden="hidden" alt="Error"
             src="<?php echo $block->getViewFileUrl('images/rule_component_remove.gif') ?>"/>
        <span id="sync_message_span">
        </span>
    </div>
</div>
