<div class="tyre-search hide">
 <div class="search-wrap">
    <input type="text" placeholder="Search Tyres by Size" readonly>
    <div class="search-icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20.025 20.023">
          <path id="search" d="M78.114,20.545,73.3,15.728a7.57,7.57,0,1,0-2.007,2.007l4.817,4.817a.947.947,0,0,0,1.336,0l.668-.668A.948.948,0,0,0,78.114,20.545ZM67.035,16.208a4.731,4.731,0,1,1,4.731-4.731A4.731,4.731,0,0,1,67.035,16.208Z" transform="translate(-58.95 -3.394)" stroke="#707070" stroke-width="1" />
       </svg>
    </div>
 </div>
 <div class="search-vehicle">
    <span class="hover-transition"><?php echo __('Search by Vehicle'); ?></span>
 </div>
</div>