<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * @var $block \Magento\Sales\Block\Adminhtml\Items\Column\Name
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('catalogHelper');
?>
<?php if ($_item = $block->getItem()): ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->loadByAttribute('sku',$block->getSku($_item));
$checkProduct = $objectManager->get('Magento\Catalog\Model\Product');
?>
    <div id="order_item_<?= (int) $_item->getId() ?>_title"
         class="product-title">
		<p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
		<?php if($checkProduct->getIdBySku($block->getSku($_item))) {
		$productEditLink = $block->getUrl('catalog/product/edit', ['id' => $product->getId()]);
		?>
			<p class="size"><?php /* @escapeNotVerified */ echo __('Origin') ?>: <?= $product->getResource()->getAttribute("manufacturer")->getFrontend()->getValue($product); ?> <?= $product->getResource()->getAttribute("runflat")->getFrontend()->getValue($product) ?></p>
			<?php if($product->getStgCode() != ''):?>
				<p class="size"><?php /* @escapeNotVerified */ echo __('Supplier Code') ?>: <a href="<?php echo $productEditLink;?>" target="_blank"><?= $product->getStgCode(); ?></a></p>
			 <?php else:?>
				<p class="size"><?php /* @escapeNotVerified */ echo __('Supplier Code') ?>: <a href="<?php echo $productEditLink;?>" target="_blank"><?php /* @escapeNotVerified */ echo __('Add Supplier Code') ?></a></p>
			 <?php endif;?>
		<?php } ?>
    </div>
    <div class="product-sku-block">
        <span><?= $block->escapeHtml(__('SKU'))?>:</span>
        <?= /* @noEscape */ implode('<br />', $catalogHelper->splitSku($block->escapeHtml($block->getSku()))) ?>
    </div>

    <?php if ($block->getOrderOptions()): ?>
        <dl class="item-options">
            <?php foreach ($block->getOrderOptions() as $_option): ?>
                <dt><?= $block->escapeHtml($_option['label']) ?>:</dt>
                <dd>
                    <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                        <?= /* @noEscape */ $block->getCustomizedOptionValue($_option) ?>
                    <?php else: ?>
                        <?php $_option = $block->getFormattedOption($_option['value']); ?>
                        <?php $dots = 'dots' . uniqid(); ?>
                        <?php $id = 'id' . uniqid(); ?>
                        <?= $block->escapeHtml($_option['value'], ['a', 'br']) ?>
                        <?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                            <span id="<?= /* @noEscape */ $dots; ?>"> ...</span>
                            <span id="<?= /* @noEscape */ $id; ?>">
                                <?= $block->escapeHtml($_option['remainder'], ['a']) ?>
                            </span>
                            <?php $scriptString = <<<script
                                require(['prototype'], function() {

script;
                            $scriptString .= "$('" . /* @noEscape */ $id . "').hide();" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                             "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $id . "').show();});" .
                              PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $dots .
                                 "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $id .
                                 "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $dots .
                                 "').show();});" . PHP_EOL . "});" . PHP_EOL;
                            ?>
                            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?= $block->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>
